Repository hashicorp/nomad, pull requests merged in 2019-07, with the labels that each got.

#5804 Revised Nomad Enterprise page
  website/redirects.txt
  website/source/docs/enterprise/autopilot/index.html.md
  website/source/docs/enterprise/index.html.md
  website/source/docs/enterprise/namespaces/index.html.md
  website/source/docs/enterprise/preemption/index.html.md
  website/source/docs/enterprise/quotas/index.html.md
  website/source/docs/enterprise/sentinel/index.html.md
  website/source/guides/operations/index.html.md
  website/source/layouts/docs.erb
Labels: docs

#5915 Use consistent casing in the JSON representation of the AllocFileInfo struct
  client/structs/structs.go
Labels: api

#5909 Merge pull request #5804 from hashicorp/yishan/revised-enterprise-docs
  website/redirects.txt
  website/source/docs/enterprise/autopilot/index.html.md
  website/source/docs/enterprise/index.html.md
  website/source/docs/enterprise/namespaces/index.html.md
  website/source/docs/enterprise/preemption/index.html.md
  website/source/docs/enterprise/quotas/index.html.md
  website/source/docs/enterprise/sentinel/index.html.md
  website/source/guides/operations/index.html.md
  website/source/layouts/docs.erb
Labels: docs

#5926 UI: Add copy button for client/allocation UUIDs
  CHANGELOG.md
  ui/app/components/addon-copy-button.js
  ui/app/components/copy-button.js
  ui/app/styles/components.scss
  ui/app/styles/components/copy-button.scss
  ui/app/styles/components/tooltip.scss
  ui/app/styles/core/buttons.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/clients/client.hbs
  ui/app/templates/components/copy-button.hbs
  ui/app/templates/components/freestyle/sg-copy-button.hbs
  ui/app/templates/freestyle.hbs
  ui/ember-cli-build.js
  ui/package.json
  ui/tests/integration/components/copy-button-test.js
  ui/yarn.lock
Labels: 0.9.4

#5962 Added line around interoperability to Downloads page.
  website/source/downloads.html.erb
Labels: docs

#5967 Add interoperability sentence to Downloads docs
  website/source/downloads.html.erb
Labels: docs

#5837 Avoid de-registering slowly restored services
  command/agent/consul/client.go
  command/agent/consul/unit_test.go
Labels: 0.9.4

#5948 Collect driver stats when driver plugins are restarted
  client/allocrunner/taskrunner/stats_hook.go
  plugins/drivers/client.go
Labels: 0.9.4

#5791 nomad: include snapshot index when submitting plans
  nomad/plan_apply.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/structs.go
  nomad/worker.go
  nomad/worker_test.go
Labels: 0.9.4

#5870 api: return X-Nomad-Index header on allocation stop
  api/allocations.go
  command/agent/alloc_endpoint.go
  command/agent/alloc_endpoint_test.go
Labels: 0.9.4

#5924 UI: Add page titles
  CHANGELOG.md
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/allocations/allocation/task/logs.hbs
  ui/app/templates/application.hbs
  ui/app/templates/clients/client.hbs
  ui/app/templates/clients/index.hbs
  ui/app/templates/head.hbs
  ui/app/templates/jobs/index.hbs
  ui/app/templates/jobs/job/allocations.hbs
  ui/app/templates/jobs/job/definition.hbs
  ui/app/templates/jobs/job/deployments.hbs
  ui/app/templates/jobs/job/evaluations.hbs
  ui/app/templates/jobs/job/index.hbs
  ui/app/templates/jobs/job/task-group.hbs
  ui/app/templates/jobs/job/versions.hbs
  ui/app/templates/jobs/run.hbs
  ui/app/templates/servers/index.hbs
  ui/app/templates/servers/server.hbs
  ui/app/templates/settings/tokens.hbs
  ui/package.json
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/clients-list-test.js
  ui/tests/acceptance/job-allocations-test.js
  ui/tests/acceptance/job-definition-test.js
  ui/tests/acceptance/job-deployments-test.js
  ui/tests/acceptance/job-evaluations-test.js
  ui/tests/acceptance/job-run-test.js
  ui/tests/acceptance/job-versions-test.js
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/acceptance/regions-test.js
  ui/tests/acceptance/server-detail-test.js
  ui/tests/acceptance/servers-list-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/acceptance/task-logs-test.js
  ui/tests/acceptance/token-test.js
  ui/tests/helpers/module-for-job.js
  ui/yarn.lock
Labels: 0.9.4

#5900 System scheduler blocked evals
  nomad/blocked_evals.go
  nomad/blocked_evals_system.go
  nomad/blocked_evals_test.go
  nomad/fsm.go
  nomad/worker.go
  scheduler/generic_sched.go
  scheduler/system_sched.go
Labels: 0.9.4

#5975 consul: fix deadlock in check-based restarts
  command/agent/consul/check_watcher.go
  command/agent/consul/check_watcher_test.go
Labels: 0.9.4

#5976 Update consul-template dependency to latest
  client/allocrunner/taskrunner/template/template.go
  vendor/github.com/hashicorp/consul-template/CHANGELOG.md
  vendor/github.com/hashicorp/consul-template/Makefile
  vendor/github.com/hashicorp/consul-template/README.md
  vendor/github.com/hashicorp/consul-template/cli.go
  vendor/github.com/hashicorp/consul-template/config/config.go
  vendor/github.com/hashicorp/consul-template/dependency/vault_common.go
  vendor/github.com/hashicorp/consul-template/manager/dedup.go
  vendor/github.com/hashicorp/consul-template/manager/runner.go
  vendor/github.com/hashicorp/consul-template/version/version.go
  vendor/vendor.json
Labels: 0.9.4

#5951 reduce CPU usage running large numbers of clients
  drivers/shared/executor/executor.go
  drivers/shared/executor/executor_basic.go
  drivers/shared/executor/executor_universal_linux.go
  drivers/shared/executor/pid_collector.go
  drivers/shared/executor/resource_container_linux.go
Labels: 0.9.4

#5953 jobs update stanza merging cleanup
  api/jobs.go
  api/jobs_test.go
  api/tasks_test.go
Labels: 0.9.4

#5972 add formatting for hcl parsing error messages
  client/allocrunner/taskrunner/task_runner.go
  helper/pluginutils/hclutils/testing.go
  helper/pluginutils/hclutils/util.go
  helper/pluginutils/hclutils/util_test.go
  helper/pluginutils/loader/init.go
  nomad/structs/structs.go
  plugins/shared/cmd/launcher/command/device.go
Labels: 0.9.4

#5991 executor_universal_linux raw_exec cgroup failure is not fatal
  drivers/shared/executor/executor_universal_linux.go
Labels: 0.9.4

#5990 logmon: Workaround golang/go#29119
  client/logmon/logging/rotator.go
  client/logmon/logmon.go
  client/logmon/logmon_test.go
Labels: 0.9.4

#5853 Service and Batch Job Preemption Guide
  website/source/guides/operating-a-job/advanced-scheduling/preemption-service-batch.html.md
  website/source/guides/operating-a-job/advanced-scheduling/spread.html.md
  website/source/layouts/guides.erb
Labels: docs
