Repository hashicorp/nomad, pull requests merged in 2019-06, with the labels that each got.

#5737 Fix restart attempts of `restart` stanza in `delay` mode.
  client/allocrunner/taskrunner/restarts/restarts.go
Labels: bug, post-0.9.2

#5746 set node.StatusUpdatedAt in raft
  nomad/drainer/watch_nodes_test.go
  nomad/drainer_shims.go
  nomad/fsm.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/structs.go
Labels: post-0.9.2

#5828 UI Screenshots script
  GNUmakefile
  scripts/.gitignore
  scripts/screenshots/Dockerfile
  scripts/screenshots/src/index.js
  scripts/screenshots/src/package.json
  scripts/screenshots/src/utils.js
  scripts/screenshots/src/yarn.lock
  ui/app/components/job-page/parts/recent-allocations.js
  ui/config/environment.js
  ui/mirage/scenarios/default.js
Labels: docs, ui

#5866 UI: Allocation file system explorer: Routing
  ui/app/router.js
  ui/app/routes/allocations/allocation/task/fs/path.js
  ui/app/templates/allocations/allocation/task/fs.hbs
  ui/app/templates/allocations/allocation/task/fs/index.hbs
  ui/app/templates/allocations/allocation/task/fs/path.hbs
  ui/app/templates/allocations/allocation/task/subnav.hbs
  ui/tests/acceptance/task-fs-path-test.js
  ui/tests/acceptance/task-fs-test.js
  ui/tests/pages/allocations/task/fs.js
  ui/tests/pages/allocations/task/fs/path.js
Labels: ui

#5902 UI: Account for the search icon within the is-compact modifier
  ui/app/styles/components/search-box.scss
Labels: ui
