Repository hashicorp/nomad, pull requests merged in 2019-12, with the labels that each got.

#6779 Use AWS SDK to access EC2 Metadata
  client/fingerprint/env_aws.go
  client/fingerprint/env_aws_test.go
  client/fingerprint/fingerprint_test.go
Labels: client, fingerprint

#6591 Docs: Remove the old UI guide
  website/source/guides/ui.html.md
  website/source/guides/web-ui/operating-a-job.html.md
  website/source/redirects.txt
Labels: docs

#6790 Deploy remove old ui guide
  website/source/guides/ui.html.md
  website/source/guides/web-ui/operating-a-job.html.md
  website/source/redirects.txt
Labels: docs

#6788 logmon: add timeout to RPC operations
  client/logmon/client.go
Labels: client

#6808 UI: Unclosed log streams
  ui/app/utils/classes/stream-logger.js
  ui/tests/unit/utils/stream-logger-test.js
Labels: ui

#6817 UI: Fix client sorting
  ui/app/components/client-node-row.js
  ui/app/controllers/clients/index.js
  ui/app/mixins/sortable-factory.js
  ui/app/mixins/sortable.js
  ui/app/models/node.js
  ui/app/styles/components/node-status-light.scss
  ui/app/templates/clients/index.hbs
  ui/app/templates/components/client-node-row.hbs
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/clients-list-test.js
  ui/tests/pages/clients/list.js
Labels: bug, ui

#6852 UI: Fix flapping status light test
  ui/tests/acceptance/client-detail-test.js
Labels: bug, ui

#6820 driver: allow disabling log collection
  client/allocrunner/taskrunner/logmon_hook.go
  client/allocrunner/taskrunner/logmon_hook_test.go
  client/allocrunner/taskrunner/logmon_hook_unix_test.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  drivers/docker/config.go
  drivers/docker/config_test.go
  drivers/docker/driver.go
  drivers/docker/handle.go
  plugins/drivers/driver.go
Labels: driver/docker, logging

#6870 csi: Fingerprint Controller Capabilities
  client/pluginmanager/csimanager/instance.go
  client/pluginmanager/csimanager/instance_test.go
  nomad/structs/node.go
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
Labels: fingerprint, storage

#6871 csi: Fingerprint node capabilities
  client/pluginmanager/csimanager/instance.go
  client/pluginmanager/csimanager/instance_test.go
  nomad/structs/node.go
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
  plugins/csi/testing/client.go
Labels: fingerprint, storage

#6876 [docs] Migrating Web-UI and Governance Guides to learn
  website/source/api/sentinel-policies.html.md
  website/source/docs/enterprise/index.html.md
  website/source/docs/job-specification/job.html.md
  website/source/guides/governance-and-policy/index.html.md
  website/source/guides/governance-and-policy/namespaces.html.markdown
  website/source/guides/governance-and-policy/quotas.html.md
  website/source/guides/governance-and-policy/sentinel/job.html.md
  website/source/guides/governance-and-policy/sentinel/sentinel-policy.html.markdown
  website/source/guides/install/production/reference-architecture.html.md
  website/source/guides/web-ui/access.html.md
  website/source/guides/web-ui/index.html.md
  website/source/guides/web-ui/inspecting-the-cluster.html.md
  website/source/guides/web-ui/operating-a-job.html.md
  website/source/guides/web-ui/securing.html.md
  website/source/guides/web-ui/submitting-a-job.html.md
  website/source/layouts/guides.erb
  website/source/redirects.txt
Labels: docs

#6886 Add CSI Plugin info to `nomad node status`
  api/nodes.go
  command/node_status.go
Labels: cli, storage

#6885 docs: Fix bad link to UI Guide track
  website/source/guides/web-ui/index.html.md
Labels: docs
