Repository hashicorp/nomad, pull requests merged in 2019-09, with the labels that each got.

#6108 UI: add Consul Connect features
  CHANGELOG.md
  ui/app/components/proxy-tag.js
  ui/app/controllers/allocations/allocation/index.js
  ui/app/models/allocation.js
  ui/app/models/consul-connect.js
  ui/app/models/network.js
  ui/app/models/service.js
  ui/app/models/sidecar-proxy-upstream.js
  ui/app/models/sidecar-proxy.js
  ui/app/models/sidecar-service.js
  ui/app/models/task-group.js
  ui/app/models/task-state.js
  ui/app/serializers/allocation.js
  ui/app/serializers/network.js
  ui/app/serializers/service.js
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/components/freestyle/sg-proxy-tag.hbs
  ui/app/templates/components/proxy-tag.hbs
  ui/app/templates/components/task-row.hbs
  ui/app/templates/freestyle.hbs
  ui/mirage/common.js
  ui/mirage/factories/allocation.js
  ui/mirage/factories/job.js
  ui/mirage/factories/service.js
  ui/mirage/factories/task-group.js
  ui/mirage/factories/task-state.js
  ui/mirage/models/service.js
  ui/mirage/models/task-group.js
  ui/mirage/serializers/task-group.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/pages/allocations/detail.js
  ui/tests/pages/allocations/task/detail.js
Labels: ui

#6267 UI: Add handling for not-running task filesystem query
  ui/app/routes/allocations/allocation/task/fs.js
  ui/tests/acceptance/task-fs-test.js
Labels: ui

#6271 UI: Move kind property to task
  ui/app/models/task-state.js
  ui/app/models/task.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
Labels: ui

#6275 UI: Restore Connect proxy tag tests
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
Labels: ui

#6284 UI: Remove Connect proxy tag tests again
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
Labels: ui

#6301 docs: Convert resources page to Markdown
  website/source/resources.html.markdown
Labels: docs

#6274 UI: Restore local headless testing
  ui/testem.js
Labels: ui

#6330 client: Fail startup if host volumes do not exist
  client/client.go
Labels: storage

#6343 UI: Fix Connect proxy tag
  ui/app/models/task-state.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
Labels: ui

#6359 UI: Remove proxy tag tests again
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
Labels: bug, ui

#6358 client/connect: ConsulProxy LocalServicePort/Address
  api/services.go
  api/services_test.go
  command/agent/consul/client.go
  command/agent/consul/group_test.go
  command/agent/job_endpoint.go
  jobspec/parse_service.go
  jobspec/test-fixtures/tg-network.hcl
  nomad/structs/diff_test.go
  nomad/structs/services.go
  nomad/structs/services_test.go
  website/source/docs/job-specification/network.html.md
  website/source/docs/job-specification/proxy.html.md
Labels: consul/connect, enhancement

#6383 doc: clarify command path requirements for exec
  website/source/docs/drivers/exec.html.md
Labels: docs, driver/exec

#6360 UI: Restore proxy tag tests
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
Labels: bug, ui

#6166 UI: Update Mirage to 1.1.0
  ui/mirage/common.js
  ui/mirage/factories/agent.js
  ui/mirage/factories/alloc-file.js
  ui/mirage/factories/allocation.js
  ui/mirage/factories/client-stat.js
  ui/mirage/factories/deployment-task-group-summary.js
  ui/mirage/factories/deployment.js
  ui/mirage/factories/evaluation.js
  ui/mirage/factories/job-summary.js
  ui/mirage/factories/job-version.js
  ui/mirage/factories/job.js
  ui/mirage/factories/namespace.js
  ui/mirage/factories/node-event.js
  ui/mirage/factories/node.js
  ui/mirage/factories/policy.js
  ui/mirage/factories/service.js
  ui/mirage/factories/task-event.js
  ui/mirage/factories/task-group.js
  ui/mirage/factories/task-state.js
  ui/mirage/factories/task.js
  ui/mirage/factories/token.js
  ui/mirage/utils.js
  ui/package.json
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/application-errors-test.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/clients-list-test.js
  ui/tests/acceptance/job-allocations-test.js
  ui/tests/acceptance/job-definition-test.js
  ui/tests/acceptance/job-deployments-test.js
  ui/tests/acceptance/job-detail-test.js
  ui/tests/acceptance/job-evaluations-test.js
  ui/tests/acceptance/job-run-test.js
  ui/tests/acceptance/job-versions-test.js
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/acceptance/namespaces-test.js
  ui/tests/acceptance/regions-test.js
  ui/tests/acceptance/server-detail-test.js
  ui/tests/acceptance/servers-list-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/acceptance/task-logs-test.js
  ui/tests/acceptance/token-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/integration/list-table-test.js
  ui/yarn.lock
Labels: ui

#6357 doc: clarify driver support for netns/connect
  website/source/docs/job-specification/network.html.md
  website/source/guides/integrations/consul-connect/index.html.md
Labels: consul/connect, docs

#6387 UI: Change factories to be more dynamic
  ui/mirage/factories/agent.js
  ui/mirage/factories/allocation.js
  ui/mirage/factories/client-stat.js
  ui/mirage/factories/deployment-task-group-summary.js
  ui/mirage/factories/deployment.js
  ui/mirage/factories/evaluation.js
  ui/mirage/factories/job.js
  ui/mirage/factories/node-event.js
  ui/mirage/factories/node.js
  ui/mirage/factories/task-event.js
  ui/mirage/factories/task-state.js
  ui/mirage/factories/task.js
Labels: enhancement, ui
