Repository hashicorp/nomad, pull requests merged in 2019-08, with the labels that each got.

#6067 Remove transition animation from sort arrows
  ui/app/styles/components/fs-explorer.scss
Labels: ui

#6003 nomad: add job status metrics
  nomad/leader.go
  website/source/docs/telemetry/metrics.html.md
Labels: metrics

#5923 Initial support for Host Volumes
  api/tasks.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  client/allocrunner/taskrunner/volume_hook.go
  client/client.go
  client/config/config.go
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/job_endpoint.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  jobspec/parse.go
  jobspec/parse_test.go
  jobspec/test-fixtures/basic.hcl
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  nomad/structs/volumes.go
  plugins/drivers/driver.go
  scheduler/feasible.go
  scheduler/feasible_test.go
  scheduler/stack.go
  scheduler/stack_oss.go
Labels: storage

#6103 syntax fix; add example for alloc exec -task
  website/source/docs/commands/alloc/exec.html.md.erb
Labels: docs

#6142 Add a link to the discussion forum on the resources page
  website/source/resources.html.erb
Labels: docs

#6048 UI: Alloc FS: File Viewer
  ui/app/adapters/task-state.js
  ui/app/components/fs-breadcrumbs.js
  ui/app/components/fs-directory-entry.js
  ui/app/components/image-file.js
  ui/app/components/streaming-file.js
  ui/app/components/task-file.js
  ui/app/components/task-log.js
  ui/app/controllers/allocations/allocation/task/fs.js
  ui/app/routes/allocations/allocation/task/fs.js
  ui/app/styles/components.scss
  ui/app/styles/components/empty-message.scss
  ui/app/styles/components/image-file.scss
  ui/app/styles/components/page-layout.scss
  ui/app/styles/core/buttons.scss
  ui/app/templates/allocations/allocation/task/fs.hbs
  ui/app/templates/components/fs-breadcrumbs.hbs
  ui/app/templates/components/image-file.hbs
  ui/app/templates/components/streaming-file.hbs
  ui/app/templates/components/task-file.hbs
  ui/app/templates/components/task-log.hbs
  ui/app/utils/classes/log.js
  ui/app/utils/classes/poll-logger.js
  ui/app/utils/classes/stream-logger.js
  ui/app/utils/stream-frames.js
  ui/mirage/config.js
  ui/mirage/factories/alloc-file.js
  ui/mirage/models/alloc-file.js
  ui/mirage/scenarios/default.js
  ui/tests/acceptance/task-fs-test.js
  ui/tests/integration/image-file-test.js
  ui/tests/integration/streaming-file-test.js
  ui/tests/integration/task-file-test.js
  ui/tests/integration/task-log-test.js
  ui/tests/unit/adapters/node-test.js
  ui/tests/unit/utils/log-test.js
  ui/tests/unit/utils/stream-frames-test.js
Labels: ui

#6158 UI: Use the standard empty message when an fs dir is empty
  ui/app/templates/allocations/allocation/task/fs.hbs
  ui/tests/acceptance/task-fs-test.js
  ui/tests/pages/allocations/task/fs.js
Labels: ui

#5871 UI: Allocation file system explorer
  ui/app/adapters/task-state.js
  ui/app/components/fs-breadcrumbs.js
  ui/app/components/fs-directory-entry.js
  ui/app/components/image-file.js
  ui/app/components/streaming-file.js
  ui/app/components/task-file.js
  ui/app/components/task-log.js
  ui/app/components/task-subnav.js
  ui/app/controllers/allocations/allocation/task/fs-root.js
  ui/app/controllers/allocations/allocation/task/fs.js
  ui/app/models/task-state.js
  ui/app/router.js
  ui/app/routes/allocations/allocation/task/fs-root.js
  ui/app/routes/allocations/allocation/task/fs.js
  ui/app/styles/components.scss
  ui/app/styles/components/boxed-section.scss
  ui/app/styles/components/empty-message.scss
  ui/app/styles/components/fs-explorer.scss
  ui/app/styles/components/image-file.scss
  ui/app/styles/components/page-layout.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/table.scss
  ui/app/styles/core/tabs.scss
  ui/app/templates/allocations/allocation/task/fs.hbs
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/allocations/allocation/task/logs.hbs
  ui/app/templates/allocations/allocation/task/subnav.hbs
  ui/app/templates/components/fs-breadcrumbs.hbs
  ui/app/templates/components/fs-directory-entry.hbs
  ui/app/templates/components/image-file.hbs
  ui/app/templates/components/streaming-file.hbs
  ui/app/templates/components/task-file.hbs
  ui/app/templates/components/task-log.hbs
  ui/app/templates/components/task-subnav.hbs
  ui/app/utils/classes/log.js
  ui/app/utils/classes/poll-logger.js
  ui/app/utils/classes/stream-logger.js
  ui/app/utils/stream-frames.js
  ui/mirage/config.js
  ui/mirage/factories/alloc-file.js
  ui/mirage/models/alloc-file.js
  ui/mirage/scenarios/default.js
  ui/tests/acceptance/task-fs-test.js
  ui/tests/integration/image-file-test.js
  ui/tests/integration/streaming-file-test.js
  ui/tests/integration/task-file-test.js
  ui/tests/integration/task-log-test.js
  ui/tests/pages/allocations/task/fs.js
  ui/tests/unit/adapters/node-test.js
  ui/tests/unit/utils/log-test.js
  ui/tests/unit/utils/stream-frames-test.js
Labels: ui

#6180 Fine grained ACLs for Host Volumes
  acl/policy.go
  acl/policy_test.go
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
Labels: storage

#6175 remove hidden field from host volumes
  api/nodes.go
  api/tasks.go
  command/agent/job_endpoint.go
  command/node_status.go
  nomad/structs/volumes.go
Labels: storage

#6190 ar: fix bridge networking port mapping when port.To is unset
  client/allocrunner/networking_bridge_linux.go
Labels: bug, networking
