Repository hashicorp/nomad, pull requests merged in 2020-01, with the labels that each got.

#6915 [docs] Change consul agent note to callout
  website/source/docs/configuration/consul.html.md
Labels: docs

#6932 csi: gRPC Logging Middlware
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
  client/client.go
  client/pluginmanager/csimanager/instance.go
  helper/grpc-middleware/logging/client_interceptors.go
  helper/grpc-middleware/logging/options.go
  plugins/csi/client.go
  vendor/github.com/hashicorp/go-hclog/interceptlogger.go
  vendor/github.com/hashicorp/go-hclog/intlogger.go
  vendor/github.com/hashicorp/go-hclog/logger.go
  vendor/github.com/hashicorp/go-hclog/nulllogger.go
  vendor/vendor.json
Labels: logging, storage

#6901 CSI Volumes API Client
  api/csi.go
  api/csi_test.go
  command/agent/csi_endpoint.go
  command/agent/http.go
  contributing/checklist-command.md
  nomad/csi_volume_endpoint_test.go
  nomad/rpc.go
Labels: api, storage

#5944 UI: Change Run Job availability based on ACLs
  ui/app/abilities/job.js
  ui/app/models/policy.js
  ui/app/routes/application.js
  ui/app/routes/jobs/run.js
  ui/app/services/token.js
  ui/app/styles/components/tooltip.scss
  ui/app/templates/jobs/index.hbs
  ui/mirage/config.js
  ui/package.json
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/job-allocations-test.js
  ui/tests/acceptance/job-definition-test.js
  ui/tests/acceptance/job-deployments-test.js
  ui/tests/acceptance/job-detail-test.js
  ui/tests/acceptance/job-evaluations-test.js
  ui/tests/acceptance/job-run-test.js
  ui/tests/acceptance/job-versions-test.js
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/acceptance/regions-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/pages/jobs/list.js
  ui/tests/unit/abilities/job-test.js
  ui/yarn.lock
Labels: enhancement, ui

#6819 UI: Invoke Node Drains
  ui/app/adapters/node.js
  ui/app/components/drain-popover.js
  ui/app/components/popover-menu.js
  ui/app/components/toggle.js
  ui/app/components/two-step-button.js
  ui/app/controllers/clients/client.js
  ui/app/models/allocation.js
  ui/app/models/node.js
  ui/app/routes/clients/client.js
  ui/app/serializers/allocation.js
  ui/app/styles/components.scss
  ui/app/styles/components/dropdown.scss
  ui/app/styles/components/inline-definitions.scss
  ui/app/styles/components/node-status-light.scss
  ui/app/styles/components/popover-menu.scss
  ui/app/styles/components/toggle.scss
  ui/app/styles/components/toolbar.scss
  ui/app/styles/components/tooltip.scss
  ui/app/styles/components/two-step-button.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/forms.scss
  ui/app/styles/core/icon.scss
  ui/app/styles/core/section.scss
  ui/app/styles/core/title.scss
  ui/app/styles/utils/z-indices.scss
  ui/app/templates/clients/client.hbs
  ui/app/templates/components/drain-popover.hbs
  ui/app/templates/components/popover-menu.hbs
  ui/app/templates/components/toggle.hbs
  ui/app/templates/components/two-step-button.hbs
  ui/mirage/config.js
  ui/package.json
  ui/tests/acceptance/client-detail-test.js
  ui/tests/integration/popover-menu-test.js
  ui/tests/integration/toggle-test.js
  ui/tests/pages/clients/detail.js
  ui/tests/pages/components/notification.js
  ui/tests/pages/components/popover-menu.js
  ui/tests/pages/components/toggle.js
  ui/tests/unit/adapters/node-test.js
  ui/yarn.lock
Labels: ui

#6997 docs: reseting bootstrap doesn't invalidate token
  website/source/guides/security/acl.html.markdown
Labels: docs

#6966 csi: server-side plugin state tracking and api
  api/csi.go
  api/csi_test.go
  command/agent/csi_endpoint.go
  command/agent/http.go
  contributing/checklist-rpc-endpoint.md
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/server.go
  nomad/state/schema.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/csi.go
  nomad/structs/csi_test.go
  nomad/structs/errors.go
Labels: volumes

#7028 UI: Disable client write actions when ACL token only allows client read
  ui/app/abilities/client.js
  ui/app/abilities/job.js
  ui/app/components/drain-popover.js
  ui/app/components/popover-menu.js
  ui/app/controllers/settings/tokens.js
  ui/app/services/system.js
  ui/app/services/token.js
  ui/app/styles/core/buttons.scss
  ui/app/templates/clients/client.hbs
  ui/app/templates/components/drain-popover.hbs
  ui/app/templates/components/popover-menu.hbs
  ui/app/templates/jobs/index.hbs
  ui/stories/components/buttons.stories.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/helpers/setup-ability.js
  ui/tests/pages/clients/detail.js
  ui/tests/unit/abilities/client-test.js
  ui/tests/unit/abilities/job-test.js
Labels: ui

#7043 Pass stats interval colleciton to executor
  CHANGELOG.md
  drivers/shared/executor/client.go
Labels: driver/exec, metrics
