Repository hashicorp/nomad, pull requests merged in 2020-10, with the labels that each got.

#9005 e2e: tfvars.dev file must override default tfvars file
  e2e/terraform/terraform.tfvars.dev
Labels: theme/testing

#8849 [Feature] Configure nomad cluster to use a Consul Namespace [Consul Enterprise]
  CHANGELOG.md
  client/allocrunner/taskrunner/envoybootstrap_hook.go
  client/allocrunner/taskrunner/template/template.go
  nomad/structs/config/consul.go
  website/pages/docs/configuration/consul.mdx
Labels: stage/waiting-reply, theme/consul, theme/consul-template, theme/consul/connect, type/enhancement

#8913 [docs] Fix inconsistencies in docker-helper-ecr-login examples
  website/pages/docs/drivers/docker.mdx
Labels: theme/docs

#8998 Use 32-byte key for gossip encryption to enable AES-256
  command/agent/agent.go
  command/agent/keyring.go
  command/agent/keyring_test.go
  command/agent/testagent.go
  command/operator_keygen.go
  command/operator_keygen_test.go
  website/pages/docs/commands/operator/keygen.mdx
  website/pages/docs/configuration/server.mdx
Labels: theme/security, type/enhancement

#9008 [doc] fix deprecated port_map example
  website/pages/docs/job-specification/network.mdx
Labels: theme/docs, type/bug

#9020 job, task group, and task IDs should not allow null characters
  CHANGELOG.md
  api/jobs_test.go
  command/agent/command.go
  command/agent/command_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  website/pages/docs/upgrade/upgrade-specific.mdx
Labels: theme/breaking-change

#9025 cli: add policy list and info to new scaling cmd.
  command/commands.go
  command/scaling.go
  command/scaling_policy.go
  command/scaling_policy_info.go
  command/scaling_policy_info_test.go
  command/scaling_policy_list.go
  command/scaling_policy_list_test.go
  command/scaling_policy_test.go
Labels: theme/cli, type/enhancement

#9033 Do not double-remove checks removed by Consul
  command/agent/consul/catalog_testing.go
  command/agent/consul/client.go
Labels: stage/accepted, theme/consul

#9023 cli: add scale and scaling-events commands to job cmd.
  command/commands.go
  command/job_scale.go
  command/job_scale_test.go
  command/job_scaling_events.go
  command/job_scaling_events_test.go
Labels: theme/cli, type/enhancement

#9037 changelog: add entries for #9023 and #9025
  CHANGELOG.md
Labels: theme/docs, type/enhancement

#9042 [Website] Add new HashiStackMenu
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
Labels: theme/website

#9075 UI: Change htmlSafe prototype calls to imports
  ui/app/components/line-chart.js
  ui/app/utils/properties/style-string.js
Labels: theme/ui, type/bug

#9080 removed backwards-compatible/untagged metrics deprecated in 0.7
  CHANGELOG.md
  client/allocrunner/taskrunner/task_runner.go
  client/client.go
  client/config/config.go
  command/agent/agent.go
  command/agent/agent_test.go
  command/agent/command.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/metrics_endpoint_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/leader.go
  website/pages/docs/configuration/telemetry.mdx
  website/pages/docs/upgrade/upgrade-specific.mdx
Labels: theme/config, theme/docs, theme/metrics

#9092 Fix robots.txt to disallow indexing of all paths
  ui/public/robots.txt
Labels: theme/security, theme/ui

#9083 agent: fix enterprise config overlay merging.
  command/agent/command.go
Labels: theme/config, type/bug

#9084 docs: update website and changelog for GH-9083
  CHANGELOG.md
  website/pages/docs/configuration/index.mdx
Labels: theme/docs, type/enhancement

#9064 Enforce bounds on MaxQueryTime
  nomad/rpc.go
  nomad/structs/structs.go
Labels: stage/waiting-reply

#9102 [Website] Update HSM version w/ waypoint
  website/package-lock.json
  website/package.json
Labels: theme/website

#9106 UI: Update loading spinner to be logo-based
  ui/app/components/loading-spinner.js
  ui/app/styles/components/loading-spinner.scss
  ui/app/templates/components/loading-spinner.hbs
  ui/public/images/icons/nomad-logo-n.svg
Labels: theme/ui, type/enhancement

#9128 UI: Remove logo spin for prefers-reduced-motion
  ui/app/styles/components/loading-spinner.scss
Labels: theme/ui, type/bug

#9140 UI: Add logged Faker seed when none is set in tests
  ui/mirage/faker.js
Labels: theme/ui, type/enhancement

#9156 Document new `expirationDate` prop for AlertBanner
  website/data/alert-banner.js
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: theme/website

#9169 Fix a command typo of vault token create
  website/pages/docs/integrations/vault-integration.mdx
Labels: theme/docs, type/bug

#9174 website: bump default version to 0.12.7.
  website/data/version.js
Labels: theme/docs, type/enhancement

#9173 UI: Show the nomad agent version of the agent the UI is served from
  ui/app/services/system.js
  ui/app/styles/components/gutter.scss
  ui/app/templates/components/gutter-menu.hbs
  ui/mirage/config.js
  ui/tests/acceptance/regions-test.js
Labels: theme/ui

#9172 UI: Always show the file browser for allocations and tasks.
  ui/app/routes/allocations/allocation/fs.js
  ui/app/routes/allocations/allocation/task/fs.js
  ui/app/templates/components/fs/browser.hbs
  ui/tests/acceptance/allocation-fs-test.js
  ui/tests/acceptance/task-fs-test.js
Labels: theme/ui

#9167 UI: topo viz refinements
  ui/app/components/flex-masonry.js
  ui/app/components/topo-viz.js
  ui/app/models/allocation.js
  ui/app/styles/charts/topo-viz-node.scss
  ui/app/styles/components/dashboard-metric.scss
  ui/app/templates/components/flex-masonry.hbs
  ui/app/templates/components/topo-viz.hbs
  ui/app/templates/topology.hbs
  ui/tests/integration/components/flex-masonry-test.js
  ui/tests/integration/components/topo-viz-test.js
Labels: theme/ui

#9166 Display class in client details
  ui/app/templates/clients/client/index.hbs
Labels: theme/ui

#9143 docs: add new scaling command website documentation.
  website/data/docs-navigation.js
  website/pages/docs/commands/scaling/index.mdx
  website/pages/docs/commands/scaling/policy-info.mdx
  website/pages/docs/commands/scaling/policy-list.mdx
Labels: theme/docs, type/enhancement

#9162 docs: add new job scale and scaling-events CLI website docs.
  website/data/docs-navigation.js
  website/pages/docs/commands/job/scale.mdx
  website/pages/docs/commands/job/scaling-events.mdx
Labels: theme/docs, type/enhancement

#9194 docs: update Autoscaler agent docs with policy_eval config params.
  website/pages/docs/autoscaling/agent.mdx
Labels: theme/docs, type/enhancement

#9193 docs: DAS related documentation updates
  website/data/api-navigation.js
  website/pages/api-docs/recommendations.mdx
  website/pages/api-docs/scaling-policies.mdx
  website/pages/docs/autoscaling/index.mdx
  website/pages/docs/autoscaling/plugins/strategy.mdx
  website/pages/docs/autoscaling/plugins/target.mdx
  website/pages/docs/autoscaling/policy.mdx
  website/pages/docs/enterprise.mdx
Labels: theme/docs, type/enhancement

#9214 Update dependencies, fix vercel build cache issue
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: theme/website

#9181 UI: Update the warning icon
  scripts/screenshots/src/index.js
  scripts/screenshots/src/package.json
  scripts/screenshots/src/yarn.lock
  ui/app/helpers/all-icons.js
  ui/app/styles/storybook.scss
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/components/allocation-row.hbs
  ui/app/templates/components/allocation-stat.hbs
  ui/app/templates/components/client-node-row.hbs
  ui/app/templates/components/plugin-allocation-row.hbs
  ui/app/templates/components/reschedule-event-timeline.hbs
  ui/app/templates/components/task-row.hbs
  ui/public/images/icons/warning.svg
  ui/stories/theme/icons.stories.js
Labels: theme/ui

#9209 UI: Fix Firefox positioning of chart resource label
  ui/app/components/das/recommendation-chart.hbs
  ui/app/styles/charts/recommendation-chart.scss
Labels: theme/ui, type/bug

#9223 UI: Add namespace and task states query params to the topology route
  ui/app/routes/topology.js
  ui/tests/acceptance/topology-test.js
Labels: theme/ui

#9234 UI: Add handling for empty state flaky test edge case
  ui/tests/acceptance/topology-test.js
  ui/tests/pages/components/topo-viz/node.js
Labels: theme/flaky-tests, theme/ui
