Repository hashicorp/nomad, pull requests merged in 2020-02, with the labels that each got.

#7047 UI: Node drain status light icons
  ui/app/components/client-node-row.js
  ui/app/models/node.js
  ui/app/styles/components/node-status-light.scss
  ui/app/templates/clients/client.hbs
  ui/public/images/icons/node-init-circle-fill.svg
Labels: ui

#7048 csi: implement VolumeClaimRPC
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/structs/csi.go
Labels: storage

#7070 e2e: rename linux runner to avoid implicit build tag
  e2e/framework/provisioning/linux_runner.go
  e2e/framework/provisioning/ssh_runner.go
Labels: testing

#7076 csi: implement releasing volume claims for terminal allocs
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
Labels: storage

#7098 UI: Explicit transparent bg on popover actions
  ui/app/styles/components/popover-menu.scss
Labels: bug, ui

#7099 UI: Override the max-width on mobile to avoid losing space due to non-existent gutter menu
  ui/app/styles/components/page-layout.scss
Labels: bug, ui

#7107 csi: implement CSI controller detach request/response
  client/structs/csi.go
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
Labels: storage

#7113 csi: add PublishContext to CSIVolumeClaimResponse
  nomad/structs/csi.go
Labels: storage

#7117 csi: stub methods for server-to-controller RPC calls
  nomad/csi_endpoint.go
Labels: storage

#7150 Update Raft dependency
  command/agent/testagent.go
  nomad/leader.go
  nomad/server.go
  nomad/testing.go
  nomad/util.go
  nomad/util_test.go
  vendor/github.com/hashicorp/raft/CHANGELOG.md
  vendor/github.com/hashicorp/raft/Makefile
  vendor/github.com/hashicorp/raft/README.md
  vendor/github.com/hashicorp/raft/api.go
  vendor/github.com/hashicorp/raft/commands.go
  vendor/github.com/hashicorp/raft/config.go
  vendor/github.com/hashicorp/raft/configuration.go
  vendor/github.com/hashicorp/raft/discard_snapshot.go
  vendor/github.com/hashicorp/raft/file_snapshot.go
  vendor/github.com/hashicorp/raft/fsm.go
  vendor/github.com/hashicorp/raft/future.go
  vendor/github.com/hashicorp/raft/go.mod
  vendor/github.com/hashicorp/raft/go.sum
  vendor/github.com/hashicorp/raft/inmem_snapshot.go
  vendor/github.com/hashicorp/raft/inmem_transport.go
  vendor/github.com/hashicorp/raft/leadership_delegate.go
  vendor/github.com/hashicorp/raft/log.go
  vendor/github.com/hashicorp/raft/net_transport.go
  vendor/github.com/hashicorp/raft/observer.go
  vendor/github.com/hashicorp/raft/raft.go
  vendor/github.com/hashicorp/raft/replication.go
  vendor/github.com/hashicorp/raft/snapshot.go
  vendor/github.com/hashicorp/raft/tcp_transport.go
  vendor/github.com/hashicorp/raft/testing.go
  vendor/github.com/hashicorp/raft/testing_batch.go
  vendor/github.com/hashicorp/raft/transport.go
  vendor/github.com/hashicorp/raft/util.go
  vendor/vendor.json
Labels: raft

#7151 UI: Host Volumes
  ui/app/controllers/clients/client.js
  ui/app/models/host-volume.js
  ui/app/models/node.js
  ui/app/models/task-group.js
  ui/app/models/task.js
  ui/app/models/volume-mount.js
  ui/app/models/volume.js
  ui/app/serializers/node.js
  ui/app/serializers/task-group.js
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/clients/client.hbs
  ui/app/templates/clients/index.hbs
  ui/app/templates/components/allocation-row.hbs
  ui/app/templates/components/client-node-row.hbs
  ui/app/templates/components/job-deployment/deployment-allocations.hbs
  ui/app/templates/components/job-editor.hbs
  ui/app/templates/components/job-page/parts/recent-allocations.hbs
  ui/app/templates/components/job-page/parts/task-groups.hbs
  ui/app/templates/components/task-group-row.hbs
  ui/app/templates/components/task-row.hbs
  ui/app/templates/jobs/job/allocations.hbs
  ui/app/templates/jobs/job/task-group.hbs
  ui/mirage/factories/job.js
  ui/mirage/factories/node.js
  ui/mirage/factories/task-group.js
  ui/mirage/factories/task.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/integration/job-page/parts/task-groups-test.js
  ui/tests/pages/allocations/detail.js
  ui/tests/pages/allocations/task/detail.js
  ui/tests/pages/clients/detail.js
  ui/tests/pages/components/allocations.js
  ui/tests/pages/jobs/job/task-group.js
  ui/tests/unit/serializers/node-test.js
Labels: ui

#7166 csi: Pass through usage options to the csimanager
  client/allocrunner/csi_hook.go
  client/pluginmanager/csimanager/interface.go
  client/pluginmanager/csimanager/volume.go
  client/pluginmanager/csimanager/volume_test.go
Labels: storage

#7169 csi: Basic volume usage tracking
  client/pluginmanager/csimanager/usage_tracker.go
  client/pluginmanager/csimanager/usage_tracker_test.go
  client/pluginmanager/csimanager/volume.go
Labels: storage

#7168 sched/feasible: Return more detailed CSI Failure messages
  scheduler/feasible.go
Labels: storage

#7167 csi: Claim volumes and perform remote attachement
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/csi_hook.go
  client/pluginmanager/csimanager/interface.go
  client/pluginmanager/csimanager/volume.go
  client/pluginmanager/csimanager/volume_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/fsm.go
  nomad/node_endpoint.go
  nomad/structs/csi.go
Labels: storage

#7125 csi: volume claim garbage collection
  jobspec/test-fixtures/service-enable-tag-override.hcl
  jobspec/test-fixtures/tg-service-enable-tag-override.hcl
  nomad/config.go
  nomad/core_sched.go
  nomad/core_sched_test.go
  nomad/csi_endpoint.go
  nomad/leader.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
  nomad/state/state_store.go
  nomad/structs/csi.go
  nomad/structs/structs.go
Labels: storage

#7178 csi: Validate Volumes during registration
  api/csi_test.go
  client/client_csi_endpoint.go
  client/client_csi_endpoint_test.go
  client/pluginmanager/csimanager/volume.go
  client/structs/csi.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  plugins/csi/client.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
Labels: storage

#7190 [docs] Add note Nomad Connect requires namespaces...
  website/pages/guides/integrations/consul-connect.mdx
Labels: docs

#7083 Document service lifecycle
  website/pages/docs/job-specification/service.mdx
Labels: consul, docs

#7216 csi: Fix Controller RPCs
  client/csi_controller_endpoint.go
  client/csi_controller_endpoint_test.go
  client/rpc.go
  client/structs/csi.go
  nomad/client_csi_endpoint.go
  nomad/client_csi_endpoint_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/server.go
Labels: storage

#7215 csi: Add /dev mounts to CSI Plugins
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
Labels: storage
