Repository hashicorp/nomad, pull requests merged in 2020-06, with the labels that each got.

#8086 docs: add go-getter redirect fix to changelog
  CHANGELOG.md
Labels: needs-backporting

#8087 driver/docker: enable setting hard/soft memory limits
  CHANGELOG.md
  drivers/docker/config.go
  drivers/docker/config_test.go
  drivers/docker/driver.go
  drivers/docker/driver_test.go
  website/pages/docs/drivers/docker.mdx
Labels: needs-backporting

#8103 Remove vendored xterm.js files
  ui/vendor/xterm.js
  ui/vendor/xterm.js.map
Labels: ui

#8162 cli: fix malformed alloc status address list when more than 1 addr
  command/alloc_status.go
Labels: bug, cli

#8171 changelog: add entry for GH-8161
  CHANGELOG.md
Labels: docs, enhancement

#8168 add `PreserveCounts` to `Job.Register`
  CHANGELOG.md
  api/jobs.go
  api/jobs_test.go
  command/agent/job_endpoint.go
  command/job_inspect.go
  command/job_run.go
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  nomad/structs/structs.go
  vendor/github.com/hashicorp/nomad/api/api.go
  vendor/github.com/hashicorp/nomad/api/jobs.go
  vendor/github.com/hashicorp/nomad/api/scaling.go
  website/pages/docs/commands/job/run.mdx
Labels: autoscaling

#8187 modify Job.Scale RPC to return an error if there is an active deployment
  CHANGELOG.md
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  website/pages/api-docs/jobs.mdx
Labels: autoscaling

#8177 UI: Client and Server Monitor
  ui/app/abilities/agent.js
  ui/app/components/agent-monitor.js
  ui/app/components/client-subnav.js
  ui/app/components/forbidden-message.js
  ui/app/components/server-subnav.js
  ui/app/components/streaming-file.js
  ui/app/controllers/clients/client/index.js
  ui/app/controllers/clients/client/monitor.js
  ui/app/controllers/servers.js
  ui/app/controllers/servers/index.js
  ui/app/controllers/servers/server/index.js
  ui/app/controllers/servers/server/monitor.js
  ui/app/router.js
  ui/app/routes/clients/client.js
  ui/app/routes/clients/client/index.js
  ui/app/routes/servers/server.js
  ui/app/styles/components/boxed-section.scss
  ui/app/styles/components/dropdown.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/clients/client.hbs
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/clients/client/monitor.hbs
  ui/app/templates/components/agent-monitor.hbs
  ui/app/templates/components/client-subnav.hbs
  ui/app/templates/components/forbidden-message.hbs
  ui/app/templates/components/server-subnav.hbs
  ui/app/templates/servers.hbs
  ui/app/templates/servers/index.hbs
  ui/app/templates/servers/server.hbs
  ui/app/templates/servers/server/index.hbs
  ui/app/templates/servers/server/monitor.hbs
  ui/mirage/config.js
  ui/tests/acceptance/client-monitor-test.js
  ui/tests/acceptance/server-detail-test.js
  ui/tests/acceptance/server-monitor-test.js
  ui/tests/integration/agent-monitor-test.js
  ui/tests/integration/streaming-file-test.js
  ui/tests/pages/clients/monitor.js
  ui/tests/pages/servers/detail.js
  ui/tests/pages/servers/monitor.js
  ui/tests/utils/ember-power-select-extensions.js
Labels: ui

#8180 demo: Fix Vagrantfile when building staging VM for Cloud build.
  terraform/Vagrantfile
Labels: bug, demos/examples

#8207 UI: Task Group Scaling Controls
  ui/app/abilities/abstract.js
  ui/app/abilities/job.js
  ui/app/adapters/job.js
  ui/app/components/search-box.js
  ui/app/components/stepper-input.js
  ui/app/components/task-group-row.js
  ui/app/controllers/jobs/job/task-group.js
  ui/app/helpers/lazy-click.js
  ui/app/models/group-scaling.js
  ui/app/models/job.js
  ui/app/models/task-group.js
  ui/app/routes/jobs/job/task-group.js
  ui/app/styles/components.scss
  ui/app/styles/components/dropdown.scss
  ui/app/styles/components/inline-definitions.scss
  ui/app/styles/components/stepper-input.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/icon.scss
  ui/app/templates/components/stepper-input.hbs
  ui/app/templates/components/task-group-row.hbs
  ui/app/templates/jobs/job/task-group.hbs
  ui/app/utils/properties/watch.js
  ui/mirage/config.js
  ui/mirage/factories/task-group.js
  ui/stories/components/stepper-input.stories.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/integration/stepper-input-test.js
  ui/tests/integration/task-group-row-test.js
  ui/tests/pages/components/stepper-input.js
  ui/tests/pages/jobs/job/task-group.js
  ui/tests/unit/abilities/job-test.js
Labels: ui

#8175 UI: Add phase 1 search
  ui/app/components/global-search/control.js
  ui/app/services/data-caches.js
  ui/app/styles/components.scss
  ui/app/styles/components/global-search-control.scss
  ui/app/styles/components/global-search-dropdown.scss
  ui/app/styles/core/navbar.scss
  ui/app/templates/components/global-header.hbs
  ui/app/templates/components/global-search/control.hbs
  ui/app/templates/components/global-search/message.hbs
  ui/app/templates/components/global-search/trigger.hbs
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/acceptance/search-test.js
  ui/tests/pages/jobs/list.js
  ui/tests/pages/layout.js
Labels: enhancement, ui

#8216 UI: Add a key to the alloc table on the task group detail page
  ui/app/templates/jobs/job/task-group.hbs
Labels: ui

#8218 UI: Add cycling to factory healthy flags
  ui/mirage/factories/storage-controller.js
  ui/mirage/factories/storage-node.js
Labels: bug, ui

#8221 UI: Fix flaky task-group-row test.
  ui/tests/integration/task-group-row-test.js
Labels: ui

#8238 Update banner contents
  website/data/alert-banner.js
Labels: docs, website

#8182 UI: Add linting for classic decorator
  ui/.eslintrc.js
  ui/app/abilities/client.js
  ui/app/adapters/watchable-namespace-ids.js
  ui/app/models/node.js
  ui/app/routes/csi/volumes/volume.js
  ui/app/routes/jobs/job.js
  ui/app/serializers/allocation.js
  ui/app/serializers/evaluation.js
Labels: bug, ui

#8242 UI: Remove non-classic use of this.set
  ui/app/components/global-search/control.js
Labels: bug, ui

#8255 cli: fix license get command help Synopsis text.
  command/license_get.go
Labels: bug, cli

#8260 docs: fix license command index page formatting.
  website/pages/docs/commands/license/index.mdx
Labels: docs, website

#8265 multiregion validation fixes
  command/agent/job_endpoint.go
  nomad/structs/structs.go
Labels: deployments

#8266 multiregion: add support for 'job plan'
  command/job_plan.go
  nomad/job_endpoint.go
  nomad/job_endpoint_oss.go
Labels: deployments

#8249 UI: Improve global search UX
  ui/app/components/global-search/control.js
  ui/app/components/global-search/match.js
  ui/app/mixins/searchable.js
  ui/app/styles/components.scss
  ui/app/styles/components/global-search-container.scss
  ui/app/styles/components/global-search-control.scss
  ui/app/styles/components/global-search-dropdown.scss
  ui/app/templates/components/global-search/control.hbs
  ui/app/templates/components/global-search/match.hbs
  ui/app/templates/components/global-search/trigger.hbs
  ui/package.json
  ui/tests/acceptance/search-test.js
  ui/tests/pages/layout.js
  ui/tests/unit/mixins/searchable-test.js
  ui/yarn.lock
Labels: bug, ui

#8279 UI: Fix monitor in Safari
  ui/app/utils/classes/stream-logger.js
Labels: ui

#8280 UI: Make monitor log output full-width
  ui/app/styles/core/section.scss
  ui/app/templates/allocations/allocation/task/logs.hbs
  ui/app/templates/clients/client/monitor.hbs
  ui/app/templates/components/fs/browser.hbs
  ui/app/templates/servers/server/monitor.hbs
Labels: ui

#8281 UI: Revert AbortController polyfill to use native AbortController on logs page
  ui/app/components/task-log.js
Labels: ui

#8283 UI: Fix text alignment for the "view raw file" button/link on the fs file viewer
  ui/app/styles/core/buttons.scss
Labels: ui

#8286 docs: spellcheck fix for multiregion
  website/pages/docs/job-specification/multiregion.mdx
Labels: docs

#8287 UI: Add multiple substring highlights for search
  ui/app/components/global-search/match.js
  ui/app/templates/components/global-search/match.hbs
  ui/tests/acceptance/search-test.js
  ui/tests/pages/layout.js
Labels: enhancement, ui

#7752 docs: update Datadog agent telemetry link to rewritten version.
  website/pages/docs/configuration/telemetry.mdx
Labels: docs, enhancement

#8271 Comment out default Consul check; Update URLs
  command/agent/bindata_assetfs.go
  command/assets/example.nomad
Labels: enhancement

#7381 Update deployment guide docs title
  website/pages/docs/install/production/deployment-guide.mdx
Labels: website

#8305 added redirect for /docs/index.html
  website/_redirects
Labels: website

#8320 UI: Fix layering so logo is clickable
  ui/app/styles/core/navbar.scss
Labels: bug, ui

#8317 UI: Change back to released Ember Power Select
  ui/app/components/global-search/control.js
  ui/package.json
  ui/yarn.lock
Labels: bug, ui
