Repository hashicorp/nomad, pull requests merged in 2020-09, with the labels that each got.

#8742 UI: Add poststart and poststop lifecycle phases
  ui/app/components/lifecycle-chart-row.js
  ui/app/components/lifecycle-chart.js
  ui/app/controllers/allocations/allocation/task/index.js
  ui/app/models/task.js
  ui/app/styles/components/lifecycle-chart.scss
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/components/lifecycle-chart-row.hbs
  ui/app/templates/components/lifecycle-chart.hbs
  ui/mirage/factories/task.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/integration/components/lifecycle-chart-test.js
  ui/tests/pages/components/lifecycle-chart.js
Labels: theme/ui, type/enhancement

#8805 UI: Temporarily remove poststop from the lifecycle chart
  ui/app/components/lifecycle-chart.js
  ui/app/styles/components/lifecycle-chart.scss
  ui/app/templates/components/lifecycle-chart.hbs
  ui/mirage/factories/task.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/integration/components/lifecycle-chart-test.js
  ui/tests/pages/components/lifecycle-chart.js
Labels: theme/ui

#8813 docs: fix incorrect aws-asg autoscaler target plugin policy params
  website/pages/docs/autoscaling/plugins/target.mdx
Labels: theme/docs, type/bug

#8828 e2e: move configurations into profile-specific directories
  e2e/terraform/config/.gitignore
  e2e/terraform/config/custom/consul/client-linux/indexed/.gitkeep
  e2e/terraform/config/custom/consul/client-windows/indexed/.gitkeep
  e2e/terraform/config/custom/consul/server/indexed/.gitkeep
  e2e/terraform/config/custom/nomad/client-linux/indexed/.gitkeep
  e2e/terraform/config/custom/nomad/client-windows/indexed/.gitkeep
  e2e/terraform/config/custom/nomad/server/indexed/.gitkeep
  e2e/terraform/config/dev-cluster/consul/aws.json
  e2e/terraform/config/dev-cluster/consul/base.json
  e2e/terraform/config/dev-cluster/consul/server/server.json
  e2e/terraform/config/dev-cluster/nomad/base.hcl
  e2e/terraform/config/dev-cluster/nomad/client-linux/client.hcl
  e2e/terraform/config/dev-cluster/nomad/server/server.hcl
  e2e/terraform/config/dev-cluster/vault/server/vault.hcl
  e2e/terraform/config/full-cluster/consul/aws.json
  e2e/terraform/config/full-cluster/consul/base.json
  e2e/terraform/config/full-cluster/consul/server/server.json
  e2e/terraform/config/full-cluster/nomad/base.hcl
  e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-0.hcl
  e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-1.hcl
  e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-2.hcl
  e2e/terraform/config/full-cluster/nomad/client-linux/indexed/client-3.hcl
  e2e/terraform/config/full-cluster/nomad/client-windows/client-windows.hcl
  e2e/terraform/config/full-cluster/nomad/server/server.hcl
  e2e/terraform/config/full-cluster/vault/server/vault.hcl
  e2e/terraform/provisioning.tf
  e2e/terraform/shared/config/provision-client.sh
  e2e/terraform/shared/config/provision-server.sh
  e2e/terraform/shared/config/provision-windows-client.ps1
  e2e/terraform/shared/consul/azure.json
  e2e/terraform/shared/consul/consul.json
  e2e/terraform/shared/nomad/indexed/server-1.hcl
  e2e/terraform/shared/nomad/indexed/server-2.hcl
Labels: theme/testing

#8733 docs: add Autoscaler telemetry documentation to website.
  website/data/docs-navigation.js
  website/pages/docs/autoscaling/agent.mdx
  website/pages/docs/autoscaling/api.mdx
  website/pages/docs/autoscaling/cli.mdx
  website/pages/docs/autoscaling/telemetry.mdx
Labels: theme/docs, type/enhancement

#8837 docs: update Autoscaler AWS target with new purge config option.
  website/pages/docs/autoscaling/plugins/target.mdx
Labels: theme/docs, type/enhancement

#8755 docs: add Nomad Autoscaler Datadog APM plugin details.
  website/pages/docs/autoscaling/plugins/apm.mdx
Labels: theme/docs, type/enhancement

#8818 Fix several search-related issues
  website/components/search-bar/index.jsx
  website/components/search-bar/style.css
  website/package-lock.json
  website/package.json
  website/scripts/index_search_content.js
Labels: theme/docs

#8833 UI: Fix bug where task logs would suddenly switch to another task's logs
  ui/app/serializers/allocation.js
  ui/app/serializers/application.js
  ui/app/serializers/job-summary.js
  ui/app/serializers/plugin.js
  ui/tests/unit/serializers/allocation-test.js
  ui/tests/unit/serializers/application-test.js
Labels: theme/ui

#8851 e2e: fix failure in running metrics test suite jobs.
  e2e/metrics/prometheus.go
Labels: theme/testing, type/bug

#8855 docs: format Autopilot config stanza example.
  website/pages/docs/configuration/autopilot.mdx
Labels: theme/docs

#8869 Sunset older instances of EA Guides
  website/_redirects
  website/data/docs-navigation.js
  website/pages/docs/install/production/deployment-guide.mdx
  website/pages/docs/install/production/index.mdx
  website/pages/docs/install/production/reference-architecture.mdx
Labels: theme/docs

#8856 UI: Add handling for allocation-less exec URL
  ui/app/utils/generate-exec-url.js
  ui/tests/unit/utils/generate-exec-url-test.js
Labels: theme/ui, type/bug

#8887 Add AWS `mac` address and `public-ipv6`
  client/fingerprint/env_aws.go
  client/fingerprint/env_aws_test.go
Labels: theme/environment-aws, theme/fingerprint

#8912 e2e: documentation and minor tweaks to configs
  e2e/terraform/README.md
  e2e/terraform/config/dev-cluster/consul/server/server.json
  e2e/terraform/packer/linux/provision.sh
  e2e/terraform/userdata/ubuntu-bionic.sh
  e2e/terraform/userdata/windows-2016.ps1
Labels: theme/testing

#8811 docs: fix type for `local_service_port`
  website/pages/docs/job-specification/proxy.mdx
Labels: theme/docs

#8915 UI: Change compared page object to match by name
  ui/tests/acceptance/job-deployments-test.js
Labels: theme/ui, type/bug

#8928 e2e: make sure dev-cluster has the option to run windows config
  e2e/terraform/config/dev-cluster/nomad/client-windows/client-windows.hcl
Labels: theme/testing

#8931 UI: Launched jobs quality of life improvements
  ui/app/components/job-page/parts/children.js
  ui/app/components/job-row.js
  ui/app/models/job.js
  ui/app/routes/jobs/job/index.js
  ui/app/serializers/job.js
  ui/app/templates/components/job-page/parts/children.hbs
  ui/app/templates/components/job-row.hbs
  ui/mirage/factories/job.js
  ui/tests/acceptance/job-detail-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/integration/components/job-page/parts/children-test.js
  ui/tests/integration/components/job-page/periodic-test.js
  ui/tests/pages/jobs/detail.js
Labels: theme/ui

#8956 ci: don't run UI tests for e2e branches
  .circleci/config.yml
  .circleci/config/workflows/build-test.yml
Labels: theme/testing

#8598 [docs] Update redirects and links for learn.hashicorp.com
  website/_redirects
  website/pages/api-docs/acl-policies.mdx
  website/pages/api-docs/acl-tokens.mdx
  website/pages/api-docs/index.mdx
  website/pages/api-docs/nodes.mdx
  website/pages/api-docs/operator.mdx
  website/pages/api-docs/sentinel-policies.mdx
  website/pages/docs/autoscaling/agent.mdx
  website/pages/docs/autoscaling/plugins/target.mdx
  website/pages/docs/commands/acl/index.mdx
  website/pages/docs/commands/agent.mdx
  website/pages/docs/commands/deployment/unblock.mdx
  website/pages/docs/commands/node/drain.mdx
  website/pages/docs/commands/operator/autopilot-get-config.mdx
  website/pages/docs/commands/operator/autopilot-set-config.mdx
  website/pages/docs/commands/operator/index.mdx
  website/pages/docs/commands/operator/raft-list-peers.mdx
  website/pages/docs/commands/operator/raft-remove-peer.mdx
  website/pages/docs/commands/operator/snapshot-inspect.mdx
  website/pages/docs/commands/operator/snapshot-restore.mdx
  website/pages/docs/commands/operator/snapshot-save.mdx
  website/pages/docs/configuration/acl.mdx
  website/pages/docs/configuration/autopilot.mdx
  website/pages/docs/configuration/consul.mdx
  website/pages/docs/configuration/server.mdx
  website/pages/docs/configuration/server_join.mdx
  website/pages/docs/configuration/tls.mdx
  website/pages/docs/configuration/vault.mdx
  website/pages/docs/drivers/external/lxc.mdx
  website/pages/docs/drivers/index.mdx
  website/pages/docs/enterprise.mdx
  website/pages/docs/faq.mdx
  website/pages/docs/install/index.mdx
  website/pages/docs/install/quickstart.mdx
  website/pages/docs/integrations/consul-connect.mdx
  website/pages/docs/integrations/consul-integration.mdx
  website/pages/docs/internals/security.mdx
  website/pages/docs/job-specification/connect.mdx
  website/pages/docs/job-specification/csi_plugin.mdx
  website/pages/docs/job-specification/expose.mdx
  website/pages/docs/job-specification/gateway.mdx
  website/pages/docs/job-specification/job.mdx
  website/pages/docs/job-specification/lifecycle.mdx
  website/pages/docs/job-specification/migrate.mdx
  website/pages/docs/job-specification/multiregion.mdx
  website/pages/docs/job-specification/proxy.mdx
  website/pages/docs/job-specification/scaling.mdx
  website/pages/docs/job-specification/service.mdx
  website/pages/docs/job-specification/update.mdx
  website/pages/docs/job-specification/volume.mdx
  website/pages/docs/upgrade/index.mdx
  website/pages/docs/upgrade/upgrade-specific.mdx
  website/pages/home/index.jsx
  website/pages/intro/getting-started/index.mdx
  website/pages/intro/getting-started/next-steps.mdx
  website/pages/use-cases/automated-service-networking-with-consul.jsx
  website/pages/use-cases/non-containerized-application-orchestration.jsx
  website/pages/use-cases/simple-container-orchestration.jsx
Labels: theme/docs, theme/website

#8983 docs: quota apply does not have a 'name' param
  website/pages/docs/commands/quota/apply.mdx
Labels: theme/docs

#8985 Add scaling policy type
  api/scaling.go
  api/scaling_test.go
  nomad/fsm.go
  nomad/job_endpoint_test.go
  nomad/mock/mock.go
  nomad/state/schema.go
  nomad/state/schema_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/funcs.go
  nomad/structs/structs.go
  nomad/structs/structs_oss.go
  nomad/structs/structs_test.go
  vendor/github.com/hashicorp/nomad/api/scaling.go
Labels: theme/autoscaling, type/enhancement

#8989 e2e: cleanup errors should use assert, not require
  e2e/nodedrain/nodedrain.go
  e2e/rescheduling/rescheduling.go
  e2e/volumes/volumes.go
Labels: theme/testing
