Repository hashicorp/nomad, pull requests merged in 2020-05, with the labels that each got.

#7810 spread scheduling algorithm
  CHANGELOG.md
  api/operator.go
  command/agent/agent_test.go
  command/agent/command.go
  command/agent/config_parse_test.go
  command/agent/operator_endpoint.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/structs/funcs.go
  nomad/structs/funcs_test.go
  nomad/structs/operator.go
  scheduler/preemption_test.go
  scheduler/rank.go
  scheduler/rank_test.go
  scheduler/stack.go
  scheduler/stack_oss.go
Labels: scheduling

#7823 e2e: csi test can purge target job
  e2e/csi/csi.go
Labels: storage, testing

#7858 volumewatcher: remove spurious nil-check
  nomad/volumewatcher/volume_watcher.go
Labels: storage

#7862 docstring improvements and typo fixes
  nomad/structs/csi.go
  nomad/structs/node.go
Labels: storage

#7869 csi: fix mount validation
  plugins/csi/client.go
  plugins/csi/client_test.go
Labels: storage

#7844 csi: fix plugin counts on node update
  nomad/csi_endpoint_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/csi.go
Labels: storage

#7871 reorder volume claim batch request raft message
  nomad/structs/structs.go
Labels: storage

#7855 UI: Make allocation reference own task group instead of job's task group when job versions don't match
  ui/app/components/allocation-row.js
  ui/app/models/allocation.js
  ui/app/serializers/allocation.js
  ui/mirage/factories/allocation.js
  ui/mirage/factories/job.js
  ui/tests/unit/models/allocation-test.js
  ui/tests/unit/serializers/allocation-test.js
  ui/tests/unit/serializers/volume-test.js
Labels: ui

#7839 UI: Remove Ember Freestyle
  ui/.template-lintrc.js
  ui/app/controllers/freestyle.js
  ui/app/routes/freestyle.js
  ui/app/services/ember-freestyle.js
  ui/app/styles/storybook.scss
  ui/ember-cli-build.js
  ui/package.json
  ui/stories/theme/colors.stories.js
  ui/stories/theme/font-stacks.stories.js
  ui/yarn.lock
Labels: enhancement, ui

#7843 UI: Migrate page objects away from jQuery
  ui/config/deprecation-workflow.js
  ui/package.json
  ui/tests/integration/job-editor-test.js
  ui/tests/integration/job-page/service-test.js
  ui/tests/integration/task-file-test.js
  ui/tests/pages/jobs/list.js
  ui/tests/test-helper.js
  ui/yarn.lock
Labels: ui

#7878 periodic GC for CSI plugins
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/core_sched.go
  nomad/core_sched_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/fsm.go
  nomad/leader.go
  nomad/state/state_store.go
  nomad/structs/csi.go
  nomad/structs/structs.go
  website/pages/docs/configuration/server.mdx
Labels: storage

#7886 Add ControllersExpected to the PluginListStub
  api/csi.go
Labels: storage

#7889 CSI volumewatcher testability improvments
  nomad/volumewatcher/volume_watcher.go
Labels: storage

#7900 volume_mount doc tweak
  website/pages/docs/job-specification/volume_mount.mdx
Labels: storage

#7907 volumewatcher: set maximum batch size for raft update
  nomad/volumewatcher/batcher.go
  nomad/volumewatcher/batcher_test.go
Labels: storage

#7895 UI: CSI Searchable volumes and plugins lists
  ui/app/controllers/csi/plugins/index.js
  ui/app/controllers/csi/volumes/index.js
  ui/app/templates/csi/plugins/index.hbs
  ui/app/templates/csi/volumes/index.hbs
  ui/mirage/factories/csi-plugin.js
  ui/mirage/factories/storage-controller.js
  ui/mirage/factories/storage-node.js
  ui/tests/acceptance/plugins-list-test.js
  ui/tests/acceptance/volumes-list-test.js
  ui/tests/pages/storage/plugins/list.js
  ui/tests/pages/storage/volumes/list.js
Labels: storage, ui

#7903 api: validate scale count value is not negative.
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
Labels: api, autoscaling, bug

#7916 changelog: add entry for GH-7902
  CHANGELOG.md
Labels: docs, enhancement

#7881 Periodic GC for volume claims
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/core_sched.go
  nomad/core_sched_test.go
  nomad/leader.go
  website/pages/docs/configuration/server.mdx
Labels: storage

#7909 volumewatcher: stop watcher goroutines when there's no work
  nomad/volumewatcher/volume_watcher.go
  nomad/volumewatcher/volumes_watcher_test.go
Labels: storage

#7896 UI: CSI namespace bugs
  ui/app/components/gutter-menu.js
  ui/app/templates/components/gutter-menu.hbs
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/acceptance/namespaces-test.js
  ui/tests/acceptance/volumes-list-test.js
  ui/tests/pages/layout.js
Labels: ui

#7918 csi: log fallthrough on invalid node IDs for client RPC
  nomad/client_csi_endpoint.go
Labels: storage

#7836 UI: add assertions for title-area buttons
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/pages/allocations/detail.js
  ui/tests/pages/jobs/detail.js
Labels: bug, ui

#7925 Add changelog entry for exec UI ACL-checking
  CHANGELOG.md
Labels: docs

#7923 csi: support Secrets parameter in CSI RPCs
  api/csi.go
  client/csi_endpoint.go
  client/pluginmanager/csimanager/volume.go
  client/structs/csi.go
  command/agent/csi_endpoint.go
  command/node_status.go
  command/volume_register_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/mock/mock.go
  nomad/structs/csi.go
  nomad/volumewatcher/volume_watcher.go
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
  website/pages/docs/commands/volume/register.mdx
Labels: storage

#7930 fix typo in changelog
  CHANGELOG.md
Labels: docs

#7937 Fix formatting error on preemption docs page
  website/pages/docs/internals/scheduling/preemption.mdx
Labels: website

#7911 UI: CSI Availability Gauges
  ui/app/components/gauge-chart.js
  ui/app/helpers/format-percentage.js
  ui/app/styles/charts.scss
  ui/app/styles/charts/gauge-chart.scss
  ui/app/styles/components/metrics.scss
  ui/app/styles/core/columns.scss
  ui/app/styles/storybook.scss
  ui/app/styles/utils/structure-colors.scss
  ui/app/templates/components/gauge-chart.hbs
  ui/app/templates/csi/plugins/plugin.hbs
  ui/stories/charts/gauge-chart.stories.js
  ui/tests/integration/gauge-chart-test.js
  ui/tests/pages/components/gauge-chart.js
  ui/tests/unit/components/gauge-chart-test.js
Labels: ui

#7942 UI: CSI Bug, Imperatively load controller/node plugin allocations
  ui/app/components/allocation-row.js
  ui/app/components/plugin-allocation-row.js
  ui/app/models/allocation.js
  ui/app/models/storage-controller.js
  ui/app/models/storage-node.js
  ui/app/templates/csi/plugins/plugin.hbs
  ui/tests/integration/plugin-allocation-row-test.js
Labels: ui

#7938 docs for `stop_on_client_disconnect` stanza
  website/pages/docs/job-specification/group.mdx
Labels: docs, storage

#7915 the api.ScalingEvent struct was missing the .Count field
  CHANGELOG.md
  api/scaling.go
Labels: api, bug

#7956 e2e: upgrade CNI to 0.8.6
  e2e/terraform/shared/config/provision-client.sh
  e2e/terraform/shared/config/provision-windows-client.ps1
  scripts/vagrant-linux-priv-cni.sh
Labels: cni, testing

#7958 csi: refactor internal client field name to ExternalID
  client/pluginmanager/csimanager/volume.go
  client/structs/csi.go
  plugins/csi/client_test.go
  plugins/csi/plugin.go
Labels: storage

#7864 UI: add asset size GitHub Action
  .github/workflows/ember-assets.yml
Labels: ci, cleanup, ui

#7963 UI: Change exec URL-generation to use Ember get
  ui/app/utils/generate-exec-url.js
Labels: bug, ui

#7957 csi: support for VolumeContext and VolumeParameters
  api/csi.go
  client/csi_endpoint.go
  client/structs/csi.go
  nomad/csi_endpoint.go
  nomad/mock/mock.go
  nomad/structs/csi.go
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
  website/pages/docs/commands/volume/register.mdx
Labels: storage

#7965 csi: use a blocking initial connection with timeout
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
  plugins/csi/client.go
Labels: storage

#7518 CNI Implementation
  client/allocrunner/network_manager_linux.go
  client/allocrunner/networking_bridge_linux.go
  client/allocrunner/networking_cni.go
  client/client.go
  client/client_test.go
  client/config/config.go
  client/fingerprint/bridge.go
  client/fingerprint/bridge_default.go
  client/fingerprint/bridge_linux.go
  client/fingerprint/bridge_linux_test.go
  client/fingerprint/cni.go
  client/fingerprint/cni_test.go
  client/fingerprint/env_aws.go
  client/fingerprint/fingerprint.go
  client/fingerprint/fingerprint_linux.go
  client/fingerprint/network.go
  client/fingerprint/test_fixtures/cni/net1.conf
  client/fingerprint/test_fixtures/cni/net2.conflist
  client/fingerprint_manager.go
  nomad/mock/mock.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  scheduler/feasible.go
  scheduler/feasible_test.go
  scheduler/stack.go
  scheduler/stack_oss.go
Labels: enhancement, networking

#7971 UI: Make the Plugin adapter extend Watchable
  ui/app/adapters/plugin.js
  ui/app/utils/properties/watch.js
Labels: ui

#7980 UI: Remove Ember server from Storybook startup
  .gitignore
  ui/.storybook/preview-head.html
  ui/README.md
  ui/package.json
Labels: cleanup, ui

#7984 csi: improve plugin error messages and volume validation
  plugins/csi/client.go
  plugins/csi/client_test.go
Labels: storage

#7995 api: tidy Go module to remove unused modules.
  api/go.sum
Labels: dependencies, enhancement

#8006 UI: CSI node only support
  ui/app/styles/core/columns.scss
  ui/app/templates/csi/plugins/index.hbs
  ui/app/templates/csi/plugins/plugin.hbs
  ui/mirage/factories/csi-plugin.js
  ui/tests/acceptance/plugin-detail-test.js
  ui/tests/acceptance/plugins-list-test.js
  ui/tests/integration/plugin-allocation-row-test.js
  ui/tests/pages/storage/plugins/detail.js
Labels: ui

#7870 [docs] Fix version typo
  website/pages/docs/configuration/server.mdx
Labels: bug, docs

#7994 update docs to mention spread algorithm
  website/pages/api-docs/operator.mdx
  website/pages/docs/configuration/server.mdx
  website/pages/docs/faq.mdx
Labels: docs, enhancement

#8007 docs: update CSI PUT operation blocking query support yes->no.
  website/pages/api-docs/volumes.mdx
Labels: bug, docs

#8013 api: return custom error if API attempts to decode empty body.
  command/agent/http.go
  command/agent/http_test.go
Labels: api, enhancement

#8021 csi: don't pass volume claim releases thru GC eval
  nomad/csi_batch.go
  nomad/csi_batch_test.go
  nomad/job_endpoint.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
Labels: storage

#8030 volumes: return better error messages for unsupported task drivers
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/csi_hook.go
  client/allocrunner/taskrunner/volume_hook.go
  client/allocrunner/taskrunner/volume_hook_test.go
  drivers/docker/config.go
  drivers/exec/driver.go
  drivers/java/driver.go
  drivers/mock/driver.go
  drivers/qemu/driver.go
  drivers/rawexec/driver.go
  plugins/drivers/client.go
  plugins/drivers/driver.go
  plugins/drivers/proto/driver.pb.go
  plugins/drivers/proto/driver.proto
Labels: storage

#8024 UI: CSI Plugin Allocations Page
  ui/app/controllers/csi/plugins/plugin/allocations.js
  ui/app/controllers/csi/plugins/plugin/index.js
  ui/app/helpers/qp-deserialize.js
  ui/app/helpers/qp-serialize.js
  ui/app/router.js
  ui/app/routes/csi/plugins/plugin.js
  ui/app/routes/csi/plugins/plugin/allocations.js
  ui/app/routes/csi/plugins/plugin/index.js
  ui/app/templates/csi/plugins/plugin.hbs
  ui/app/templates/csi/plugins/plugin/allocations.hbs
  ui/app/templates/csi/plugins/plugin/index.hbs
  ui/tests/acceptance/plugin-allocations-test.js
  ui/tests/acceptance/plugin-detail-test.js
  ui/tests/pages/storage/plugins/detail.js
  ui/tests/pages/storage/plugins/plugin/allocations.js
Labels: ui

#7929 UI: Add test timing comparison for PRs
  .github/workflows/ember-test-audit.yml
Labels: cleanup, enhancement, ui

#8037 docs: add missing fields to driver Capabilities
  website/pages/docs/internals/plugins/task-drivers.mdx
Labels: api, docs

#8033 csi: skip unit tests on unsupported platforms
  client/pluginmanager/csimanager/volume_test.go
Labels: storage

#7964 UI: use lazy-loading for Xterm.js
  ui/.eslintrc.js
  ui/app/controllers/exec.js
  ui/app/routes/exec.js
  ui/ember-cli-build.js
  ui/package.json
  ui/tests/acceptance/exec-test.js
  ui/tests/integration/util/exec-command-editor-xterm-adapter-test.js
  ui/tests/integration/util/exec-socket-xterm-adapter-test.js
  ui/yarn.lock
Labels: cleanup, enhancement, ui

#8035 UI: Replace jQuery with fetch within Ember Data
  ui/app/adapters/application.js
  ui/app/adapters/watchable.js
  ui/app/components/job-page/parts/latest-deployment.js
  ui/app/components/job-page/parts/title.js
  ui/app/components/task-log.js
  ui/app/initializers/app-env.js
  ui/app/utils/classes/xhr-token.js
  ui/app/utils/properties/watch.js
  ui/mirage/config.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/token-test.js
  ui/tests/integration/job-page/periodic-test.js
  ui/tests/integration/job-page/service-test.js
  ui/tests/unit/adapters/job-test.js
  ui/tests/unit/adapters/volume-test.js
Labels: ui

#8048 UI: Remove minor version from audit comparison action
  .github/workflows/ember-test-audit.yml
Labels: cleanup, ui

#8055 UI: Remove jQuery from the rest of application code
  ui/app/components/distribution-bar.js
  ui/app/components/gauge-chart.js
  ui/app/components/line-chart.js
  ui/app/helpers/lazy-click.js
  ui/app/initializers/app-env.js
  ui/app/mixins/window-resizable.js
Labels: ui

#8056 UI: Remove jQuery
  ui/config/optional-features.json
  ui/package.json
  ui/yarn.lock
Labels: ui

#8074 docs: fix typo in eligibility command doc
  website/pages/docs/commands/node/eligibility.mdx
Labels: docs
