Repository hashicorp/nomad, pull requests merged in 2020-03, with the labels that each got.

#7261 Update bugsnag config
  website/lib/bugsnag.js
Labels: website

#7266 e2e: add EBS and EFS volumes for testing CSI
  e2e/terraform/compute.tf
  e2e/terraform/iam.tf
  e2e/terraform/main.tf
  e2e/terraform/network.tf
  e2e/terraform/packer/linux/setup.sh
  e2e/terraform/volumes.tf
Labels: storage, testing

#7263 Add redirects to learn for migrated guides
  website/_redirects
Labels: docs

#7273 UI: Remove build-binaries job for UI-only branches
  .circleci/config.yml
  .circleci/config/workflows/build-test.yml
Labels: testing, ui

#7274 api: alloc exec recovers from bad client connection
  api/allocations.go
Labels: api

#7256 storage: add volumes to 'nomad alloc status' CLI
  command/alloc_status.go
  command/alloc_status_test.go
Labels: storage

#7193 csi: CLI for volume status, registration/deregistration and plugin status
  api/allocations.go
  api/contexts/contexts.go
  api/csi.go
  command/agent/config_parse.go
  command/commands.go
  command/plugin.go
  command/plugin_status.go
  command/plugin_status_csi.go
  command/plugin_status_test.go
  command/status.go
  command/volume.go
  command/volume_deregister.go
  command/volume_register.go
  command/volume_register_csi.go
  command/volume_register_test.go
  command/volume_status.go
  command/volume_status_csi.go
  command/volume_status_test.go
  helper/funcs.go
  nomad/client_rpc.go
  nomad/csi_endpoint_test.go
  nomad/search_endpoint.go
  nomad/search_endpoint_test.go
  nomad/state/state_store.go
  nomad/structs/structs.go
  nomad/testing.go
Labels: storage

#7286 Deflake TestServer_ReconcileMember and some leadership related tests
  nomad/leader_test.go
  testutil/wait.go
Labels: flaky-tests

#7285 csi: add Provider field to CSI CLIs and APIs
  api/csi.go
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
  client/pluginmanager/csimanager/fingerprint.go
  command/alloc_status.go
  command/plugin_status_csi.go
  command/volume_status_csi.go
  nomad/csi_endpoint.go
  nomad/state/state_store.go
  nomad/structs/csi.go
  nomad/structs/node.go
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
Labels: storage

#7298 csi: ensure GET for plugin is idempotent
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
Labels: storage

#7303 csi: ensure volume query is idempotent
  nomad/csi_endpoint.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: storage

#7226 Fix rendered backslash in group "<required>"
  website/pages/docs/job-specification/job.mdx
Labels: docs, website

#7301 Update index.mdx
  website/pages/guides/install/production/index.mdx
Labels: docs, website

#7327 csi: docstring and log message fixups
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
  client/devicemanager/manager.go
  client/devicemanager/state/state.go
  client/pluginmanager/drivermanager/state/state.go
  client/state/state_database.go
Labels: storage

#7326 csi: use `ExternalID`, when set, to identify volumes for outside RPC calls
  client/pluginmanager/csimanager/volume.go
  nomad/csi_endpoint.go
  nomad/structs/csi.go
Labels: storage

#7330 csi: add dynamicplugins registry to client state store
  client/client.go
  client/dynamicplugins/registry.go
  client/dynamicplugins/registry_test.go
  client/pluginmanager/csimanager/manager.go
  client/pluginmanager/csimanager/manager_test.go
  client/state/db_test.go
  client/state/interface.go
  client/state/memdb.go
  client/state/noopdb.go
  client/state/state_database.go
Labels: storage

#7260 Improve docs and errors around releases on the website
  website/README.md
  website/pages/downloads/index.jsx
Labels: website

#7334 Use Head Component
  website/components/default-head-tags/index.jsx
  website/components/docs-page/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/_document.js
  website/pages/downloads/index.jsx
  website/pages/resources/index.jsx
  website/pages/security/index.jsx
Labels: website

#7356 csi: implement controller detach RPCs
  client/csi_controller_endpoint.go
  client/csi_controller_endpoint_test.go
  nomad/client_csi_endpoint.go
  nomad/client_csi_endpoint_test.go
  nomad/core_sched_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
Labels: storage

#7353 website: Fix bug with new lines in code samples
  website/package-lock.json
  website/package.json
  website/pages/use-cases/simple-container-orchestration.jsx
Labels: website

#7364 volumes: add task environment interpolation to volume_mount
  client/allocrunner/taskrunner/volume_hook.go
  client/allocrunner/taskrunner/volume_hook_test.go
Labels: storage

#7361 csi: fix filesystem write paths in e2e tests
  e2e/csi/csi.go
  e2e/csi/input/use-ebs-volume.nomad
  e2e/csi/input/use-efs-volume-read.nomad
  e2e/csi/input/use-efs-volume-write.nomad
Labels: storage

#7313 docs: explicitly detail IAM instance profile S3 artifact auth.
  website/pages/docs/job-specification/artifact.mdx
Labels: docs, enhancement

#7379 cli: fix indentation issue with -dev-connect agent help output.
  command/agent/command.go
Labels: bug, cli

#7386 csi: dynamically update plugin registration
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
  client/dynamicplugins/registry_test.go
  client/pluginmanager/csimanager/instance.go
  client/pluginmanager/csimanager/manager.go
  client/pluginmanager/csimanager/manager_test.go
Labels: storage

#7387 csi: use single-node-writer for EFS plugin e2e test
  e2e/csi/csi.go
Labels: storage

#7388 csi: stub fingerprint on instance manager shutdown
  client/pluginmanager/csimanager/instance.go
  client/pluginmanager/csimanager/instance_test.go
  plugins/csi/fake/client.go
Labels: storage

#7259 Constrain Subnav
  website/components/enterprise-info/nomad.jsx
  website/components/mega-nav/img/hashicorp-logo.svg
  website/components/mega-nav/img/temporary_suite/icon-angle.svg
  website/components/mega-nav/img/temporary_suite/logo-consul.svg
  website/components/mega-nav/img/temporary_suite/logo-hashicorp-wordmark.svg
  website/components/mega-nav/img/temporary_suite/logo-hashicorp.svg
  website/components/mega-nav/img/temporary_suite/logo-nomad.svg
  website/components/mega-nav/img/temporary_suite/logo-packer.svg
  website/components/mega-nav/img/temporary_suite/logo-terraform.svg
  website/components/mega-nav/img/temporary_suite/logo-vagrant.svg
  website/components/mega-nav/img/temporary_suite/logo-vault.svg
  website/components/mega-nav/index.jsx
  website/components/mega-nav/style.css
  website/components/mega-nav/temporary_suite.css
  website/components/mega-nav/temporary_suite.jsx
  website/components/subnav/index.jsx
  website/components/subnav/style.css
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
Labels: website

#7425 csi: fix setup error in e2e test
  e2e/csi/csi.go
Labels: storage

#7426 csi: improve error messages from scheduler
  scheduler/feasible.go
Labels: storage

#7371 Use DocsPage Component
  website/components/docs-page/img/github-icon.svg
  website/components/docs-page/index.jsx
  website/components/docs-page/style.css
  website/layouts/api.jsx
  website/layouts/docs.jsx
  website/layouts/guides.jsx
  website/layouts/intro.jsx
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: website

#7414 Detect network mode change
  scheduler/util.go
  scheduler/util_test.go
Labels: networking

#7450 csi: fix missing health count from volume list stub
  nomad/structs/csi.go
Labels: storage

#7439 Documentation for CSI command line and jobspec
  website/data/docs-navigation.js
  website/pages/docs/commands/alloc/status.mdx
  website/pages/docs/commands/node/status.mdx
  website/pages/docs/commands/plugin/index.mdx
  website/pages/docs/commands/plugin/status.mdx
  website/pages/docs/commands/volume/deregister.mdx
  website/pages/docs/commands/volume/index.mdx
  website/pages/docs/commands/volume/register.mdx
  website/pages/docs/commands/volume/status.mdx
  website/pages/docs/job-specification/csi_plugin.mdx
  website/pages/docs/job-specification/volume.mdx
Labels: docs, storage

#7462 csi: remove client from plugin on client node update
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: storage

#7435 CSI: HTTP API docs
  website/data/api-navigation.js
  website/pages/api-docs/plugins.mdx
  website/pages/api-docs/volumes.mdx
Labels: storage

#7471 csi: return an empty result list from plugins & volumes without `?type`, not an error
  command/agent/csi_endpoint.go
Labels: storage

#6697 UI: add exec terminal
  ui/.ember-cli
  ui/app/components/exec-terminal.js
  ui/app/components/exec/open-button.js
  ui/app/components/exec/task-contents.js
  ui/app/components/exec/task-group-parent.js
  ui/app/controllers/exec.js
  ui/app/router.js
  ui/app/routes/exec.js
  ui/app/routes/exec/task-group/task.js
  ui/app/services/sockets.js
  ui/app/styles/components.scss
  ui/app/styles/components/exec.scss
  ui/app/styles/core.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/core/title.scss
  ui/app/styles/utils/structure-colors.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/components/exec-terminal.hbs
  ui/app/templates/components/exec/open-button.hbs
  ui/app/templates/components/exec/task-contents.hbs
  ui/app/templates/components/exec/task-group-parent.hbs
  ui/app/templates/components/job-page/parts/title.hbs
  ui/app/templates/exec.hbs
  ui/app/templates/jobs/job/task-group.hbs
  ui/app/utils/classes/exec-command-editor-xterm-adapter.js
  ui/app/utils/classes/exec-socket-xterm-adapter.js
  ui/app/utils/escape-task-name.js
  ui/app/utils/generate-exec-url.js
  ui/app/utils/open-exec-url.js
  ui/ember-cli-build.js
  ui/mirage/factories/allocation.js
  ui/mirage/factories/job.js
  ui/package.json
  ui/public/images/icons/console.svg
  ui/server/.eslintrc.js
  ui/server/index.js
  ui/server/proxies/api.js
  ui/tests/acceptance/exec-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/integration/util/exec-command-editor-xterm-adapter-test.js
  ui/tests/integration/util/exec-socket-xterm-adapter-test.js
  ui/tests/pages/allocations/task/detail.js
  ui/tests/pages/exec.js
  ui/tests/unit/utils/escape-task-name-test.js
  ui/tests/unit/utils/generate-exec-url-test.js
  ui/vendor/xterm.js
  ui/vendor/xterm.js.map
  ui/yarn.lock
Labels: enhancement, ui

#7446 UI: Support for CSI
  ui/app/adapters/job.js
  ui/app/adapters/volume.js
  ui/app/adapters/watchable.js
  ui/app/controllers/csi.js
  ui/app/controllers/csi/volumes/index.js
  ui/app/controllers/csi/volumes/volume.js
  ui/app/mixins/with-namespace-ids.js
  ui/app/models/plugin.js
  ui/app/models/storage-controller.js
  ui/app/models/storage-node.js
  ui/app/models/task-group.js
  ui/app/models/volume-definition.js
  ui/app/models/volume-mount.js
  ui/app/models/volume.js
  ui/app/router.js
  ui/app/routes/csi/index.js
  ui/app/routes/csi/volumes.js
  ui/app/routes/csi/volumes/index.js
  ui/app/routes/csi/volumes/volume.js
  ui/app/serializers/plugin.js
  ui/app/serializers/volume.js
  ui/app/services/watch-list.js
  ui/app/styles/core/menu.scss
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/components/allocation-row.hbs
  ui/app/templates/components/gutter-menu.hbs
  ui/app/templates/components/task-row.hbs
  ui/app/templates/csi.hbs
  ui/app/templates/csi/volumes.hbs
  ui/app/templates/csi/volumes/index.hbs
  ui/app/templates/csi/volumes/volume.hbs
  ui/app/templates/jobs/job/task-group.hbs
  ui/app/utils/properties/watch.js
  ui/mirage/common.js
  ui/mirage/config.js
  ui/mirage/factories/csi-plugin.js
  ui/mirage/factories/csi-volume.js
  ui/mirage/factories/storage-controller.js
  ui/mirage/factories/storage-node.js
  ui/mirage/models/csi-plugin.js
  ui/mirage/models/csi-volume.js
  ui/mirage/models/storage-controller.js
  ui/mirage/models/storage-node.js
  ui/mirage/scenarios/default.js
  ui/mirage/serializers/csi-plugin.js
  ui/mirage/serializers/csi-volume.js
  ui/tests/acceptance/volume-detail-test.js
  ui/tests/acceptance/volumes-list-test.js
  ui/tests/unit/adapters/volume-test.js
  ui/tests/unit/serializers/volume-test.js
Labels: ui

#7486 api: prevent panic if volume has nil alloc
  api/csi.go
Labels: storage

#7491 UI: Change determination of exec sidebar active tasks
  ui/app/components/exec/task-group-parent.js
Labels: cleanup, ui

#7497 UI: Fix check for Mirage presence setting up sockets
  ui/app/services/sockets.js
Labels: bug, ui

#7345 Update website dependencies, fix IE11
  website/.npm-upgrade.json
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/downloads/index.jsx
Labels: website

#7504 website: Miscellaneous cherry-picks from stable-website that was accidentally never pushed to master
  website/components/learn-nomad/index.jsx
  website/components/learn-nomad/style.css
  website/components/mega-nav/img/hashicorp-logo.svg
  website/components/mega-nav/img/temporary_suite/icon-angle.svg
  website/components/mega-nav/img/temporary_suite/logo-consul.svg
  website/components/mega-nav/img/temporary_suite/logo-hashicorp-wordmark.svg
  website/components/mega-nav/img/temporary_suite/logo-hashicorp.svg
  website/components/mega-nav/img/temporary_suite/logo-nomad.svg
  website/components/mega-nav/img/temporary_suite/logo-packer.svg
  website/components/mega-nav/img/temporary_suite/logo-terraform.svg
  website/components/mega-nav/img/temporary_suite/logo-vagrant.svg
  website/components/mega-nav/img/temporary_suite/logo-vault.svg
  website/components/mega-nav/index.jsx
  website/components/mega-nav/style.css
  website/components/mega-nav/temporary_suite.css
  website/components/mega-nav/temporary_suite.jsx
  website/components/mini-cta/style.css
  website/components/subnav/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
  website/pages/use-cases/img/csi.svg
  website/pages/use-cases/simple-container-orchestration.jsx
Labels: website

#7505 website: Cherry picks back into stable-website
  website/components/learn-nomad/index.jsx
  website/components/learn-nomad/style.css
  website/components/mega-nav/img/hashicorp-logo.svg
  website/components/mega-nav/img/temporary_suite/icon-angle.svg
  website/components/mega-nav/img/temporary_suite/logo-consul.svg
  website/components/mega-nav/img/temporary_suite/logo-hashicorp-wordmark.svg
  website/components/mega-nav/img/temporary_suite/logo-hashicorp.svg
  website/components/mega-nav/img/temporary_suite/logo-nomad.svg
  website/components/mega-nav/img/temporary_suite/logo-packer.svg
  website/components/mega-nav/img/temporary_suite/logo-terraform.svg
  website/components/mega-nav/img/temporary_suite/logo-vagrant.svg
  website/components/mega-nav/img/temporary_suite/logo-vault.svg
  website/components/mega-nav/index.jsx
  website/components/mega-nav/style.css
  website/components/mega-nav/temporary_suite.css
  website/components/mega-nav/temporary_suite.jsx
  website/components/mini-cta/style.css
  website/components/subnav/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
Labels: website

#7472 csi: test volume denormalize without plugin
  nomad/state/state_store_test.go
  nomad/structs/csi.go
  nomad/structs/csi_test.go
Labels: storage, testing

#7512 UI: Guard against a null value for the HostVolumes hash
  ui/app/serializers/node.js
  ui/tests/unit/serializers/node-test.js
Labels: ui

#7287 Anchor Link Fixes
  website/README.md
  website/package-lock.json
  website/package.json
  website/pages/api-docs/acl-tokens.mdx
  website/pages/docs/commands/agent.mdx
  website/pages/docs/configuration/client.mdx
  website/pages/docs/drivers/exec.mdx
  website/pages/docs/drivers/external/singularity.mdx
  website/pages/docs/internals/consensus.mdx
  website/pages/docs/job-specification/dispatch_payload.mdx
  website/pages/docs/job-specification/scaling.mdx
  website/pages/docs/job-specification/service.mdx
  website/pages/docs/job-specification/task.mdx
  website/pages/docs/runtime/interpolation.mdx
  website/pages/guides/install/index.mdx
  website/pages/guides/install/production/reference-architecture.mdx
  website/pages/guides/install/quickstart/index.mdx
  website/pages/guides/integrations/vault-integration.mdx
  website/pages/guides/upgrade/upgrade-specific.mdx
  website/pages/intro/getting-started/running.mdx
Labels: website

#7503 [docs] System scheduler doesn't do deployments.
  website/pages/docs/schedulers.mdx
Labels: docs

#7543 Test flakiness fixes - 2020-03-30 Edition
  client/gc_test.go
  command/agent/consul/unit_test.go
  command/agent/node_endpoint_test.go
  drivers/docker/driver_linux_test.go
  nomad/autopilot_test.go
  nomad/client_agent_endpoint_test.go
  nomad/drainer/watch_jobs.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/vendor.json
Labels: flaky-tests, testing

#7546 state: support snapshot of CSI plugin and volume tables
  nomad/fsm.go
  nomad/mock/mock.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: raft, storage

#7534 windows: support -dev mode
  command/agent/config.go
Labels: platform-windows

#7549 csi: add grpc retries to client controller RPCs
  client/csi_controller_endpoint.go
  client/pluginmanager/csimanager/volume.go
  plugins/csi/client.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
Labels: storage

#7552 csi: annotate remaining missing cancellation contexts
  client/allocrunner/csi_hook.go
  client/pluginmanager/csimanager/fingerprint_test.go
Labels: storage

#7551 UI: Use new text encoder for stream frames
  ui/app/utils/stream-frames.js
  ui/tests/unit/utils/stream-frames-test.js
Labels: ui

#7344 UI: Facet for host volumes
  nomad/node_endpoint_test.go
  nomad/structs/structs.go
  ui/app/controllers/clients/index.js
  ui/app/templates/clients/index.hbs
  ui/mirage/factories/node.js
  ui/tests/acceptance/clients-list-test.js
  ui/tests/pages/clients/list.js
Labels: ui

#7559 client: use NewNodeEvent builder for consistency
  client/node_updater.go
Labels: storage

#7548 UI: Change exec button to not show on dead jobs
  ui/app/templates/components/job-page/parts/title.hbs
Labels: bug, ui

#7566 UI: Add exec loading template
  ui/app/styles/components/exec.scss
  ui/app/templates/exec-loading.hbs
  ui/app/templates/exec.hbs
Labels: bug, ui

#7547 csi: add node events to report progress mounting and unmounting volumes
  client/client.go
  client/pluginmanager/csimanager/instance.go
  client/pluginmanager/csimanager/manager.go
  client/pluginmanager/csimanager/volume.go
  client/pluginmanager/csimanager/volume_test.go
  command/node_status.go
  nomad/structs/structs.go
Labels: storage

#7569 [docs] Fix syntax error in docs
  website/pages/docs/job-specification/service.mdx
Labels: docs, website
