Repository hashicorp/nomad, pull requests merged in 2021-03, with the labels that each got.

#10100 update policy.mdx -- fixing strategy name
  website/content/docs/autoscaling/policy.mdx
Labels: theme/autoscaling, theme/docs, type/bug

#10094 UI: Fix rendering of DAS interstitial components
  CHANGELOG.md
  ui/app/components/das/recommendation-card.hbs
  ui/app/components/das/recommendation-card.js
Labels: stage/needs-backporting, theme/enterprise, theme/ui, type/bug

#10006 [Website] Enhancements to /docs/ecosystem
  website/components/ecosystem-integration-group/ecosystem-integration-card/index.jsx
  website/components/ecosystem-integration-group/ecosystem-integration-card/style.module.css
  website/components/ecosystem-integration-group/index.jsx
  website/components/ecosystem-integration-group/style.module.css
  website/components/smart-link/index.jsx
  website/content/docs/ecosystem.mdx
  website/pages/docs/[[...page]].jsx
Labels: theme/docs

#10019 [Website] Updates to homepage, highlighting features
  website/components/comparison-callouts/index.jsx
  website/components/comparison-callouts/style.module.css
  website/package-lock.json
  website/package.json
  website/pages/home/img/nomad-vs-kubernetes/alternative.svg
  website/pages/home/img/nomad-vs-kubernetes/supplement.svg
  website/pages/home/img/partner-logos/cni.svg
  website/pages/home/img/partner-logos/consul.svg
  website/pages/home/img/partner-logos/csi.svg
  website/pages/home/img/partner-logos/datadog.svg
  website/pages/home/img/partner-logos/github.svg
  website/pages/home/img/partner-logos/jfrog.svg
  website/pages/home/img/partner-logos/nvidia.svg
  website/pages/home/img/partner-logos/prometheus.svg
  website/pages/home/img/partner-logos/vault.svg
  website/pages/home/index.jsx
  website/pages/home/style.css
Labels: theme/docs

#10119 docs: hightlight different default node drain deadline when using the Autoscaler
  website/content/docs/autoscaling/plugins/target.mdx
Labels: theme/autoscaling, theme/docs

#9885 Add extra Docker labels ( job name, task and task group name)
  client/allocrunner/taskrunner/task_runner.go
  drivers/docker/config.go
  drivers/docker/driver.go
  drivers/docker/driver_test.go
  plugins/drivers/driver.go
  website/content/docs/drivers/docker.mdx
Labels: stage/waiting-reply, theme/driver/docker, type/enhancement

#10128 docs: remove stale release guide
  dev/guides/releasing.md
Labels: theme/docs

#10131 docs: required capabilities on Linux
  website/content/docs/install/production/requirements.mdx
Labels: theme/docs

#10132 docs: clarify mount source path in filesystem docs
  website/content/docs/internals/filesystem.mdx
Labels: theme/docs

#10129 docs: swap master for main in Nomad repo
  contributing/README.md
  contributing/checklist-jobspec.md
  contributing/golang.md
  dev/hooks/pre-push
  e2e/README.md
  e2e/terraform/Makefile
  terraform/gcp/README.md
  ui/README.md
Labels: theme/docs

#10140 agent: return req error if prometheus metrics are disabled.
  CHANGELOG.md
  api/internal/testutil/server.go
  api/operator_metrics_test.go
  command/agent/metrics_endpoint.go
  command/agent/metrics_endpoint_test.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/api, theme/metrics, type/bug

#10143 scheduler/csi: fix early return when multiple volumes are requested
  CHANGELOG.md
  scheduler/feasible.go
  scheduler/feasible_test.go
Labels: stage/needs-backporting, theme/storage, type/bug

#10166 csi: upgrade CSI protobufs to 1.4.0
  go.mod
  go.sum
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/modules.txt
Labels: theme/dependencies, theme/storage

#10164 CSI: don't truncate CSI volume IDs
  command/volume_status.go
Labels: theme/storage, type/enhancement

#10141 docs: clarify HCL is parsed in CLI
  website/content/docs/job-specification/index.mdx
Labels: theme/docs

#10170 CSI: protobuffer mappings for Create/Delete/List volume RPCs
  plugins/csi/client.go
  plugins/csi/client_test.go
  plugins/csi/fake/client.go
  plugins/csi/plugin.go
  plugins/csi/testing/client.go
Labels: theme/storage, type/enhancement

#10187 Fixup uses of `sanity`
  api/internal/testutil/server.go
  command/agent/consul/unit_test.go
  drivers/shared/executor/executor_linux_test.go
  e2e/connect/acls.go
  helper/escapingio/reader_test.go
  helper/pluginutils/hclutils/util_test.go
  nomad/consul.go
  nomad/fsm_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/funcs_test.go
  nomad/structs/structs.go
  testutil/server.go
Labels: theme/core, theme/docs, type/enhancement

#10174 CSI: volume init command
  .gitignore
  command/commands.go
  command/volume_init.go
  website/content/docs/commands/volume/index.mdx
  website/content/docs/commands/volume/init.mdx
  website/data/docs-navigation.js
Labels: theme/cli, theme/storage, type/enhancement

#10158 CSI: remove prefix matching from CSIVolumeByID and fix CLI prefix matching
  CHANGELOG.md
  api/csi.go
  command/agent/csi_endpoint.go
  command/volume_deregister.go
  command/volume_detach.go
  command/volume_status_csi.go
  nomad/csi_endpoint.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  scheduler/feasible.go
  scheduler/scheduler.go
  vendor/github.com/hashicorp/nomad/api/csi.go
Labels: stage/needs-backporting, theme/storage, type/bug

#10136 CSI: unique volume per allocation
  CHANGELOG.md
  api/tasks.go
  client/allocrunner/csi_hook.go
  command/agent/job_endpoint.go
  e2e/csi/input/use-ebs-volume.nomad
  e2e/terraform/compute.tf
  e2e/terraform/terraform.tfvars
  e2e/terraform/volumes.tf
  nomad/state/state_store.go
  nomad/structs/diff_test.go
  nomad/structs/funcs.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  nomad/structs/volumes.go
  scheduler/feasible.go
  scheduler/feasible_test.go
  scheduler/generic_sched.go
  scheduler/generic_sched_test.go
  scheduler/stack.go
  scheduler/stack_test.go
  scheduler/system_sched.go
  scheduler/util.go
  vendor/github.com/hashicorp/nomad/api/tasks.go
  website/content/docs/job-specification/update.mdx
  website/content/docs/job-specification/volume.mdx
Labels: theme/storage, type/enhancement

#10193 test infrastructure for mock client RPCs
  client/client.go
  client/client_test.go
  client/rpc.go
  client/testing.go
  command/agent/agent.go
  nomad/client_csi_endpoint_test.go
Labels: theme/storage, theme/testing

#10185 CSI: create/delete/list volume RPCs
  client/csi_endpoint.go
  client/csi_endpoint_test.go
  client/pluginmanager/csimanager/volume_test.go
  client/structs/csi.go
  nomad/client_csi_endpoint.go
  nomad/client_csi_endpoint_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/structs/csi.go
  plugins/csi/plugin.go
Labels: theme/storage, type/enhancement

#10212 E2E: CSI test should use expected unique-volume name
  e2e/csi/csi.go
Labels: theme/storage, theme/testing

#10223 E2E: bump AWS CSI driver versions
  e2e/csi/input/plugin-aws-ebs-controller.nomad
  e2e/csi/input/plugin-aws-ebs-nodes.nomad
  e2e/csi/input/plugin-aws-efs-nodes.nomad
Labels: theme/storage

#10208 UI: Showed host reservations and allocation utilization by task on existing stats charts
  ui/app/components/chart-primitives/area.hbs
  ui/app/components/chart-primitives/tooltip.hbs
  ui/app/components/chart-primitives/v-annotations.js
  ui/app/components/line-chart.js
  ui/app/components/primary-metric.js
  ui/app/components/primary-metric/allocation.hbs
  ui/app/components/primary-metric/allocation.js
  ui/app/components/primary-metric/current-value.hbs
  ui/app/components/primary-metric/node.hbs
  ui/app/components/primary-metric/node.js
  ui/app/components/primary-metric/task.hbs
  ui/app/components/primary-metric/task.js
  ui/app/components/stats-time-series.js
  ui/app/helpers/bind.js
  ui/app/styles/charts/tooltip.scss
  ui/app/styles/components/tooltip.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/allocations/allocation/task/index.hbs
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/components/primary-metric.hbs
  ui/app/templates/components/stats-time-series.hbs
  ui/app/templates/topology.hbs
  ui/app/utils/classes/allocation-stats-tracker.js
  ui/mirage/factories/node.js
  ui/tests/integration/components/primary-metric/allocation-test.js
  ui/tests/integration/components/primary-metric/node-test.js
  ui/tests/integration/components/primary-metric/primary-metric.js
  ui/tests/integration/components/primary-metric/task-test.js
  ui/tests/unit/utils/allocation-stats-tracker-test.js
Labels: theme/ui

#10230 api: add Allocation client and server terminal status funcs.
  api/allocations.go
  api/allocations_test.go
  vendor/github.com/hashicorp/nomad/api/allocations.go
Labels: theme/allocation API, theme/api, type/enhancement

#10226 UI: Update to v4 of Ember Power Select
  ui/app/components/global-search/control.js
  ui/app/styles/components/global-search-container.scss
  ui/app/templates/components/agent-monitor.hbs
  ui/app/templates/components/drain-popover.hbs
  ui/app/templates/components/global-search/control.hbs
  ui/app/templates/components/gutter-menu.hbs
  ui/app/templates/components/page-size-select.hbs
  ui/app/templates/components/region-switcher.hbs
  ui/package.json
  ui/tests/acceptance/behaviors/page-size-select.js
  ui/tests/acceptance/job-detail-test.js
  ui/tests/acceptance/namespaces-test.js
  ui/tests/acceptance/regions-test.js
  ui/tests/integration/components/agent-monitor-test.js
  ui/tests/pages/clients/detail.js
  ui/tests/pages/clients/monitor.js
  ui/tests/pages/components/page-size-select.js
  ui/tests/pages/jobs/list.js
  ui/tests/pages/layout.js
  ui/tests/pages/servers/monitor.js
  ui/tests/pages/storage/volumes/list.js
  ui/tests/unit/utils/stream-logger-test.js
  ui/yarn.lock
Labels: theme/dependencies, theme/ui, type/bug

#10225 docs: note that Connect requires a hard-coded port
  website/content/docs/integrations/consul-connect.mdx
Labels: theme/docs

#10252 Debug: Remove extra linefeed in monitor.log
  CHANGELOG.md
  command/operator_debug.go
Labels: stage/needs-backporting

#10194 website: add should-build script
  website/package-lock.json
  website/package.json
  website/scripts/should-build.sh
Labels: theme/website

#10254 website: use global featured-slider component
  website/components/featured-slider-section/index.jsx
  website/components/featured-slider-section/style.css
  website/components/featured-slider/StatusBar.jsx
  website/components/featured-slider/index.jsx
  website/components/featured-slider/index.props.js
  website/components/featured-slider/style.css
  website/package-lock.json
  website/package.json
  website/pages/style.css
  website/pages/use-cases/automated-service-networking-with-consul.jsx
  website/pages/use-cases/non-containerized-application-orchestration.jsx
  website/pages/use-cases/simple-container-orchestration.jsx
Labels: theme/website

#10203 Reserved Cores [1/4]: Structs and scheduler implementation
  api/jobs_test.go
  api/nodes.go
  api/resources.go
  api/resources_test.go
  client/client_test.go
  command/agent/job_endpoint.go
  lib/cpuset/cpuset.go
  lib/cpuset/cpuset_test.go
  nomad/structs/diff_test.go
  nomad/structs/funcs.go
  nomad/structs/funcs_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  scheduler/rank.go
  scheduler/rank_test.go
  scheduler/util.go
  scheduler/util_test.go
  vendor/github.com/hashicorp/nomad/api/nodes.go
  vendor/github.com/hashicorp/nomad/api/resources.go
Labels: theme/resource-utilization, theme/scheduling, type/enhancement

#10261 fix(circle): change website branch filter to main
  .circleci/config.yml
Labels: theme/website

#10275 drivers/docker: fix flaky image coordinator test
  drivers/docker/coordinator_test.go
Labels: theme/flaky-tests, theme/platform-windows, type/bug
