Repository hashicorp/nomad, pull requests merged in 2021-07, with the labels that each got.

#10853 constraint on the Docker driver missing 'attr'
  website/content/docs/drivers/docker.mdx
Labels: stage/accepted, theme/docs, type/bug

#10861 api: Added `NewSystemJob` job creation helper function.
  .changelog/10861.txt
  api/jobs.go
  api/jobs_test.go
  vendor/github.com/hashicorp/nomad/api/jobs.go
Labels: stage/accepted, theme/api, type/enhancement

#10869 testing: prevent panic when `job status` output changes
  command/job_status_test.go
Labels: theme/testing

#10868 service: remove duplicate name check during validation
  .changelog/10868.txt
  nomad/structs/structs.go
Labels: stage/needs-backporting, theme/discovery, type/bug

#10870 cni: respect default `cni_config_dir` and `cni_path`
  .changelog/10870.txt
  command/agent/config.go
Labels: stage/needs-backporting, theme/cni

#10806 Enforce idempotency of dispatched jobs using token on dispatch request
  CHANGELOG.md
  api/api.go
  api/api_test.go
  command/agent/http.go
  command/agent/job_endpoint_test.go
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  nomad/structs/structs.go
  vendor/github.com/hashicorp/nomad/api/api.go
Labels: theme/batch, type/enhancement

#10802 website: remove redirect away from existing page
  website/redirects.js
Labels: theme/docs, theme/website

#10889 [Website] Bump hashi-stack-menu
  website/package-lock.json
  website/package.json
Labels: theme/website

#10563 Capture ACL Token from self API call for Reverse Proxy use-case
  ui/app/services/token.js
  ui/tests/acceptance/proxy-test.js
Labels: theme/ui

#10892 deps: update consul-template to v0.25.2.
  .changelog/10892.txt
  go.mod
  go.sum
  vendor/github.com/golang/snappy/AUTHORS
  vendor/github.com/golang/snappy/CONTRIBUTORS
  vendor/github.com/golang/snappy/decode.go
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/decode_asm.go
  vendor/github.com/golang/snappy/decode_other.go
  vendor/github.com/golang/snappy/encode.go
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/github.com/golang/snappy/encode_asm.go
  vendor/github.com/golang/snappy/encode_other.go
  vendor/github.com/hashicorp/consul-template/config/config.go
  vendor/github.com/hashicorp/consul-template/dependency/vault_common.go
  vendor/github.com/hashicorp/consul-template/manager/runner.go
  vendor/github.com/hashicorp/consul-template/version/version.go
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-shellwords/.travis.yml
  vendor/github.com/mattn/go-shellwords/README.md
  vendor/github.com/mattn/go-shellwords/go.mod
  vendor/github.com/mattn/go-shellwords/go.test.sh
  vendor/github.com/mattn/go-shellwords/shellwords.go
  vendor/github.com/mattn/go-shellwords/util_go15.go
  vendor/github.com/mattn/go-shellwords/util_posix.go
  vendor/github.com/mattn/go-shellwords/util_windows.go
  vendor/github.com/pierrec/lz4/.travis.yml
  vendor/github.com/pierrec/lz4/README.md
  vendor/github.com/pierrec/lz4/block.go
  vendor/github.com/pierrec/lz4/decode_other.go
  vendor/github.com/pierrec/lz4/errors.go
  vendor/github.com/pierrec/lz4/lz4.go
  vendor/github.com/pierrec/lz4/reader.go
  vendor/github.com/pierrec/lz4/writer.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/gopkg.in/square/go-jose.v2/.gitignore
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/jwk.go
  vendor/gopkg.in/square/go-jose.v2/jwt/claims.go
  vendor/gopkg.in/square/go-jose.v2/jwt/validation.go
  vendor/modules.txt
Labels: stage/accepted, stage/needs-backporting, theme/dependencies, type/bug

#10864 scheduler: datacenter updates should be destructive
  .changelog/10864.txt
  scheduler/generic_sched_test.go
  scheduler/util.go
Labels: stage/needs-backporting

#10875 cli: `-namespace` should override job namespace
  .changelog/10875.txt
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
Labels: stage/needs-backporting, theme/cli, theme/namespaces

#10886 Handle successful/canceled/blocked deployments in CLI output
  command/deployment_status.go
  website/content/docs/commands/deployment/status.mdx
  website/content/docs/commands/job/run.mdx
Labels: theme/cli, type/enhancement

#10907 client: avoid acting on stale data after launch
  .changelog/10907.txt
  client/client.go
Labels: backport/1.0

#10675 ui: add parameterized dispatch interface
  ui/app/abilities/job.js
  ui/app/adapters/job.js
  ui/app/components/job-dispatch.js
  ui/app/models/job-dispatch.js
  ui/app/models/job.js
  ui/app/models/task-group.js
  ui/app/models/task.js
  ui/app/router.js
  ui/app/routes/jobs/job/dispatch.js
  ui/app/templates/components/job-dispatch.hbs
  ui/app/templates/components/job-page/parameterized-child.hbs
  ui/app/templates/components/job-page/parts/children.hbs
  ui/app/templates/components/job-subnav.hbs
  ui/app/templates/jobs/job/dispatch.hbs
  ui/app/utils/classes/exec-socket-xterm-adapter.js
  ui/app/utils/encode.js
  ui/mirage/config.js
  ui/mirage/factories/job.js
  ui/package.json
  ui/tests/acceptance/job-dispatch-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/pages/jobs/detail.js
  ui/tests/pages/jobs/dispatch.js
  ui/tests/unit/abilities/job-test.js
  ui/tests/unit/adapters/job-test.js
  ui/tests/unit/models/task-group-test.js
  ui/tests/unit/models/task-test.js
  ui/tests/unit/utils/encode-test.js
  ui/yarn.lock
Labels: stage/accepted, theme/ui, type/enhancement

#10921 docs: fixup regions API documentation path to include version.
  website/content/api-docs/regions.mdx
Labels: stage/accepted, theme/docs, type/bug

#10926 cli: Use glint to determine if os.Stdout is tty
  .changelog/10926.txt
  command/deployment_status.go
  go.mod
  go.sum
Labels: type/bug

#10952 nomad: only activate one-time auth tokens with 1.1.0
  .changelog/10952.txt
  nomad/acl_endpoint.go
  nomad/leader.go
Labels: type/bug

#10908 web: migrate to web platform- packages
  website/.eslintrc.js
  website/.stylelintrc.js
  website/components/subnav/index.jsx
  website/next-env.d.ts
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/_error.jsx
  website/pages/style.css
  website/pages/use-cases/simple-container-orchestration.jsx
  website/prettier.config.js
Labels: theme/website

#10961 website: add back tab styles
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: theme/website

#10972 Adds documentation for file mode to sink docs
  website/content/docs/configuration/audit.mdx
Labels: theme/docs, theme/enterprise
