Repository hashicorp/nomad, pull requests merged in 2021-09, with the labels that each got.

#11110 ui: set namespace when looking for and displaying children jobs
  .changelog/11110.txt
  ui/app/components/job-page/parts/children.js
  ui/app/routes/jobs/job/index.js
  ui/app/templates/components/job-page/parts/children.hbs
  ui/tests/acceptance/job-detail-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/pages/jobs/detail.js
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11119 fix(website): `start` script reloads app on save
  website/package.json
Labels: theme/website

#11141 ui: set the job namespace when redirecting after the job is dispatched
  .changelog/11141.txt
  ui/app/components/job-dispatch.js
  ui/app/templates/components/job-page/parts/title.hbs
  ui/tests/acceptance/job-dispatch-test.js
  ui/tests/integration/components/job-page/periodic-test.js
  ui/tests/pages/jobs/detail.js
Labels: stage/needs-backporting, backport/1.1

#11128 cli: include all possible scores in alloc status metric table
  .changelog/11128.txt
  command/monitor.go
  command/monitor_test.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11143 deps: update go-plugin to v1.4.3 to fix Windows handle leak.
  .changelog/11143.txt
  go.mod
  go.sum
Labels: type/bug, theme/plugin, theme/dependencies, stage/accepted

#11105 ci: add staticcheck with ST1020 and update golangci-lint
  .golangci.yml
  GNUmakefile
  acl/policy.go
  client/client.go
  client/pluginmanager/drivermanager/manager.go
  command/alloc_status.go
  helper/noxssrw/noxssrw.go
  scheduler/util.go
Labels: type/enhancement, theme/testing, stage/accepted

#11145 docs: Update Nvidia GPU installation instructions
  website/content/docs/devices/nvidia.mdx
Labels: theme/docs

#11189 docs: add changelog and website entry for #11173
  .changelog/11173.txt
  website/content/docs/job-specification/network.mdx
Labels: type/enhancement, theme/docs, stage/accepted

#11194 e2e: fix provisioning when ACLs and TLS enabled.
  e2e/terraform/nomad-acls.tf
  e2e/terraform/terraform.full.tfvars
Labels: type/bug, theme/e2e

#11168 Fixed usage of NOMAD_CLI_NO_COLOR env variable.
  .changelog/11168.txt
  command/meta.go
  command/meta_test.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11206 client: task env vars should take precedence over host env vars.
  .changelog/11206.txt
  client/taskenv/env.go
  client/taskenv/env_test.go
Labels: type/bug, theme/client, stage/needs-backporting, stage/accepted, backport/1.0, backport/1.1

#11215 client: add NOMAD_LICENSE to default env deny list
  .changelog/11215.txt
  client/config/config.go
  command/agent/host/host.go
  website/content/docs/configuration/client.mdx
Labels: stage/needs-backporting, backport/1.1

#11183 Disable PowerShell profile and simplify fingerprinting link speed on Windows
  .changelog/11183.txt
  client/fingerprint/network_windows.go
  client/fingerprint/network_windows_test.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11218 DOCS: Clarify the reservation example
  website/content/docs/configuration/client.mdx
Labels: type/enhancement, theme/docs

#11224 docs: fix API docs node evaluate example call.
  website/content/api-docs/nodes.mdx
Labels: type/bug, theme/docs, stage/accepted

#10992 Add Portworx CSI Driver example
  demo/csi/portworx-csi-plugin/README.md
  demo/csi/portworx-csi-plugin/portworx-csi-plugin.hcl
  demo/csi/portworx-csi-plugin/portworx-volume.hcl
Labels: type/enhancement, theme/docs

#10796 devices: externalize nvidia device driver
  .circleci/config.yml
  devices/gpu/nvidia/README.md
  devices/gpu/nvidia/cmd/main.go
  devices/gpu/nvidia/device.go
  devices/gpu/nvidia/device_test.go
  devices/gpu/nvidia/fingerprint.go
  devices/gpu/nvidia/fingerprint_test.go
  devices/gpu/nvidia/nvml/client.go
  devices/gpu/nvidia/nvml/client_test.go
  devices/gpu/nvidia/nvml/driver_default.go
  devices/gpu/nvidia/nvml/driver_linux.go
  devices/gpu/nvidia/nvml/shared.go
  devices/gpu/nvidia/stats.go
  devices/gpu/nvidia/stats_test.go
  go.mod
  go.sum
  helper/pluginutils/catalog/register_nvidia_linux.go
  website/content/docs/devices/external/index.mdx
  website/content/docs/devices/external/nvidia.mdx
  website/content/docs/devices/index.mdx
  website/data/docs-nav-data.json
Labels: theme/devices
