Repository hashicorp/nomad, pull requests merged in 2021-06, with the labels that each got.

#10690 chore: updates text-split-with-logo-grid package
  website/package-lock.json
  website/package.json
  website/pages/home/img/partner-logos/gitlab-logo-gray-stacked-rgb.svg
  website/pages/home/index.jsx
Labels: theme/website

#10693 scheduler: test for reconciler's in-place rollback behavior
  scheduler/reconcile_test.go
Labels: theme/scheduling, theme/testing

#10696 docs: clarify default `check.initial_status` behavior
  website/content/docs/job-specification/service.mdx
Labels: hcc/cst, theme/consul, theme/docs

#10662 rotate algolia api key
  website/.env
Labels: theme/website

#10650 docs: fix broken links in `nomad csi snapshot` commands
  website/content/docs/commands/volume/snapshot-create.mdx
  website/content/docs/commands/volume/snapshot-delete.mdx
  website/content/docs/commands/volume/snapshot-list.mdx
Labels: theme/docs

#10698 drivers/exec: Don't inherit Nomad oom_score_adj value
  drivers/shared/executor/executor_linux.go
  drivers/shared/executor/executor_linux_test.go
Labels: stage/needs-backporting

#10651 csi: validate `volume` block has `attachment_mode` and `access_mode`
  CHANGELOG.md
  nomad/job_endpoint_test.go
  nomad/structs/structs_test.go
  nomad/structs/volumes.go
Labels: theme/storage

#10703 CSI: accept list of caps during validation in volume register
  CHANGELOG.md
  client/csi_endpoint_test.go
  client/structs/csi.go
  nomad/csi_endpoint.go
  plugins/csi/client_test.go
  plugins/csi/plugin.go
Labels: theme/storage

#10710 pool: track usage of incoming streams
  client/rpc.go
  helper/pool/pool.go
  helper/pool/pool_test.go
Labels: stage/needs-backporting

#10714 Fixed global-search keyboard shortcut for non-english keyboard layouts.
  CHANGELOG.md
  ui/app/components/global-search/control.js
  ui/tests/acceptance/search-test.js
Labels: stage/needs-backporting

#10723 chanagelog: add entry for #10712
  CHANGELOG.md
Labels: stage/accepted, theme/docs, type/enhancement

#10724 docs: warn not to set `network_mode` for Connect-enabled Docker task
  website/content/docs/drivers/docker.mdx
Labels: theme/consul/connect, theme/docs

#10739 core: remove unused types pkg and PeriodicCallback type.
  nomad/types/types.go
Labels: stage/accepted, type/enhancement

#10745 deploymentwatcher: fix test data race.
  nomad/deploymentwatcher/deployments_watcher_test.go
Labels: theme/deployments, theme/testing, type/bug

#10750 Fix headshot image 404
  website/pages/home/index.jsx
Labels: theme/website

#10753 quotas: evaluate quota feasibility last in scheduler
  CHANGELOG.md
  scheduler/stack.go
Labels: stage/needs-backporting, theme/ent/quotas, type/bug

#10752 volumewatcher: fix test data race.
  nomad/volumewatcher/volumes_watcher_test.go
Labels: theme/testing, type/bug

#10758 plugins: fix test data race.
  plugins/drivers/testutils/testing_test.go
Labels: stage/accepted, theme/plugin, theme/testing, type/bug

#10764 consul: make failures_before_critical and success_before_passing work with group services
  CHANGELOG.md
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
Labels: stage/needs-backporting

#10765 client/fingerprint/java: improve java version string regex matching
  drivers/java/driver.go
  drivers/java/utils.go
  drivers/java/utils_test.go
Labels: stage/needs-backporting

#10766 docker: generate /etc/hosts file for bridge network mode
  CHANGELOG.md
  client/allocrunner/network_hook.go
  drivers/docker/driver.go
  drivers/shared/hostnames/mount.go
  drivers/shared/hostnames/mount_unix_test.go
  plugins/drivers/driver.go
  plugins/drivers/proto/driver.pb.go
  plugins/drivers/proto/driver.proto
  plugins/drivers/utils.go
  website/content/docs/drivers/docker.mdx
Labels: theme/driver/docker, theme/networking

#10774 docs: host_network does support Docker task port mapping
  website/content/docs/job-specification/network.mdx
Labels: theme/docs, theme/networking

#10776 consul/connect: in-place update service definition when connect upstreams are modified
  command/agent/consul/service_client.go
  command/agent/consul/service_client_test.go
Labels: stage/needs-backporting

#10778 deps: bump go-getter to 1.5.4
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/go.mod
  vendor/github.com/hashicorp/go-getter/client.go
  vendor/github.com/hashicorp/go-getter/client_option_insecure.go
  vendor/github.com/hashicorp/go-getter/detect_s3.go
  vendor/github.com/hashicorp/go-getter/get_gcs.go
  vendor/github.com/hashicorp/go-getter/get_http.go
  vendor/github.com/hashicorp/go-getter/get_s3.go
  vendor/github.com/hashicorp/go-getter/go.mod
  vendor/github.com/hashicorp/go-getter/go.sum
  vendor/modules.txt
Labels: stage/needs-backporting, theme/dependencies

#10783 tests: allocrunner CNI tests are Linux-only
  client/allocrunner/networking_cni_test.go
Labels: theme/testing

#10798 docs: improve CSI deployment recommendations
  website/content/docs/job-specification/csi_plugin.mdx
Labels: theme/docs, theme/storage

#10792 website: upgrade code-block
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: theme/docs, theme/website

#10818 csi: fix CLI panic when formatting volume status with -verbose flag
  CHANGELOG.md
  command/volume_status_csi.go
Labels: theme/storage, type/bug

#10811 website: upgrade react-head
  website/package-lock.json
  website/package.json
Labels: theme/website

#10827 docs: add missing backwards compat warning about port_map
  CHANGELOG.md
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/docs

#10828 docs: unset port `to` field maps to dynamic port
  CHANGELOG.md
  website/content/docs/job-specification/network.mdx
Labels: theme/docs, theme/networking

#10822 cli: fixed system commands so they correctly use passed flags.
  command/system_gc.go
  command/system_gc_test.go
  command/system_reconcile_summaries.go
  command/system_reconcile_summaries_test.go
Labels: stage/accepted, theme/cli, type/bug

#10831 [docs] Fix missing opening quote
  website/content/docs/drivers/docker.mdx
Labels: stage/accepted, theme/docs, type/bug

#10829 changelog: add entry for #10822
  CHANGELOG.md
Labels: stage/accepted, theme/docs, type/enhancement

#10823 docker: move host path for hosts file mount to alloc dir
  .changelog/10823.txt
  drivers/docker/driver.go
  drivers/shared/hostnames/mount.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/driver/docker, theme/networking
