Repository hashicorp/nomad, pull requests merged in 2021-10, with the labels that each got.

#11249 deps: update hashicorp/go-discover.
  .changelog/11249.txt
  go.mod
Labels: type/enhancement, theme/discovery, theme/dependencies, stage/accepted

#11257 fix panic when Connect mesh gateway doesn't have a proxy block
  .changelog/11257.txt
  command/agent/consul/service_client.go
  nomad/job_endpoint_hook_connect.go
  nomad/job_endpoint_hook_connect_test.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11261 Fix a logmon goroutine and memory leak
  .changelog/11261.txt
  client/logmon/logging/rotator.go
  client/logmon/logging/rotator_test.go
  go.mod
  go.sum
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11247 website: upgrade dependencies
  .circleci/config.yml
  website/.nvmrc
  website/Dockerfile
  website/components/basic-hero/style.css
  website/global.d.ts
  website/next-env.d.ts
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: theme/website

#11273 executor: suppress spurious log messages
  .changelog/11273.txt
  drivers/shared/executor/client.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11283 deps: update hashicorp/go-hclog to v1.0.0
  .changelog/11283.txt
  go.mod
  go.sum
Labels: type/enhancement, theme/dependencies, stage/accepted

#10799 Return SchedulerConfig instead of SchedulerConfigResponse struct
  .changelog/10799.txt
  api/operator.go
  command/agent/operator_endpoint.go
  command/agent/operator_endpoint_test.go
  e2e/oversubscription/oversubscription.go
  internal/testing/apitests/operator_test.go
  website/content/api-docs/operator/scheduler.mdx
Labels: type/bug, theme/api, hcc/sme

#11346 Fix preemption panic
  nomad/structs/funcs.go
  scheduler/preemption_test.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1
