Repository hashicorp/nomad, pull requests merged in 2021-11, with the labels that each got.

#11144 Making RPC Upgrade mode reloadable.
  .changelog/11144.txt
  command/agent/agent.go
  command/agent/agent_test.go
Labels: type/enhancement, theme/tls

#11411 cli: add json and template flag opts to acl bootstrap command.
  .changelog/11411.txt
  command/acl_bootstrap.go
  website/content/docs/commands/acl/bootstrap.mdx
Labels: type/enhancement, theme/cli, stage/accepted

#11430 scripts: install latest version of Consul and Vault.
  scripts/vagrant-linux-priv-consul.sh
  scripts/vagrant-linux-priv-vault.sh
Labels: type/enhancement, theme/build-infrastructure, stage/accepted

#11425 docs: document Consul timeout config parameter.
  website/content/docs/configuration/consul.mdx
Labels: type/bug, theme/docs, stage/accepted

#11423 Parse `job > group > consul` block in HCL1
  .changelog/11423.txt
  jobspec/parse_group.go
  jobspec/parse_test.go
  jobspec/test-fixtures/consul-namespace.hcl
Labels: type/enhancement, theme/consul

#11416 core: bump rejected plans from debug -> info
  .changelog/11416.txt
  nomad/plan_apply.go
  website/redirects.js
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11333 exactly one of ingress, terminating, or mesh must be configured
  website/content/docs/job-specification/gateway.mdx
Labels: type/bug, theme/docs, stage/accepted

#11444 docs: update API alloc list sample response to be current.
  website/content/api-docs/allocations.mdx
Labels: type/bug, theme/docs, stage/accepted

#11429 rpc: set the job scale eval priority to the job priority.
  .changelog/11429.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
Labels: type/bug, theme/scheduling

#11426 rpc: set the deregistration eval priority to the job priority.
  .changelog/11426.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
Labels: type/bug, theme/scheduling, stage/needs-backporting, backport/1.0, backport/1.1

#11504 deps: update armon/go-metrics to v0.3.10.
  .changelog/11504.txt
  go.mod
  go.sum
Labels: type/bug, type/enhancement, theme/dependencies, stage/accepted

#11541 docs: add global query param to API job deregister endpoint.
  website/content/api-docs/jobs.mdx
Labels: theme/docs

#11561 tools: update virtualbox networking configuration
  Vagrantfile
Labels: theme/dev-environment

#11555 config: UI configuration block with Vault/Consul links
  command/agent/config.go
  command/agent/http.go
  nomad/structs/config/ui.go
  nomad/structs/config/ui_test.go
  website/content/docs/configuration/ui.mdx
  website/data/docs-nav-data.json
Labels: theme/config, theme/ui

#11571 config: fix test-only failures in UI handler setup
  command/agent/http_test.go
Labels: theme/testing

#11583 docs: `mount_flags` takes a slice of strings
  website/content/docs/job-specification/volume.mdx
Labels: theme/docs

#11585 client: respect `client_auto_join` after connection loss
  .changelog/11585.txt
  client/client.go
Labels: backport/1.0, backport/1.1
