Repository hashicorp/nomad, pull requests merged in 2021-08, with the labels that each got.

#10950 Rookout driver docs
  website/content/docs/drivers/external/index.mdx
  website/content/docs/drivers/external/rookout.mdx
Labels: stage/accepted, theme/docs, type/enhancement

#10987 docs: order external driver overview alphabetically.
  website/content/docs/drivers/external/index.mdx
  website/data/docs-nav-data.json
Labels: stage/accepted, theme/docs, type/enhancement

#10976 API docs: Fix allocation restart example
  website/content/api-docs/allocations.mdx
Labels: theme/docs, type/bug

#10990 Only initialize task.VolumeMounts when not-nil
  .changelog/10990.txt
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
Labels: backport/1.0, stage/needs-backporting

#10996 cli: fix minor format error within `-ca-cert` help text.
  command/meta.go
Labels: stage/accepted, theme/cli, type/bug

#10929 fix: load token in docker auth config
  drivers/docker/utils.go
Labels: backport/1.0, stage/accepted, stage/needs-backporting, theme/driver/docker, type/bug

#11006 changelog: add entry for #10929
  .changelog/10929.txt
Labels: type/bug, stage/needs-backporting, backport/1.0

#10989 Some Rookout docs tweaks
  website/content/docs/drivers/external/rookout.mdx
Labels: type/enhancement, theme/docs

#11019 ui: only dipslay "Dispatch Job" button on parameterized jobs
  .changelog/11019.txt
  ui/app/templates/components/job-page/parts/children.hbs
Labels: type/bug, theme/ui, stage/needs-backporting, backport/1.1

#10666 ui: Fix fuzzy search namespace-handling
  .changelog/10666.txt
  ui/app/components/global-search/control.js
  ui/mirage/config.js
  ui/tests/acceptance/search-test.js
Labels: type/bug, theme/ui, hcc/cst

#11020 ui: add missing pipe separator in parameterized and periodic jobs
  .changelog/11020.txt
  ui/app/templates/components/job-page/parameterized-child.hbs
  ui/app/templates/components/job-page/periodic-child.hbs
Labels: theme/ui

#11051 tlsutil: update testing certificates close to expiry.
  helper/tlsutil/testdata/README.md
  helper/tlsutil/testdata/ca-bad-key.pem
  helper/tlsutil/testdata/ca-bad.csr
  helper/tlsutil/testdata/ca-bad.pem
  helper/tlsutil/testdata/ca-key.pem
  helper/tlsutil/testdata/ca.csr
  helper/tlsutil/testdata/ca.pem
  helper/tlsutil/testdata/nomad-bad-key.pem
  helper/tlsutil/testdata/nomad-bad.csr
  helper/tlsutil/testdata/nomad-bad.pem
  helper/tlsutil/testdata/nomad-foo-key.pem
  helper/tlsutil/testdata/nomad-foo.csr
  helper/tlsutil/testdata/nomad-foo.pem
Labels: type/bug, theme/testing, stage/accepted

#11054 Consider all system jobs for a new node
  .changelog/11054.txt
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
  nomad/structs/structs.go
  scheduler/rank.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11064 Deflake tests attempts
  nomad/autopilot_test.go
  nomad/leader_test.go
Labels: theme/flaky-tests

#10936 Upgrade global styles
  website/components/footer/index.jsx
  website/components/footer/style.css
  website/content/security.mdx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/community/index.jsx
  website/pages/community/style.css
  website/pages/community/style.module.css
  website/pages/downloads/style.module.css
  website/pages/not-found/index.jsx
  website/pages/print.css
  website/pages/security/index.jsx
  website/pages/security/style.css
  website/pages/style.css
Labels: theme/website

#11070 Don't timestamp active log file
  .changelog/11070.txt
  command/agent/log_file.go
  command/agent/log_file_test.go
  website/content/docs/configuration/index.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: stage/needs-backporting, backport/1.1

#11042 docs: Remove note on ingress gateway hosts field needing a port number
  website/content/docs/job-specification/gateway.mdx
Labels: theme/docs

#11065 Update x/sys to support go 1.17
  .changelog/11065.txt
  go.mod
  go.sum
Labels: type/enhancement, theme/dependencies, stage/accepted

#11091 cni: consolidate cni plugins within test install and docs to use v1.0.0
  e2e/terraform/packer/ubuntu-bionic-amd64/setup.sh
  scripts/vagrant-linux-priv-cni.sh
  website/content/docs/drivers/external/containerd.mdx
  website/content/docs/job-specification/network.mdx
Labels: type/enhancement, theme/docs, theme/testing, theme/cni

#11092 Support mTLS clusters for e2e testing
  e2e/terraform/.terraform.lock.hcl
  e2e/terraform/config/dev-cluster/consul/base.json
  e2e/terraform/config/shared/consul-tls.json
  e2e/terraform/config/shared/nomad-tls.hcl
  e2e/terraform/config/shared/vault-tls.hcl
  e2e/terraform/network.tf
  e2e/terraform/nomad.tf
  e2e/terraform/outputs.tf
  e2e/terraform/packer/ubuntu-bionic-amd64/provision.sh
  e2e/terraform/provision-nomad/main.tf
  e2e/terraform/provision-nomad/variables.tf
  e2e/terraform/terraform.tfvars
  e2e/terraform/tls_ca.tf
  e2e/terraform/variables.tf
  e2e/terraform/vault.tf
Labels: theme/tls, theme/e2e

#11101 Mention the ndjson standard format the event stream uses
  website/content/api-docs/events.mdx
Labels: theme/docs
