Repository hashicorp/nomad, pull requests merged in 2022-10, with the labels that each got.

#14750 internals documentation with diagrams
  contributing/architecture-eval-lifecycle.md
  contributing/architecture-eval-states.md
  contributing/architecture-eval-triggers.md
  contributing/architecture-state-store.md
  website/content/docs/concepts/architecture.mdx
Labels: theme/docs, theme/scheduling, theme/deployments

#14767 Docs(job-specification/periodic): Add enabled toggle
  website/content/docs/job-specification/periodic.mdx
Labels: theme/docs, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#14786 deps: use install from current HEAD for `hc-install`
  .github/workflows/test-core.yaml
  GNUmakefile
Labels: type/bug, theme/build-infrastructure, backport/1.2.x, backport/1.3.x, backport/1.4.x

#14789 deps: remove gophers.dev dependency
  tools/go.mod
  tools/go.sum
  tools/missing/main.go
Labels: theme/dependencies, theme/build-infrastructure

#14792 variables: use correct URL in ref to docs
  command/var.go
Labels: theme/variables, backport/1.4.x

#14790 client: defer `nobody` user lookup so Windows doesn't panic
  client/allocdir/fs_unix.go
  helper/users/lookup.go
Labels: type/bug, theme/platform-windows, theme/crash, backport/1.4.x

#14812 semgrep: add MeasureSinceWithLabels to FSM time rule
  .semgrep/fsm_time.yml
Labels: theme/testing, backport/1.4.x

#14821 fix panic from keyring raft entries being written during upgrade
  .changelog/14821.txt
  nomad/encrypter.go
  nomad/leader.go
  nomad/plan_apply_test.go
  nomad/worker_test.go
Labels: type/bug, theme/crash, theme/variables, backport/1.4.x

#14830 website: upgrade next version
  website/package-lock.json
  website/package.json
Labels: theme/website

#14831 docs: clarify nomad vars vs vault
  website/content/docs/concepts/variables.mdx
Labels: backport/website

#14631 Allow specification of a custom job name/prefix for parameterized jobs
  .changelog/14631.txt
  api/jobs.go
  command/job_dispatch.go
  e2e/scheduler_sysbatch/sysbatch.go
  nomad/job_endpoint.go
  nomad/structs/structs.go
  website/content/docs/commands/job/dispatch.mdx
Labels: theme/cli, theme/batch, backport/1.4.x

#14615 Invoke FingerprintManager's Reload() func during agent's SIGHUP (Fixes #14614)
  .changelog/14615.txt
  client/client.go
Labels: type/enhancement, theme/fingerprint, backport/1.4.x

#14492 Check that JobPlanResponse Diff Type is None before checking for changes on getExitCode
  .changelog/14492.txt
  command/job_plan.go
Labels: type/bug, theme/cli, theme/batch

#14300 Allow jobs not requiring network resources with network fingerprinter disabled
  .changelog/14300.txt
  scheduler/feasible.go
Labels: theme/scheduling, backport/1.4.x

#14775 enhancement: UpdateTask when Task is waiting for ShutdownDelay
  .changelog/14775.txt
  client/allocrunner/taskrunner/task_runner.go
  nomad/structs/structs.go
Labels: theme/task lifecycle, backport/1.4.x

#14814 [ui] Line charts: explicitly update X-axis whenever xScale changes
  .changelog/14814.txt
  ui/app/components/line-chart.js
  ui/app/templates/components/line-chart.hbs
Labels: backport/1.4.x

#14779 feat: Add nomad fmt
  .changelog/14779.txt
  GNUmakefile
  command/commands.go
  command/fmt.go
  command/fmt_test.go
  command/testdata/fmt/job.in.hcl
  command/testdata/fmt/job.out.hcl
  command/testdata/fmt/nomad.in.hcl
  command/testdata/fmt/nomad.out.hcl
  website/content/docs/commands/fmt.mdx
  website/data/docs-nav-data.json
Labels: theme/cli, backport/1.4.x

#14834 [ui] Makes service tags wrap and look like tag items
  .changelog/14832.txt
  ui/app/components/allocation-service-sidebar.hbs
  ui/app/styles/components/inline-definitions.scss
Labels: backport/1.4.x

#14864 services: remove assertion on 'task' field being set
  .changelog/14864.txt
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  website/content/docs/job-specification/check.mdx
Labels: backport/1.4.x

#14875 docker_logger: reorder imports to save memory
  .changelog/14875.txt
  main.go
Labels: theme/driver/docker, theme/logging, theme/resource-utilization, backport/1.2.x, backport/1.3.x, backport/1.4.x

#14904 fix: website broken links
  website/content/api-docs/operator/keyring.mdx
  website/content/docs/commands/eval/delete.mdx
  website/content/docs/commands/operator/index.mdx
  website/content/docs/configuration/server.mdx
  website/content/docs/enterprise/index.mdx
  website/content/docs/operations/key-management.mdx
Labels: backport/website, backport/1.4.x

#14901 keyring: filter by region before checking version
  .changelog/14901.txt
  nomad/encrypter.go
  nomad/leader.go
Labels: type/bug, backport/1.4.x, theme/keyring

#14911 make version checks specific to region (1.3.x)
  .changelog/14911.txt
  nomad/acl_endpoint.go
  nomad/core_sched.go
  nomad/job_endpoint.go
  nomad/leader.go
  nomad/operator_endpoint.go
  nomad/periodic.go
  nomad/plan_apply.go
  nomad/util.go
  nomad/util_test.go
  nomad/worker.go
  scheduler/scheduler.go
Labels: type/bug, theme/scheduling

#14912 make version checks specific to region (1.4.x)
  .changelog/14912.txt
  nomad/acl_endpoint.go
  nomad/core_sched.go
  nomad/job_endpoint.go
  nomad/leader.go
  nomad/operator_endpoint.go
  nomad/periodic.go
  nomad/plan_apply.go
  nomad/util.go
  nomad/util_test.go
  nomad/variables_endpoint.go
  nomad/worker.go
  scheduler/scheduler.go
Labels: type/bug, backport/1.4.x

#14910 make version checks specific to region (1.2.x)
  .changelog/14910.txt
  nomad/acl_endpoint.go
  nomad/core_sched.go
  nomad/job_endpoint.go
  nomad/leader.go
  nomad/operator_endpoint.go
  nomad/periodic.go
  nomad/plan_apply.go
  nomad/util.go
  nomad/util_test.go
  nomad/worker.go
Labels: type/bug, theme/auth

#14917 consul: do not re-register already registered services
  .changelog/14917.txt
  command/agent/consul/service_client.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#14924 nnsd: gate registration write & delete RPC use on v1.3.0 or greater.
  .changelog/14924.txt
  nomad/leader.go
  nomad/service_registration_endpoint.go
Labels: backport/1.3.x, backport/1.4.x

#14908 acl: gate ACL role write and delete RPC usage on v1.4.0 or greater.
  .changelog/14908.txt
  nomad/acl_endpoint.go
  nomad/leader.go
Labels: backport/1.4.x

#14931 deps: bump shoenig/test to 0.4.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#14918 website: fixes redirected links
  website/content/docs/concepts/security.mdx
  website/content/docs/concepts/variables.mdx
  website/content/docs/configuration/consul.mdx
  website/content/docs/configuration/vault.mdx
  website/content/docs/faq.mdx
  website/content/docs/install/index.mdx
  website/content/docs/integrations/consul-connect.mdx
  website/content/docs/integrations/consul-integration.mdx
  website/content/docs/job-specification/check.mdx
  website/content/docs/job-specification/connect.mdx
  website/content/docs/job-specification/expose.mdx
  website/content/docs/job-specification/gateway.mdx
  website/content/docs/job-specification/proxy.mdx
  website/content/docs/job-specification/service.mdx
  website/content/docs/job-specification/task.mdx
  website/content/docs/job-specification/upstreams.mdx
  website/content/docs/operations/index.mdx
  website/content/docs/operations/monitoring-nomad.mdx
  website/content/docs/runtime/environment.mdx
  website/content/docs/runtime/interpolation.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
  website/content/partials/envvars.mdx
  website/content/plugins/drivers/podman.mdx
Labels: theme/website, backport/website, backport/1.4.x

#14940 chore: Update Digital Team Files
  website/Makefile
  website/scripts/should-build.sh
  website/scripts/website-build.sh
  website/scripts/website-start.sh
Labels: theme/website

#14843 api: add convenience string func to Topic type.
  api/event_stream.go
  api/event_stream_test.go
Labels: backport/1.4.x

#14953 Updated datacenter block description
  website/content/docs/configuration/index.mdx
Labels: backport/website

#14946 website: fix broken links
  website/content/docs/upgrade/upgrade-specific.mdx
  website/content/partials/envvars.mdx
Labels: theme/website, backport/website, backport/1.4.x

#14951 docs: explain autoscaler target-value strategy
  website/content/tools/autoscaling/plugins/strategy/target-value.mdx
Labels: theme/docs, theme/autoscaling, backport/website, backport/1.4.x

#14947 docs: move autoscaling `source` agent config
  website/content/tools/autoscaling/agent/apm.mdx
  website/content/tools/autoscaling/agent/http.mdx
  website/content/tools/autoscaling/agent/nomad.mdx
  website/content/tools/autoscaling/agent/policy.mdx
  website/content/tools/autoscaling/agent/policy_eval.mdx
  website/content/tools/autoscaling/agent/source.mdx
  website/content/tools/autoscaling/agent/strategy.mdx
  website/content/tools/autoscaling/agent/target.mdx
  website/content/tools/autoscaling/agent/telemetry.mdx
  website/data/tools-nav-data.json
Labels: theme/docs, theme/autoscaling, backport/website, backport/1.4.x

#14941 docs: add autoscaling debug
  website/content/tools/autoscaling/agent.mdx
  website/content/tools/autoscaling/api.mdx
  website/content/tools/autoscaling/cli.mdx
Labels: theme/docs, theme/autoscaling, backport/website, backport/1.4.x

#14913 Adds searching and filtering for nodes on topology view
  .changelog/14913.txt
  ui/app/controllers/topology.js
  ui/app/templates/components/topo-viz.hbs
  ui/app/templates/components/topo-viz/node.hbs
  ui/app/templates/topology.hbs
  ui/tests/acceptance/topology-test.js
  ui/tests/pages/topology.js
Labels: backport/1.4.x

#14937 docs: expand Autoscaling documentation
  website/content/tools/autoscaling/concepts/index.mdx
  website/content/tools/autoscaling/concepts/plugins/apm.mdx
  website/content/tools/autoscaling/concepts/plugins/base.mdx
  website/content/tools/autoscaling/concepts/plugins/index.mdx
  website/content/tools/autoscaling/concepts/plugins/strategy.mdx
  website/content/tools/autoscaling/concepts/plugins/target.mdx
  website/content/tools/autoscaling/concepts/policy-eval/checks.mdx
  website/content/tools/autoscaling/concepts/policy-eval/index.mdx
  website/content/tools/autoscaling/concepts/policy-eval/node-selector-strategy.mdx
  website/content/tools/autoscaling/internals/checks.mdx
  website/content/tools/autoscaling/internals/index.mdx
  website/content/tools/autoscaling/plugins/strategy/threshold.mdx
  website/content/tools/autoscaling/policy.mdx
  website/data/tools-nav-data.json
  website/public/img/autoscaling/autoscaler-arch.png
  website/public/img/autoscaling/control-loop.png
  website/public/img/autoscaling/policy-eval.png
  website/redirects.js
Labels: theme/docs, theme/autoscaling, backport/website, backport/1.4.x

#14922 acl: correctly resolve ACL roles within client cache.
  .changelog/14922.txt
  client/acl.go
  client/acl_test.go
  client/config/config.go
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  website/content/docs/configuration/acl.mdx
Labels: backport/1.4.x

#14923 acl: add ACL roles to event stream topic and resolve policies.
  .changelog/14923.txt
  nomad/acl_endpoint.go
  nomad/acl_endpoint_test.go
  nomad/state/events.go
  nomad/state/events_test.go
  nomad/state/state_store_acl.go
  nomad/stream/event_broker.go
  nomad/stream/event_broker_test.go
  nomad/structs/acl.go
  nomad/structs/acl_test.go
  nomad/structs/event.go
  website/content/api-docs/events.mdx
Labels: backport/1.4.x

#14798 refact: upgrade Promise.then to async/await
  .changelog/14798.txt
  ui/app/routes/allocations/allocation.js
  ui/app/templates/components/allocation-row.hbs
Labels: backport/1.3.x, backport/1.4.x

#14992 cli: prevent panic on `operator debug`
  .changelog/14992.txt
  command/operator_debug.go
Labels: backport/1.4.x

#14950 docs: use of `node_class` when autoscaling
  website/content/tools/autoscaling/plugins/apm/nomad.mdx
Labels: theme/docs, theme/autoscaling, backport/website, backport/1.4.x

#14987 keyring: fixes for keyring replication on cluster join
  nomad/encrypter.go
  nomad/encrypter_test.go
  nomad/keyring_endpoint.go
  nomad/leader.go
Labels: type/bug, theme/keyring

#15009 keyring: fix missing GC config, don't rotate on manual GC
  .changelog/14987.txt
  .changelog/15009.txt
  command/agent/agent.go
  nomad/core_sched.go
Labels: type/bug, backport/1.4.x, theme/keyring

#15021 deps: update hashicorp/raft to v1.3.11
  .changelog/15021.txt
  go.mod
  go.sum
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15020 docs: add details to redirects file
  website/redirects.js
Labels: theme/website, backport/website

#15026 keyring: refactor to hold locks for less time
  nomad/encrypter.go
Labels: backport/1.4.x, theme/keyring

#15027 client: ensure minimal cgroup controllers enabled
  .changelog/15027.txt
  client/lib/cgutil/cpuset_manager_v2.go
Labels: backport/1.3.x, backport/1.4.x

#15034 keyring: remove root key GC
  .changelog/15034.txt
  nomad/core_sched.go
  nomad/core_sched_test.go
  website/content/docs/configuration/server.mdx
Labels: type/bug, backport/1.4.x, theme/keyring

#15045 [deps] Update consul-template dependency
  .changelog/15045.txt
  go.mod
  go.sum
Labels: theme/consul-template, theme/dependencies, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15065 test: refactor EvalEndpoint_Delete
  nomad/eval_endpoint_test.go
Labels: theme/testing, backport/1.4.x

#15070 refactor eval delete safety check
  nomad/eval_endpoint.go
  nomad/eval_endpoint_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: type/enhancement, backport/1.4.x
