Repository hashicorp/nomad, pull requests merged in 2022-11, with the labels that each got.

#15092 keyring: safely handle missing keys and restore GC
  .changelog/15034.txt
  .changelog/15092.txt
  nomad/core_sched.go
  nomad/core_sched_test.go
  nomad/encrypter.go
  nomad/encrypter_test.go
  nomad/plan_apply.go
  nomad/state/schema.go
  nomad/state/state_store.go
  nomad/structs/keyring.go
  nomad/structs/structs.go
  nomad/variables_endpoint_test.go
  website/content/docs/configuration/server.mdx
Labels: type/bug, backport/1.4.x, theme/keyring

#15102 variables: limit rekey eval to half the nack timeout
  .changelog/15102.txt
  nomad/core_sched.go
Labels: type/bug, theme/variables, backport/1.4.x

#15101 volumewatcher: prevent panic on nil volume
  .changelog/15101.txt
  nomad/volumewatcher/volume_watcher.go
  nomad/volumewatcher/volumes_watcher.go
  nomad/volumewatcher/volumes_watcher_test.go
Labels: type/bug, theme/storage, backport/1.2.x, backport/1.3.x, backport/1.4.x

#14747 Job spec upload
  .changelog/14747.txt
  ui/app/components/job-editor.js
  ui/app/styles/components/codemirror.scss
  ui/app/templates/components/job-editor.hbs
  ui/tests/integration/components/job-editor-test.js
  ui/tests/pages/components/job-editor.js
Labels: backport/1.4.x

#14833 [ui] Adds meta to job list stub and displays a pack logo on the jobs index
  .changelog/14833.txt
  api/jobs.go
  command/agent/job_endpoint.go
  command/job_status.go
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  nomad/structs/structs.go
  ui/app/routes/jobs/index.js
  ui/app/routes/jobs/job.js
  ui/app/routes/jobs/job/index.js
  ui/app/styles/core/tag.scss
  ui/app/templates/components/job-row.hbs
  website/content/api-docs/jobs.mdx
Labels: backport/1.4.x

#15118 Accidentally trailed off on a docs paragraph
  website/content/api-docs/jobs.mdx
Labels: backport/1.4.x

#15121 WI: set identity to client secret if missing
  .changelog/15121.txt
  client/allocrunner/taskrunner/identity_hook.go
  client/allocrunner/taskrunner/task_runner.go
Labels: type/bug, theme/template, theme/auth, backport/1.4.x

#15126 Ember patched for security release
  ui/package.json
  ui/yarn.lock
Labels: backport/1.4.x

#15125 fix: batchFirstFingerprints does not update device on node after v1.3.5
  .changelog/15125.txt
  client/node_updater.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15134 Add missing timer reset
  .changelog/15134.txt
  nomad/plan_queue.go
Labels: type/bug, theme/metrics, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15141 template: error on missing key
  .changelog/14002.txt
  api/jobs_test.go
  api/tasks.go
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/parse_task.go
  jobspec/parse_test.go
  jobspec/test-fixtures/basic.hcl
  jobspec2/parse_job.go
  jobspec2/parse_test.go
  jobspec2/test-fixtures/template-err-missing-key.hcl
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  scheduler/util_test.go
  website/content/docs/job-specification/template.mdx
Labels: type/enhancement, theme/template, backport/1.4.x

#15140 client: retry RPC call when no server is available
  .changelog/15140.txt
  client/rpc.go
Labels: backport/1.3.x, backport/1.4.x

#15068 Update alloc after reconnect and enforece client heartbeat order
  .changelog/15068.txt
  client/client.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  scheduler/generic_sched.go
  scheduler/reconcile.go
  scheduler/reconcile_test.go
  scheduler/reconcile_util.go
  scheduler/reconcile_util_test.go
  scheduler/scheduler_system.go
  scheduler/scheduler_system_test.go
  scheduler/util.go
  scheduler/util_test.go
Labels: backport/1.3.x, backport/1.4.x

#15147 API for `Eval.Count`
  .changelog/15147.txt
  api/evaluations.go
  command/agent/eval_endpoint.go
  command/agent/eval_endpoint_test.go
  command/agent/http.go
  nomad/eval_endpoint.go
  nomad/eval_endpoint_test.go
  nomad/structs/structs.go
  website/content/api-docs/evaluations.mdx
Labels: type/enhancement, theme/api, backport/1.4.x

#15146 [ui] Remove animation from task logs sidebar
  .changelog/15146.txt
  ui/app/styles/components/sidebar.scss
Labels: backport/1.4.x

#15123 Fix s3 example URLs in the artifacts docs
  website/content/docs/job-specification/artifact.mdx
Labels: backport/website, backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#12916 api: remove `mapstructure` tags from`Port` struct
  .changelog/12916.txt
  api/resources.go
  client/client_test.go
  command/agent/event_endpoint_test.go
  command/agent/testingutils_test.go
  e2e/events/input/deploy.nomad
  e2e/events/input/initial.nomad
  jobspec/parse_network.go
  jobspec/parse_test.go
  jobspec/test-fixtures/parse-ports.hcl
Labels: theme/api, theme/events, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15192 template: protect use of template manager with a lock
  .changelog/15192.txt
  client/allocrunner/taskrunner/template_hook.go
Labels: backport/1.3.x, backport/1.4.x

#15191 acl: sso auth method schema and store functions
  .changelog/15191.txt
  helper/raftutil/msgtypes.go
  nomad/fsm.go
  nomad/mock/acl.go
  nomad/state/schema.go
  nomad/state/state_store_acl_sso.go
  nomad/state/state_store_acl_sso_test.go
  nomad/state/state_store_restore.go
  nomad/state/state_store_restore_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: type/enhancement, theme/auth

#15212 docs: clarify how to access task meta values in templates
  website/content/docs/job-specification/meta.mdx
  website/content/docs/job-specification/template.mdx
Labels: backport/website

#14851 exec: allow running commands from host volume
  .changelog/14851.txt
  drivers/shared/executor/executor_linux.go
  drivers/shared/executor/executor_linux_test.go
  website/content/docs/drivers/exec.mdx
Labels: type/enhancement, theme/driver/exec, theme/driver/java

#15215 client: avoid unconsumed channel in timer construction
  .changelog/15215.txt
  client/allocrunner/taskrunner/task_runner.go
  helper/funcs.go
  helper/funcs_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15214 [bug] Return a spec on reconnect
  .changelog/15214.txt
  client/allocrunner/network_manager_linux.go
Labels: type/bug, theme/networking, theme/driver/exec

#15234 Fix broken URL to nvidia device plugin
  website/content/docs/concepts/plugins/devices.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15228 Fix wrong reference to `vault`
  website/content/docs/commands/var/put.mdx
Labels: backport/website, backport/1.4.x

#15117 eval delete: move batching of deletes into RPC handler and state
  .changelog/15117.txt
  api/evaluations.go
  command/agent/eval_endpoint.go
  command/agent/eval_endpoint_test.go
  command/eval_delete.go
  nomad/eval_endpoint.go
  nomad/eval_endpoint_test.go
  nomad/fsm.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/eval.go
  nomad/structs/structs.go
  website/content/docs/commands/eval/delete.mdx
Labels: theme/cli, backport/1.4.x

#15248 Fix example in docs
  website/content/api-docs/variables.mdx
Labels: backport/website, backport/1.4.x

#15267 test: ensure leader is still valid in reelection test
  nomad/leader_test.go
Labels: theme/flaky-tests, backport/1.4.x

#14621 eval broker: shed all but one blocked eval per job after ack
  .changelog/14621.txt
  nomad/config.go
  nomad/eval_broker.go
  nomad/eval_broker_test.go
  nomad/eval_endpoint.go
  nomad/leader.go
  nomad/server.go
  nomad/worker_test.go
Labels: type/enhancement, theme/scheduling, backport/1.4.x

#15242 fix create snapshot request docs
  website/content/api-docs/volumes.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15227 keyring: update handle to state inside replication loop
  .changelog/15227.txt
  nomad/encrypter.go
  nomad/encrypter_test.go
Labels: type/bug, backport/1.4.x, theme/keyring

#15271 ci: use hashicorp/setup-golang for setting up go compiler, cache
  .github/workflows/test-core.yaml
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15180 Fix goroutine leakage
  .changelog/15180.txt
  plugins/drivers/client.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15285 remove deprecated `AllocUpdateRequestType` raft entry
  nomad/fsm.go
  nomad/fsm_test.go
  nomad/state/events.go
  nomad/state/events_test.go
  website/content/docs/operations/metrics-reference.mdx
Labels: theme/cleanup, backport/1.4.x

#15290 autopilot: include only servers from the same region
  .changelog/15290.txt
  nomad/autopilot.go
  nomad/autopilot_test.go
Labels: type/bug, theme/autopilot, backport/1.4.x

#15294 make eval cancelation async with `Eval.Ack`
  nomad/eval_endpoint.go
Labels: theme/scheduling, backport/1.4.x

#15303 scheduler: log stack in case of panic
  scheduler/generic_sched.go
  scheduler/scheduler_system.go
Labels: backport/1.3.x, backport/1.4.x

#15298 make eval cancelation really async with `Eval.Ack`
  nomad/eval_endpoint.go
Labels: theme/scheduling, backport/1.4.x

#15299 docs: add cpu-allocated and memory-allocated
  website/content/tools/autoscaling/plugins/apm/nomad.mdx
Labels: backport/website, backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15252 api: ensure all request body decode error return a 400 status code.
  .changelog/15252.txt
  command/agent/acl_endpoint.go
  command/agent/agent_endpoint.go
  command/agent/namespace_endpoint.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15324 [ui] Show Consul Connect upstreams / on update info in sidebar
  .changelog/15324.txt
  ui/app/components/allocation-service-sidebar.hbs
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/components/job-service-row.hbs
Labels: theme/ui, backport/1.4.x

#15221 acl: sso auth method RPC endpoints
  nomad/acl_endpoint.go
  nomad/acl_endpoint_test.go
  nomad/config.go
  nomad/fsm.go
  nomad/fsm_test.go
  nomad/leader.go
  nomad/mock/acl.go
  nomad/structs/acl.go
  nomad/structs/acl_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: type/enhancement, theme/auth

#15309 client: accommodate Consul 1.14.0 gRPC and agent self changes.
  .changelog/15309.txt
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/consul_grpc_sock_hook.go
  client/allocrunner/consul_grpc_sock_hook_test.go
  client/fingerprint/consul.go
  client/fingerprint/consul_test.go
  website/content/docs/configuration/consul.mdx
  website/content/docs/integrations/consul-connect.mdx
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15348 pin build/release pipeline to ubuntu 20.04
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: theme/build-infrastructure, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15350 ensure engineering has merge authority on build pipeline
  CODEOWNERS
Labels: theme/build-infrastructure

#15355 [ui] Stabilize Percy tests for Exec and Logs Sidebar views
  ui/tests/acceptance/exec-test.js
  ui/tests/acceptance/task-logs-test.js
Labels: backport/1.4.x

#14296 Add command "nomad tls"
  .changelog/14296.txt
  command/commands.go
  command/tls.go
  command/tls_ca.go
  command/tls_ca_create.go
  command/tls_ca_create_test.go
  command/tls_ca_info.go
  command/tls_cert.go
  command/tls_cert_create.go
  command/tls_cert_create_test.go
  command/tls_cert_info.go
  helper/tlsutil/config.go
  helper/tlsutil/config_test.go
  helper/tlsutil/generate.go
  helper/tlsutil/generate_test.go
  lib/file/atomic.go
  testutil/tls.go
  website/content/docs/commands/tls/ca-create.mdx
  website/content/docs/commands/tls/ca-info.mdx
  website/content/docs/commands/tls/cert-create.mdx
  website/content/docs/commands/tls/cert-info.mdx
  website/content/docs/commands/tls/index.mdx
  website/data/docs-nav-data.json
Labels: theme/cli, backport/1.4.x

#15363 [ui] Task sub row alignment changes
  .changelog/15363.txt
  ui/app/styles/components/task-sub-row.scss
Labels: backport/1.4.x

#15337 Fix missing host header in http check
  .changelog/15337.txt
  client/serviceregistration/checks/client.go
  client/serviceregistration/checks/client_test.go
Labels: type/bug

#15373 fix linter for go.mod tidy
  go.sum
Labels: type/bug

#15262 cli: `wait` flag for use with `deployment status -monitor`
  .changelog/15262.txt
  command/deployment_status.go
  command/monitor.go
  website/content/docs/commands/deployment/status.mdx
Labels: type/enhancement, theme/cli, backport/1.4.x

#15326 cli: improve errors for multiregion deployments
  command/deployment_status.go
Labels: backport/1.4.x

#15372 scheduler: set job on system stack for CSI feasibility check
  .changelog/15372.txt
  scheduler/scheduler_system_test.go
  scheduler/stack.go
Labels: type/bug, theme/storage, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15325 scheduler: create placements for non-register MRD
  .changelog/15325.txt
  nomad/fsm.go
  nomad/job_endpoint.go
  nomad/job_endpoint_oss.go
  nomad/state/state_store.go
  nomad/structs/structs.go
  scheduler/reconcile.go
  scheduler/reconcile_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15387 docs: improve job parse API documentation
  website/content/api-docs/jobs.mdx
Labels: backport/website, backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15322 acl: sso auth methods cli commands
  command/acl_auth_method.go
  command/acl_auth_method_create.go
  command/acl_auth_method_create_test.go
  command/acl_auth_method_delete.go
  command/acl_auth_method_delete_test.go
  command/acl_auth_method_info.go
  command/acl_auth_method_info_test.go
  command/acl_auth_method_list.go
  command/acl_auth_method_list_test.go
  command/acl_auth_method_update.go
  command/acl_auth_method_update_test.go
  command/commands.go
  command/helpers.go
Labels: type/enhancement, theme/auth

#15410 acl: sso auth methods RPC/API/CLI should return created or updated objects
  api/acl.go
  api/acl_test.go
  command/acl_auth_method_create.go
  command/acl_auth_method_update.go
  command/agent/acl_endpoint.go
  command/agent/acl_endpoint_test.go
  nomad/acl_endpoint.go
  nomad/acl_endpoint_test.go
  nomad/structs/acl.go
Labels: type/enhancement, theme/auth

#15418 docs: clarify autoscaling factor and threshold for target-value plugin
  website/content/tools/autoscaling/plugins/strategy/target-value.mdx
Labels: backport/website, backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x
