Repository hashicorp/nomad, pull requests merged in 2022-01, with the labels that each got.

#11743 api: paginate deployment list and accept wildcard namespace
  .changelog/11743.txt
  nomad/deployment_endpoint.go
  nomad/deployment_endpoint_test.go
  website/content/api-docs/deployments.mdx
Labels: theme/api, theme/deployments

#11582 agent: support multiple http address in addresses.http
  command/agent/agent.go
  command/agent/agent_test.go
  command/agent/command.go
  command/agent/config.go
  command/agent/config_test.go
  command/agent/http.go
  command/agent/http_test.go
  command/agent/testagent.go
  website/content/docs/configuration/consul.mdx
Labels: stage/waiting-reply, theme/config

#11762 docs: add 1.2.0 HCLv2 strict parsing upgrade note.
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: type/bug, theme/docs, stage/accepted, backport/website, backport/1.2.2, backport/1.2.1, backport/1.2.0, backport/1.2.3

#11776 csi: reap unused volume claims at leadership transitions
  .changelog/11776.txt
  nomad/volumewatcher/volume_watcher.go
  nomad/volumewatcher/volumes_watcher_test.go
Labels: theme/storage

#11593 Make number of scheduler workers reloadable
  .changelog/11593.txt
  .tours/scheduler-worker---hot-reload.tour
  .tours/scheduler-worker---pause.tour
  .tours/scheduler-worker---unpause.tour
  .tours/scheduler-worker.tour
  GNUmakefile
  api/agent.go
  api/agent_test.go
  command/agent/agent_endpoint.go
  command/agent/agent_endpoint_test.go
  command/agent/http.go
  nomad/leader.go
  nomad/leader_test.go
  nomad/server.go
  nomad/server_test.go
  nomad/testing.go
  nomad/worker.go
  nomad/worker_string_schedulerworkerstatus.go
  nomad/worker_string_workerstatus.go
  nomad/worker_test.go
  website/content/api-docs/agent.mdx
Labels: type/enhancement, theme/scheduling

#10237 Emit metrics on reschedule later decisions as nomad.client.allocs.reschedule
  nomad/structs/structs.go
  scheduler/reconcile.go
Labels: type/enhancement, theme/metrics, stage/needs-discussion

#10236 Emit metrics for eval waitUntil as nomad.nomad.broker.eval_waiting
  nomad/eval_broker.go
Labels: type/enhancement, theme/metrics, stage/needs-discussion

#11788 CSI: tests to exercise csi_hook
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/csi_hook.go
  client/allocrunner/csi_hook_test.go
Labels: theme/storage

#11799 docs: note that clients need to have ACLs enabled
  website/content/docs/configuration/acl.mdx
Labels: theme/docs, backport/website, backport/1.2.2, backport/1.2.1, backport/1.2.0, backport/1.2.3

#11606 Expose Consul template configuration parameters
  .changelog/11606.txt
  api/tasks.go
  api/tasks_test.go
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  client/config/config.go
  client/config/config_test.go
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  command/agent/test-resources/client_with_template.hcl
  command/agent/test-resources/minimal_client.hcl
  jobspec2/parse_test.go
  jobspec2/test-fixtures/template-wait-config.hcl
  nomad/structs/diff.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  scheduler/util_test.go
  website/content/docs/configuration/client.mdx
  website/content/docs/job-specification/template.mdx
Labels: type/enhancement, theme/consul-template

#11783 Un-break templates when using vault stanza change_mode noop
  client/allocrunner/taskrunner/vault_hook.go
Labels: stage/needs-discussion

#11818 docs: improve changelog for PR #11783
  .changelog/11783.txt
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11817 Update alert-banner
  website/data/alert-banner.js
Labels: backport/website

#11830 agent: validate reserved_ports are valid
  .changelog/11830.txt
  command/agent/command.go
  command/agent/command_test.go
  nomad/structs/funcs.go
  nomad/structs/funcs_test.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11672 Fix ACL requirements for job details UI
  .changelog/11672.txt
  ui/app/abilities/client.js
  ui/app/components/job-page/abstract.js
  ui/app/components/job-page/parameterized-child.js
  ui/app/components/job-page/parts/job-client-status-summary.js
  ui/app/components/job-page/periodic-child.js
  ui/app/components/job-page/sysbatch.js
  ui/app/components/job-page/system.js
  ui/app/components/list-accordion/accordion-head.js
  ui/app/controllers/jobs/job/index.js
  ui/app/models/allocation.js
  ui/app/routes/jobs/job/index.js
  ui/app/templates/components/allocation-row.hbs
  ui/app/templates/components/job-page/parameterized-child.hbs
  ui/app/templates/components/job-page/parts/job-client-status-summary.hbs
  ui/app/templates/components/job-page/periodic-child.hbs
  ui/app/templates/components/job-page/sysbatch.hbs
  ui/app/templates/components/job-page/system.hbs
  ui/app/templates/components/job-subnav.hbs
  ui/app/templates/components/list-accordion/accordion-head.hbs
  ui/app/templates/components/task-row.hbs
  ui/app/templates/jobs/job/index.hbs
  ui/app/utils/properties/job-client-status.js
  ui/mirage/factories/allocation.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/integration/components/allocation-row-test.js
  ui/tests/pages/jobs/detail.js
  ui/tests/unit/abilities/client-test.js
  ui/tests/unit/utils/job-client-status-test.js
Labels: theme/ui

#11402 taskrunner: add clarifying initial vault token renew comment.
  client/allocrunner/taskrunner/vault_hook.go
Labels: type/enhancement, theme/docs, theme/vault

#11403 agent/docs: add better clarification when top-level data dir needs setting
  command/agent/command.go
  command/agent/command_test.go
  website/content/docs/configuration/server.mdx
Labels: type/enhancement, theme/docs, theme/cli

#11856 drivers: set world-readable permissions on copied resolv.conf
  .changelog/11856.txt
  drivers/shared/resolvconf/mount.go
Labels: theme/driver, backport/1.0, backport/1.1

#11854 freebsd: build fix for ARM7 32-bit
  .changelog/11854.txt
  command/agent/log_file_bsd.go
Labels: theme/platform-freebsd, backport/1.0, backport/1.1

#11853 csi: when warning for multiple prefix matches, use full ID
  .changelog/11853.txt
  command/volume_deregister.go
  command/volume_detach.go
Labels: theme/storage, backport/1.0, backport/1.1

#11852 csi: volume deregistration should require exact ID
  .changelog/11852.txt
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: theme/storage, backport/1.0, backport/1.1

#11793 scheduler: detect and log unexpected scheduling collisions
  nomad/fsm.go
  nomad/job_endpoint.go
  nomad/mock/mock.go
  nomad/plan_apply.go
  nomad/server.go
  nomad/structs/funcs.go
  nomad/structs/network.go
  nomad/structs/network_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  nomad/worker.go
  nomad/worker_test.go
  scheduler/context.go
  scheduler/context_test.go
  scheduler/generic_sched.go
  scheduler/generic_sched_test.go
  scheduler/rank.go
  scheduler/rank_test.go
  scheduler/scheduler.go
  scheduler/scheduler_sysbatch_test.go
  scheduler/scheduler_system.go
  scheduler/scheduler_system_test.go
  scheduler/testing.go
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11849 changelog: add entry for #11848
  .changelog/11848.txt
Labels: type/bug, theme/enterprise, stage/needs-backporting, stage/accepted, theme/ent/quotas, backport/1.0, backport/1.1

#11862 changelog: add entry for #11793
  .changelog/11793.txt
Labels: stage/needs-backporting, backport/1.0, backport/1.1

#11912 docs: Update volume create/register mount options to use []string example
  website/content/docs/commands/volume/create.mdx
  website/content/docs/commands/volume/register.mdx
Labels: theme/docs, backport/1.2.2, backport/1.2.1, backport/1.2.0, backport/1.2.3

#11891 CSI: update leader's ACL in volumewatcher
  .changelog/11891.txt
  nomad/leader.go
  nomad/volumewatcher/volumes_watcher.go
  nomad/volumewatcher/volumes_watcher_test.go
Labels: theme/storage, backport/1.1, backport/1.2

#11930 Update IsEmpty logic in finalizeClientTemplateConfig
  .changelog/11902.txt
  client/config/config.go
  command/agent/config_test.go
  command/agent/test-resources/client_with_basic_template.hcl
  command/agent/test-resources/client_with_basic_template.json
Labels: type/bug, stage/needs-backporting, backport/1.2

#11896 Fix for #11884: Move volume link to the source column and fix the link target
  .changelog/11896.txt
  ui/app/templates/allocations/allocation/task/index.hbs
Labels: backport/1.1, backport/1.2

#11940 docs: add `cores` to client reserved config block.
  website/content/docs/configuration/client.mdx
Labels: type/bug, theme/docs, stage/accepted, backport/1.1, backport/website, backport/1.2

#11890 CSI: resolve invalid claim states
  .changelog/11890.txt
  nomad/core_sched.go
  nomad/core_sched_test.go
  nomad/state/state_store.go
  nomad/state/testing.go
  nomad/volumewatcher/volume_watcher_test.go
  nomad/volumewatcher/volumes_watcher_test.go
  scheduler/feasible.go
Labels: theme/storage, backport/1.0, backport/1.1

#11892 CSI: node unmount from the client before unpublish RPC
  client/allocrunner/csi_hook.go
  client/allocrunner/csi_hook_test.go
  client/pluginmanager/csimanager/volume.go
Labels: theme/storage

#11941 website: Add Demandbase tag to consent manager
  website/lib/consent-manager-services/index.ts
  website/pages/_app.js
Labels: theme/website

#11944 core: prevent malformed plans from crashing leader
  nomad/plan_endpoint.go
  nomad/plan_endpoint_test.go
  nomad/structs/structs.go
Labels: stage/needs-backporting, backport/1.1, backport/1.2
