Repository hashicorp/nomad, pull requests merged in 2022-04, with the labels that each got.

#12304 fix: update incorrect DriverNetworkManager interface implementation
  drivers/mock/driver.go
  plugins/drivers/client.go
Labels: type/bug, theme/client, stage/accepted, backport/1.1, backport/1.2

#11938 command/operator_debug: add pprof interval
  .changelog/11938.txt
  command/operator_debug.go
  command/operator_debug_test.go
  website/content/docs/commands/operator/debug.mdx
Labels: type/enhancement, theme/cli

#12449 Support Vault entity aliases
  .changelog/12449.txt
  api/tasks.go
  api/tasks_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  go.mod
  go.sum
  helper/funcs.go
  helper/funcs_test.go
  jobspec/parse.go
  jobspec/parse_test.go
  jobspec/test-fixtures/basic.hcl
  nomad/job_endpoint.go
  nomad/job_endpoint_hook_vault.go
  nomad/job_endpoint_hook_vault_oss.go
  nomad/job_endpoint_hooks.go
  nomad/job_endpoint_oss.go
  nomad/job_endpoint_test.go
  nomad/node_endpoint.go
  nomad/structs/config/vault.go
  nomad/structs/config/vault_test.go
  nomad/structs/diff_test.go
  nomad/structs/funcs.go
  nomad/structs/funcs_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  nomad/structs/vault.go
  nomad/vault.go
  nomad/vault_test.go
  nomad/vault_testing.go
  website/content/docs/configuration/vault.mdx
  website/content/docs/integrations/vault-integration.mdx
  website/content/docs/job-specification/vault.mdx
Labels: theme/vault

#12466 docs: updates for CSI plugin improvements for 1.3.0
  website/content/docs/internals/plugins/csi.mdx
  website/content/docs/job-specification/csi_plugin.mdx
Labels: theme/docs, stage/needs-backporting, backport/1.1, backport/1.2

#12477 disconnected clients: Add changelog entry
  .changelog/12476.txt
Labels: theme/edge

#12492 api: use `cleanhttp.DefaultPooledTransport` for default API client
  .changelog/12492.txt
  api/api.go
  command/agent/http_test.go
Labels: type/enhancement, theme/api

#12495 plan_apply: Add missing unit test for validating plans for disconnected clients
  nomad/plan_apply_test.go
Labels: theme/edge

#12494 e2e: fix eventual consistency failure within consultemplate suite.
  e2e/consultemplate/consultemplate.go
Labels: type/bug, theme/e2e

#12514 docs: add nomad services template jobspec example.
  website/content/docs/job-specification/template.mdx
Labels: theme/docs, backport/website

#12517 add Nomad v1.3.0-beta.1 download box
  website/pages/downloads/index.jsx
Labels: backport/website

#12521 docs: fix upgrade specific broken link and conflict tag
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/website

#12524 docs: fixup title formatting in upgrade guide
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/website

#12554 fix data race in dynamic plugin registry tests
  client/dynamicplugins/registry_test.go
Labels: theme/testing

#12573 CSI: handle per-alloc volumes in `alloc status -verbose` CLI
  .changelog/12573.txt
  command/alloc_status.go
Labels: stage/needs-backporting, backport/1.1, backport/1.2

#12555 system_scheduler: support disconnected clients
  nomad/structs/structs.go
  scheduler/generic_sched.go
  scheduler/reconcile_util.go
  scheduler/scheduler_system.go
  scheduler/scheduler_system_test.go
  scheduler/util.go
  scheduler/util_test.go
Labels: theme/system-scheduler, theme/edge

#12559 heartbeat: Handle transitioning from disconnected to down
  nomad/heartbeat.go
  nomad/heartbeat_test.go
  nomad/node_endpoint.go
Labels: theme/heartbeating, theme/edge

#12584 CSI: fix volume status prefix matching in CLI
  command/volume_status_csi.go
Labels: theme/cli

#12583 CSI: replace structs->api with serialization extension
  command/agent/csi_endpoint.go
  command/agent/csi_endpoint_test.go
  nomad/structs/csi.go
  nomad/structs/extensions.go
Labels: theme/api, theme/storage, theme/tech-debt

#12594 CI: build binaries for UI branches
  .circleci/config.yml
Labels: theme/ui, theme/build-infrastructure

#12593 fix #12592
  .changelog/12593.txt
  nomad/structs/structs.go
Labels: type/bug, stage/needs-backporting, backport/1.1, backport/1.2

#12071 `consul-template`: revert `function_denylist` logic
  .changelog/12071.txt
  client/config/config.go
  command/agent/config.go
  command/agent/config_test.go
  command/agent/test-resources/client_with_empty_template.hcl
  command/agent/test-resources/client_with_function_denylist.hcl
  command/agent/test-resources/client_with_function_denylist_empty.hcl
  command/agent/test-resources/client_with_function_denylist_empty_string.hcl
  command/agent/test-resources/client_with_function_denylist_empty_string.json
  command/agent/test-resources/client_with_function_denylist_nil.hcl
Labels: type/bug

#12578 changelog: add entry for #11944
  .changelog/11944.txt
Labels: stage/needs-backporting, backport/1.1, backport/1.2

#12671 E2E: provide options for reverse proxy for web UI
  e2e/terraform/README.md
  e2e/terraform/network.tf
  e2e/terraform/provision-nomad/install-linux.tf
  e2e/terraform/provision-nomad/main.tf
  e2e/terraform/tls_client.tf
  e2e/ui/input/proxy.nomad
Labels: type/enhancement, theme/testing

#11531 Add Concurrent Download Support for artifacts
  .changelog/11531.txt
  client/allocrunner/taskrunner/artifact_hook.go
  client/allocrunner/taskrunner/artifact_hook_test.go
Labels: stage/waiting-reply, theme/artifact

#12539 reconciler: Handle canaries when client disconnects
  nomad/heartbeat.go
  nomad/node_endpoint.go
  nomad/plan_apply.go
  nomad/structs/structs.go
  scheduler/reconcile.go
  scheduler/reconcile_test.go
  scheduler/reconcile_util.go
  scheduler/reconcile_util_test.go
Labels: theme/edge

#12733 docs: fix broken link from `template` to client config
  website/content/docs/job-specification/template.mdx
Labels: theme/docs, backport/1.2.x

#12732 E2E: set longer timeout for CSI plugin alloc start
  e2e/csi/csi.go
  e2e/csi/ebs.go
  e2e/csi/efs.go
Labels: theme/testing

#12735 docker: back out cgroup v2 OOM detection
  drivers/docker/handle.go
Labels: type/bug, theme/driver/docker

#12738 cli: detect directory when applying namespace spec file
  command/namespace_apply.go
  website/content/docs/commands/namespace/apply.mdx
Labels: type/bug, theme/cli

#12621 E2E: fix debug logging on disconnected clients test
  e2e/disconnectedclients/disconnectedclients_test.go
Labels: theme/testing

#12751 CSI: handle nil topologies safely in command line
  command/volume_status_csi.go
Labels: type/bug, theme/storage

#12720 services: enable setting arbitrary address value in service registrations
  .changelog/12720.txt
  api/services.go
  client/serviceregistration/address.go
  client/serviceregistration/address_test.go
  client/serviceregistration/nsd/nsd.go
  client/taskenv/services.go
  client/taskenv/services_test.go
  command/agent/consul/service_client.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  command/service_info.go
  command/service_info_test.go
  nomad/structs/diff_test.go
  nomad/structs/services.go
  nomad/structs/services_test.go
  nomad/structs/structs_test.go
  website/content/docs/job-specification/service.mdx
Labels: theme/service-discovery

#12544 [ui] Disconnected Clients: "Unknown" allocations in the UI
  ui/app/components/allocation-status-bar.js
  ui/app/components/job-client-status-bar.js
  ui/app/components/job-client-status-row.js
  ui/app/controllers/clients/client/index.js
  ui/app/controllers/clients/index.js
  ui/app/controllers/jobs/job/allocations.js
  ui/app/controllers/jobs/job/clients.js
  ui/app/controllers/jobs/job/task-group.js
  ui/app/models/allocation.js
  ui/app/models/job-summary.js
  ui/app/models/job.js
  ui/app/models/task-group-summary.js
  ui/app/styles/charts/colors.scss
  ui/app/styles/charts/distribution-bar.scss
  ui/app/styles/components/status-text.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/core/variables.scss
  ui/app/utils/properties/job-client-status.js
  ui/mirage/factories/job-summary.js
  ui/tests/acceptance/client-detail-test.js
  ui/tests/acceptance/clients-list-test.js
  ui/tests/acceptance/job-allocations-test.js
  ui/tests/acceptance/job-clients-test.js
  ui/tests/acceptance/task-group-detail-test.js
  ui/tests/integration/components/job-client-status-bar-test.js
  ui/tests/unit/models/job-test.js
  ui/tests/unit/utils/job-client-status-test.js
Labels: theme/ui

#12752 CSI: plugin supervisor prestart should not mark itself done
  .changelog/12752.txt
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
Labels: theme/storage, backport/1.1.x, backport/1.2.x

#12774 CSI: plugin config updates should always be destructive
  .changelog/12774.txt
  scheduler/util.go
Labels: theme/storage, backport/1.1.x, backport/1.2.x

#12785 CSI: enforce one plugin supervisor loop via `sync.Once`
  client/allocrunner/taskrunner/plugin_supervisor_hook.go
Labels: theme/storage

#12787 E2E: remove old CLI for driving provisioning
  e2e/cli/command/environment.go
  e2e/cli/command/meta.go
  e2e/cli/command/provision.go
  e2e/cli/command/run.go
  e2e/cli/command/test_decoder.go
  e2e/cli/command/util.go
  e2e/cli/environments/mock/mock/main.tf
  e2e/cli/environments/mock/mock/terraform.tfvars
  e2e/cli/main.go
  go.mod
Labels: theme/cleanup, theme/testing

#12788 E2E: move volume mounts test to use golang's stdlib test runner
  e2e/e2e_test.go
  e2e/volumes/doc.go
  e2e/volumes/volumes.go
  e2e/volumes/volumes_test.go
Labels: theme/cleanup, theme/testing

#12795 e2e: Wait for deployment to finish before disconnect
  e2e/disconnectedclients/disconnectedclients_test.go
  e2e/e2eutil/input/disconnect-node.nomad
  e2e/e2eutil/input/restart-node.nomad
Labels: type/bug, theme/e2e, theme/edge

#12781 ci: setup release process with CRT
  .github/workflows/build-trigger.yml
  .github/workflows/build.yml
  .github/workflows/generate-static-assets.yml
  .github/workflows/release.yml
  .release/ci.hcl
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x

#12807 debug: add version constraint to avoid pprof panic
  .changelog/12807.txt
  command/operator_debug.go
  command/operator_debug_test.go
Labels: theme/cli

#12801 docs: Add known limitations callouts to Max Client Disconnect section
  website/content/docs/job-specification/group.mdx
Labels: theme/docs, theme/edge

#12825 docs: clarify `capacity_min/max` for volumes
  website/content/docs/commands/volume/create.mdx
Labels: theme/docs, theme/storage, backport/1.1.x, backport/1.2.x

#12828 ci: remove unused CircleCI Makefile
  .circleci/Makefile
Labels: backport/1.1.x, backport/1.2.x
