Repository hashicorp/nomad, pull requests merged in 2022-12, with the labels that each got.

#15168 [docs] Update affinity.mdx
  website/content/docs/job-specification/affinity.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15430 provide `RPCContext` to all RPC handlers
  nomad/acl_endpoint.go
  nomad/alloc_endpoint.go
  nomad/client_agent_endpoint.go
  nomad/client_alloc_endpoint.go
  nomad/client_csi_endpoint.go
  nomad/client_fs_endpoint.go
  nomad/client_stats_endpoint.go
  nomad/csi_endpoint.go
  nomad/deployment_endpoint.go
  nomad/endpoints_oss.go
  nomad/eval_endpoint.go
  nomad/event_endpoint.go
  nomad/job_endpoint.go
  nomad/job_endpoint_hook_connect_test.go
  nomad/keyring_endpoint.go
  nomad/namespace_endpoint.go
  nomad/node_endpoint.go
  nomad/operator_endpoint.go
  nomad/periodic_endpoint.go
  nomad/plan_endpoint.go
  nomad/regions_endpoint.go
  nomad/scaling_endpoint.go
  nomad/search_endpoint.go
  nomad/server.go
  nomad/service_registration_endpoint.go
  nomad/status_endpoint.go
  nomad/system_endpoint.go
  nomad/variables_endpoint.go
Labels: type/enhancement, theme/tech-debt

#15448 docs: update `plugin status` docs with capabilities and topology
  website/content/docs/commands/plugin/status.mdx
Labels: theme/docs, theme/storage, backport/1.3.x, backport/1.4.x

#15451 remove most static RPC handlers
  nomad/client_csi_endpoint_test.go
  nomad/csi_endpoint_test.go
  nomad/heartbeat.go
  nomad/node_endpoint_test.go
  nomad/server.go
  nomad/variables_endpoint_test.go
Labels: theme/tech-debt

#15454 [ui] Add namespaces to exec window
  .changelog/15454.txt
  ui/app/controllers/exec.js
Labels: backport/1.4.x

#15458 [ui] Adding canary_tags the web UI
  .changelog/15458.txt
  ui/app/components/allocation-service-sidebar.hbs
  ui/app/models/service-fragment.js
  ui/app/models/service.js
  ui/app/styles/core/tag.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/components/job-service-row.hbs
Labels: backport/1.4.x

#15417 Pre forwarding authentication
  .semgrep/rpc_endpoint.yml
  helper/tlsutil/testdata/nomad-foo-client-key.pem
  helper/tlsutil/testdata/nomad-foo-client.pem
  nomad/acl.go
  nomad/acl_endpoint.go
  nomad/acl_test.go
  nomad/namespace_endpoint.go
  nomad/rpc_test.go
  nomad/structs/acl.go
  nomad/structs/errors.go
  nomad/structs/structs.go
Labels: type/enhancement, theme/auth

#15499 pointer: add Merge helper function for merging pointers
  helper/pointer/pointer.go
  helper/pointer/pointer_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15485 docs: clarify rescheduling happens when tasks fail
  website/content/docs/job-specification/reschedule.mdx
Labels: theme/docs, backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#14630 [CI-only] Update build trigger to run on pushes to main and the release branches
  .github/workflows/build.yml
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15435 [ui] Token management interface on policy pages
  .changelog/15435.txt
  ui/app/abilities/token.js
  ui/app/adapters/token.js
  ui/app/components/policy-editor.js
  ui/app/components/tooltip.js
  ui/app/controllers/policies/index.js
  ui/app/controllers/policies/policy.js
  ui/app/routes/policies.js
  ui/app/routes/policies/policy.js
  ui/app/styles/components/policies.scss
  ui/app/templates/policies/index.hbs
  ui/app/templates/policies/policy.hbs
  ui/mirage/config.js
  ui/mirage/factories/token.js
  ui/tests/acceptance/policies-test.js
  ui/tests/acceptance/token-test.js
  ui/tests/unit/abilities/token-test.js
Labels: theme/ui, theme/auth

#12582 command/job_stop: accept multiple jobs, stop concurrently
  .changelog/12582.txt
  command/job_stop.go
  command/job_stop_test.go
  website/content/docs/commands/job/stop.mdx
Labels: theme/cli
