Repository hashicorp/nomad, pull requests merged in 2022-08, with the labels that each got.

#13934 e2e: move `namespaces` test out of legacy framework
  e2e/e2e_test.go
  e2e/namespaces/doc.go
  e2e/namespaces/namespaces.go
  e2e/namespaces/namespaces_test.go
Labels: theme/e2e

#13952 docs: fix path for quota/usage API
  website/content/api-docs/quotas.mdx
Labels: theme/docs, backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13956 build: update to go1.18.5
  .circleci/config.yml
  .github/workflows/test-core.yaml
  .go-version
  contributing/README.md
  scripts/release/mac-remote-build
  scripts/vagrant-linux-priv-go.sh
Labels: backport/1.2.x, backport/1.3.x

#13951 secure vars: enforce ENT quotas (OSS work)
  api/quota.go
  command/agent/search_endpoint_test.go
  command/quota_apply.go
  command/quota_init.go
  command/quota_status.go
  nomad/secure_variables_endpoint.go
  nomad/secure_variables_endpoint_oss.go
  nomad/state/state_store_secure_variables.go
  nomad/state/state_store_secure_variables_oss.go
  nomad/state/state_store_secure_variables_test.go
  nomad/structs/secure_variables.go
  website/content/api-docs/quotas.mdx
Labels: type/enhancement, theme/secure-variables

#13764 docs: concepts for secure variables and workload identity
  website/content/docs/concepts/secure-variables.mdx
  website/content/docs/concepts/security.mdx
  website/content/docs/concepts/workload-identity.mdx
  website/content/docs/operations/key-management.mdx
  website/content/docs/other-specifications/acl-policy.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, theme/secure-variables

#13938 cli: do not import structs, use API package only.
  GNUmakefile
  api/allocations.go
  api/api.go
  api/csi.go
  api/deployments.go
  api/evaluations.go
  api/jobs.go
  command/alloc_status.go
  command/deployment_status.go
  command/job_status.go
  command/job_validate.go
  command/monitor.go
  command/node_status.go
  command/operator_debug.go
  command/volume_status_csi.go
Labels: backport/1.3.x

#13755 client: enable specifying user/group permissions in the template stanza
  .changelog/13755.txt
  api/jobs_test.go
  api/tasks.go
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/helper.go
  jobspec/helper_test.go
  jobspec/parse_task.go
  jobspec/parse_test.go
  jobspec/test-fixtures/basic.hcl
  jobspec2/helper_test.go
  jobspec2/parse_job.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  website/content/api-docs/json-jobs.mdx
  website/content/docs/job-specification/template.mdx
Labels: theme/template, backport/1.3.x

#13670 ui: fix zero memory utilization bug on systems using cgroups v2
  .changelog/13670.txt
  ui/app/utils/classes/allocation-stats-tracker.js
  ui/tests/unit/utils/allocation-stats-tracker-test.js
Labels: backport/1.3.x

#13907 Add Nomad RetryConfig to agent template config
  .changelog/13907.txt
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  client/config/config.go
  command/agent/config_parse.go
  command/agent/config_test.go
  command/agent/test-resources/client_with_template.hcl
  go.mod
  go.sum
  website/content/docs/configuration/client.mdx
Labels: theme/consul-template, backport/1.3.x

#13999 docs: remove link to HCL2 `timestamp` function
  website/content/docs/job-specification/hcl2/functions/datetime/formatdate.mdx
Labels: backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#14000 qemu: restore monitor socket path
  .changelog/14000.txt
  drivers/qemu/driver.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14001 allow unhealthy canaries without blocking autopromote
  .changelog/14001.txt
  nomad/deploymentwatcher/deployment_watcher.go
  nomad/deploymentwatcher/deployments_watcher_test.go
Labels: backport/1.3.x

#13971 qemu: reduce monitor socket path
  .changelog/13971.txt
  drivers/qemu/driver.go
  drivers/qemu/driver_bsd.go
  drivers/qemu/driver_fallback.go
  drivers/qemu/driver_linux.go
  drivers/qemu/driver_test.go
  go.mod
  go.sum
  website/content/docs/drivers/qemu.mdx
Labels: backport/1.3.x

#14027 api: use errors.New not fmt.Errorf when error doesn't have format.
  .semgrep/api_errorf.yml
  api/acl.go
  api/allocations.go
  api/api.go
  api/api_test.go
  api/fs_test.go
  api/internal/testutil/freeport/freeport.go
  api/ioutil.go
  api/ioutil_test.go
  api/jobs.go
  api/sentinel.go
Labels: backport/1.3.x

#14032 Sweep of docs for repeated words; minor edits
  website/content/api-docs/evaluations.mdx
  website/content/docs/commands/alloc/stop.mdx
  website/content/docs/commands/deployment/resume.mdx
  website/content/docs/commands/job/run.mdx
  website/content/docs/commands/job/stop.mdx
  website/content/docs/commands/volume/snapshot-list.mdx
  website/content/docs/concepts/plugins/csi.mdx
  website/content/docs/job-specification/hcl2/functions/datetime/formatdate.mdx
  website/content/docs/job-specification/multiregion.mdx
  website/content/docs/job-specification/restart.mdx
  website/content/docs/job-specification/spread.mdx
  website/content/docs/operations/key-management.mdx
  website/content/partials/envvars.mdx
  website/content/plugins/devices/nvidia.mdx
  website/content/plugins/drivers/podman.mdx
  website/content/tools/autoscaling/agent/apm.mdx
  website/content/tools/autoscaling/agent/strategy.mdx
  website/content/tools/autoscaling/agent/target.mdx
Labels: theme/docs, backport/website

#14077 template doc typo fix
  website/content/docs/job-specification/template.mdx
Labels: backport/website

#14070 ci: delete generated files after build
  .github/workflows/release.yml
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14091 docs: correctly state RPC port is used by servers and clients.
  website/content/docs/concepts/security.mdx
Labels: backport/website, backport/1.3.x

#14088 cli: support vault token in plan command
  .changelog/14088.txt
  command/job_plan.go
  command/job_plan_test.go
  website/content/docs/commands/job/plan.mdx
Labels: backport/1.3.x

#14099 Error typed changed to dismissable global toast
  ui/app/controllers/variables/variable/index.js
  ui/app/templates/variables/variable/index.hbs
Labels: theme/secure-variables

#14040 Add notes about DAS being prometheus only
  website/content/tools/autoscaling/agent/dynamic_application_sizing.mdx
  website/content/tools/autoscaling/plugins/target/app-sizing-nomad.mdx
Labels: backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13922 move secure variable conflict resolution to state store
  command/agent/search_endpoint_test.go
  command/agent/secure_variable_endpoint.go
  command/agent/secure_variable_endpoint_test.go
  helper/raftutil/msgtypes.go
  nomad/core_sched.go
  nomad/core_sched_test.go
  nomad/fsm.go
  nomad/fsm_test.go
  nomad/secure_variables_endpoint.go
  nomad/secure_variables_endpoint_test.go
  nomad/state/state_store_secure_variables.go
  nomad/state/state_store_secure_variables_oss.go
  nomad/state/state_store_secure_variables_test.go
  nomad/state/state_store_test.go
  nomad/structs/secure_variables.go
  nomad/structs/structs.go
Labels: theme/secure-variables

#13820 SV CLI: var init
  command/commands.go
  command/var_init.go
  go.mod
  go.sum
Labels: theme/cli, theme/secure-variables

#14122 api: document warnings for setting `api.ClientConnTimeout`
  api/allocations.go
  api/api.go
  api/fs.go
Labels: theme/docs, theme/api, theme/allocation API

#14123 ACL: disallow missing `path` in secure variable policy
  acl/policy.go
  acl/policy_test.go
Labels: theme/auth, theme/secure-variables

#14118 adds link for Nomad-Pack GitHub action
  website/content/tools/index.mdx
Labels: backport/website

#14144 ui: fix ability checking when anon policy is missing namespace
  ui/app/abilities/job.js
  ui/app/abilities/variable.js
Labels: theme/ui

#14145 api: trim space of error response output
  .changelog/14145.txt
  GNUmakefile
  api/api.go
Labels: backport/1.2.x, backport/1.3.x

#14129 changelog: add missing entry for #13539
  .changelog/13539.txt
  CHANGELOG.md
Labels: backport/1.3.x

#14187 build: print installed go version in cricle on windows
  .circleci/config.yml
Labels: backport/1.2.x, backport/1.3.x

#14171 sentinel: add support for Nomad ACL Token and Namespace
  .changelog/14171.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_oss.go
Labels: type/enhancement, theme/enterprise

#14203 template: use pointer values for gid and uid
  .changelog/14203.txt
  api/jobs_test.go
  api/tasks.go
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/helper.go
  jobspec/helper_test.go
  jobspec/parse_task.go
  jobspec/parse_test.go
  jobspec2/helper_test.go
  jobspec2/parse_job.go
  nomad/structs/diff.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  website/content/docs/job-specification/template.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/1.3.x

#14205 SV: Make GetSecureVariable a blocking query
  nomad/secure_variables_endpoint_test.go
  nomad/state/state_store_secure_variables.go
Labels: type/bug, theme/secure-variables

#14140 allow ACL policies to be associated with workload identity
  .changelog/14140.txt
  api/acl.go
  command/acl_bootstrap.go
  command/acl_policy_apply.go
  command/acl_policy_info.go
  nomad/acl.go
  nomad/acl_test.go
  nomad/secure_variables_endpoint_test.go
  nomad/state/schema.go
  nomad/state/state_store.go
  nomad/structs/structs.go
  website/content/docs/commands/acl/policy-apply.mdx
  website/content/docs/commands/acl/policy-info.mdx
  website/content/docs/concepts/secure-variables.mdx
  website/content/docs/concepts/workload-identity.mdx
Labels: theme/secure-variables

#14009 allocrunner: refactor task coordinator
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/task_hook_coordinator.go
  client/allocrunner/task_hook_coordinator_test.go
  client/allocrunner/tasklifecycle/coordinator.go
  client/allocrunner/tasklifecycle/coordinator_test.go
  client/allocrunner/tasklifecycle/doc.go
  client/allocrunner/tasklifecycle/gate.go
  client/allocrunner/tasklifecycle/gate_test.go
  client/allocrunner/tasklifecycle/testing.go
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/task_runner_test.go
  command/agent/consul/int_test.go
  nomad/job_endpoint_validators_test.go
  nomad/mock/mock.go
  nomad/structs/structs.go
Labels: backport/1.3.x

#14232 ci: fix gofmt on tasklifecycle
  client/allocrunner/tasklifecycle/doc.go
Labels: backport/1.3.x

#14224 ui: use task state to determine if task is active
  .changelog/14224.txt
  ui/app/models/task-state.js
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/acceptance/exec-test.js
  ui/tests/acceptance/task-detail-test.js
  ui/tests/pages/allocations/detail.js
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14248 build: set osusergo build tag by default
  .changelog/14248.txt
  GNUmakefile
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14212 docs: Update upgrade guide to reflect enterprise changes introduced in nomad-enterprise
  .changelog/14212.txt
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/1.3.x

#14269 deps: sync versions of go-discover in go.mod
  go.mod
  go.sum
Labels: backport/1.3.x

#13972 template: custom change_mode scripts
  .changelog/13972.txt
  api/tasks.go
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  client/allocrunner/taskrunner/template_hook.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/parse_task.go
  jobspec/parse_test.go
  jobspec/test-fixtures/basic.hcl
  jobspec2/hcl_conversions.go
  jobspec2/parse_job.go
  jobspec2/parse_test.go
  nomad/structs/diff.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  website/content/api-docs/json-jobs.mdx
  website/content/docs/job-specification/change_script.mdx
  website/content/docs/job-specification/template.mdx
  website/data/docs-nav-data.json
Labels: theme/template, backport/1.3.x

#14297 client/logmon: acquire executable in init block
  .changelog/14297.txt
  client/logmon/plugin.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14283 drivers/java: add parsing test case for corretto 17
  drivers/java/utils_test.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14298 vault: detect namespace change in config reload
  .changelog/14298.txt
  command/agent/agent_test.go
  nomad/server_test.go
  nomad/structs/config/vault.go
  nomad/structs/config/vault_test.go
  nomad/vault.go
  nomad/vault_testing.go
Labels: type/bug, theme/vault, backport/1.1.x, backport/1.2.x, backport/1.3.x

#14127 Task lifecycle restart
  .changelog/14127.txt
  api/allocations.go
  client/alloc_endpoint.go
  client/alloc_endpoint_test.go
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/alloc_runner_unix_test.go
  client/allocrunner/tasklifecycle/coordinator.go
  client/allocrunner/tasklifecycle/coordinator_test.go
  client/allocrunner/taskrunner/lifecycle.go
  client/allocrunner/taskrunner/sids_hook_test.go
  client/allocrunner/taskrunner/state/state.go
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/task_runner_test.go
  client/allocrunner/testing.go
  client/client.go
  command/agent/alloc_endpoint.go
  command/alloc_restart.go
  nomad/mock/mock.go
  nomad/structs/structs.go
  website/content/api-docs/allocations.mdx
  website/content/docs/commands/alloc/restart.mdx
Labels: backport/1.3.x

#14223 ui: task lifecycle restart all tasks
  .changelog/14223.txt
  ui/app/adapters/allocation.js
  ui/app/components/lifecycle-chart-row.js
  ui/app/controllers/allocations/allocation/index.js
  ui/app/models/allocation.js
  ui/app/templates/allocations/allocation/index.hbs
  ui/tests/acceptance/allocation-detail-test.js
  ui/tests/integration/components/lifecycle-chart-test.js
  ui/tests/pages/allocations/detail.js
Labels: backport/1.3.x

#14230 client: refactor cpuset manager initialization
  .changelog/14230.txt
  client/client.go
  client/client_test.go
  client/lib/cgutil/cgutil_linux.go
  client/lib/cgutil/cgutil_linux_test.go
  client/lib/cgutil/cgutil_noop.go
  client/lib/cgutil/cpuset_manager.go
  client/lib/cgutil/cpuset_manager_v1.go
  client/lib/cgutil/cpuset_manager_v1_test.go
  client/lib/cgutil/cpuset_manager_v2.go
  client/lib/cgutil/cpuset_manager_v2_test.go
Labels: backport/1.3.x

#14325 SV API: return upserted variable to caller
  api/secure_variables.go
  api/secure_variables_test.go
  command/agent/secure_variable_endpoint.go
  command/agent/secure_variable_endpoint_test.go
Labels: type/enhancement, theme/api, theme/secure-variables

#14226 Nomad Services: job routes, model, and serializer updates
  ui/app/adapters/service.js
  ui/app/adapters/watchable.js
  ui/app/components/job-service-row.js
  ui/app/controllers/allocations/allocation/index.js
  ui/app/controllers/jobs/job/services.js
  ui/app/controllers/jobs/job/services/index.js
  ui/app/controllers/jobs/job/services/service.js
  ui/app/models/job.js
  ui/app/models/service-fragment.js
  ui/app/models/service.js
  ui/app/models/task-group.js
  ui/app/models/task.js
  ui/app/router.js
  ui/app/routes/jobs/job/services.js
  ui/app/routes/jobs/job/services/index.js
  ui/app/routes/jobs/job/services/service.js
  ui/app/serializers/job.js
  ui/app/serializers/service-fragment.js
  ui/app/serializers/service.js
  ui/app/styles/components.scss
  ui/app/styles/components/services.scss
  ui/app/templates/components/job-service-row.hbs
  ui/app/templates/components/job-subnav.hbs
  ui/app/templates/jobs/job/services.hbs
  ui/app/templates/jobs/job/services/index.hbs
  ui/app/templates/jobs/job/services/service.hbs
  ui/app/utils/properties/watch.js
  ui/mirage/config.js
  ui/tests/acceptance/keyboard-test.js
  ui/tests/acceptance/regions-test.js
  ui/tests/pages/jobs/job/services.js
  ui/tests/unit/adapters/service-test.js
  ui/tests/unit/controllers/jobs/job/services-test.js
  ui/tests/unit/controllers/jobs/job/services/index-test.js
  ui/tests/unit/controllers/jobs/job/services/service-test.js
  ui/tests/unit/models/service-fragment-test.js
  ui/tests/unit/routes/jobs/job/services/index-test.js
  ui/tests/unit/routes/jobs/job/services/service-test.js
  ui/tests/unit/serializers/service-test.js
Labels: theme/ui, theme/service-discovery

#14318 cleanup: create pointer.Compare helper function
  helper/funcs.go
  helper/funcs_test.go
  helper/pointer/pointer.go
  helper/pointer/pointer_test.go
  nomad/structs/services.go
Labels: backport/1.2.x, backport/1.3.x

#14333 cli: force periodic job if its id equals search prefix (#14116)
  .changelog/14333.txt
  command/job_periodic_force.go
  command/job_periodic_force_test.go
Labels: type/bug, theme/cli, backport/1.1.x, backport/1.2.x, backport/1.3.x

#12953 consul: allow stale namespace results
  .changelog/12953.txt
  command/agent/consul/namespaces_client.go
Labels: backport/1.2.x, backport/1.3.x

#14374 bugfix: fixed template validation panic in case of incorrect ChangeScript configuration
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: theme/template, backport/1.3.x

#14383 [ui] Variables Rename
  ui/app/abilities/variable.js
  ui/app/components/variable-form.hbs
  ui/app/components/variable-form.js
  ui/app/components/variable-form/input-group.hbs
  ui/app/components/variable-form/input-group.js
  ui/app/components/variable-form/namespace-filter.hbs
  ui/app/components/variable-form/namespace-filter.js
  ui/app/components/variable-form/related-entities.hbs
  ui/app/controllers/variables/variable/index.js
  ui/app/models/variable.js
  ui/app/styles/components.scss
  ui/app/styles/components/variables.scss
  ui/app/templates/variables.hbs
  ui/app/templates/variables/index.hbs
  ui/app/templates/variables/new.hbs
  ui/app/templates/variables/path.hbs
  ui/app/templates/variables/variable.hbs
  ui/app/templates/variables/variable/edit.hbs
  ui/app/templates/variables/variable/index.hbs
  ui/app/utils/path-tree.js
  ui/mirage/config.js
  ui/mirage/factories/token.js
  ui/tests/acceptance/variables-test.js
  ui/tests/integration/components/variable-form-test.js
  ui/tests/integration/components/variable-paths-test.js
  ui/tests/unit/abilities/abstract-test.js
  ui/tests/unit/abilities/variable-test.js
  ui/tests/unit/utils/path-tree-test.js
Labels: theme/variables

#14368 docs: template change script example correction
  website/content/docs/job-specification/change_script.mdx
Labels: backport/website, backport/1.3.x

#14290 cleanup: tidy up helper package some more
  client/allocrunner/taskrunner/getter/getter_test.go
  client/client.go
  client/taskenv/env.go
  command/agent/agent.go
  command/operator_debug.go
  helper/escapingfs/escapes.go
  helper/escapingfs/escapes_test.go
  helper/funcs.go
  helper/funcs_test.go
  helper/math.go
  helper/path.go
  nomad/blocked_evals.go
  nomad/server.go
Labels: backport/1.2.x, backport/1.3.x

#14385 cgroups: refactor v2 kill path to use cgroups.kill interface file
  .changelog/14371.txt
  client/lib/cgutil/editor.go
  client/lib/cgutil/editor_test.go
  client/lib/cgutil/group_killer.go
Labels: backport/1.3.x

#14397 search: enforce correct ACL for search over variables
  command/agent/search_endpoint_test.go
  nomad/search_endpoint.go
Labels: type/bug, theme/variables

#14405 testing: setting env var incompatible with parallel tests
  api/api_test.go
  client/allocrunner/taskrunner/template/template_test.go
  client/fingerprint/env_azure_test.go
  client/fingerprint/env_digitalocean_test.go
  client/fingerprint/env_gce_test.go
  command/agent/host/host_test.go
  command/helpers_test.go
  command/job_plan_test.go
  command/job_validate_test.go
  command/meta_test.go
  command/ui_test.go
  drivers/docker/driver_darwin_test.go
  drivers/docker/driver_linux_test.go
Labels: type/bug, theme/testing

#14399 Vars: Update CT dependency to support variables.
  client/allocrunner/taskrunner/connect_native_hook_test.go
  client/allocrunner/taskrunner/template/template_test.go
  command/agent/consul/group_test.go
  command/agent/consul/int_test.go
  command/operator_debug_test.go
  go.mod
  go.sum
Labels: type/enhancement, theme/template, theme/consul-template, theme/variables

#14407 ci: fix TestNomad_BootstrapExpect_NonVoter test
  nomad/serf_test.go
Labels: backport/1.3.x

#14416 changelog: add entry for #14381
  .changelog/14381.txt
Labels: backport/1.3.x

#14419 changelog: add entry for #14374
  .changelog/14374.txt
Labels: backport/1.3.x
