Repository hashicorp/nomad, pull requests merged in 2022-09, with the labels that each got.

#14356 Update ephemeral_disk.mdx to explain how to use the ephemeral disk
  website/content/docs/job-specification/ephemeral_disk.mdx
Labels: backport/website, backport/1.3.x

#14434 docs: clarify CSI plugin compatibility
  website/content/docs/concepts/plugins/csi.mdx
Labels: theme/docs, theme/storage, backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#14426 cli: set -hcl2-strict to false if -hcl1 is defined
  .changelog/14426.txt
  command/job_plan.go
  command/job_plan_test.go
  command/job_run.go
  command/job_run_test.go
  command/job_validate.go
  command/job_validate_test.go
  website/content/docs/commands/job/plan.mdx
  website/content/docs/commands/job/run.mdx
  website/content/docs/commands/job/validate.mdx
Labels: backport/1.3.x

#14441 migrate autopilot implementation to raft-autopilot
  .changelog/14441.txt
  command/agent/operator_endpoint.go
  go.mod
  go.sum
  nomad/autopilot.go
  nomad/autopilot_oss.go
  nomad/autopilot_test.go
  nomad/leader.go
  nomad/leader_test.go
  nomad/operator_endpoint.go
  nomad/serf.go
  nomad/server.go
  nomad/server_setup_oss.go
  nomad/stats_fetcher.go
  nomad/stats_fetcher_test.go
  nomad/status_endpoint.go
  nomad/structs/autopilot.go
Labels: theme/autopilot

#14443 docs: add warning about changing region config
  website/content/docs/configuration/index.mdx
Labels: backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#14071 [ui] Show a different message when there are no tasks in a job
  .changelog/14071.txt
  ui/app/controllers/exec.js
Labels: backport/1.3.x

#13103 warn destructive update only when count > 1
  .changelog/13103.txt
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: backport/1.3.x

#14457 ui: remove extra space in menu footer
  .changelog/14457.txt
  ui/app/templates/components/gutter-menu.hbs
Labels: theme/ui, backport/1.3.x

#14485 docs: add quota panic fix changelog entry
  .changelog/_839.txt
Labels: backport/1.2.x, backport/1.3.x

#14496 test: fix concurrent map access in `TestStatsFetcher`
  nomad/stats_fetcher_test.go
Labels: theme/testing

#14497 helper: guard against negative inputs into random stagger
  .changelog/14497.txt
  helper/cluster.go
  helper/cluster_test.go
Labels: backport/1.2.x, backport/1.3.x

#14499 test: fix concurrent map access in `TestStatsFetcher`
  nomad/stats_fetcher_test.go
Labels: theme/testing

#14502 test: fix concurrent map access in `TestStatsFetcher`
  nomad/stats_fetcher_test.go
Labels: theme/testing

#14484 CSI: failed allocation should not block its own controller unpublish
  .changelog/14484.txt
  api/csi.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/structs/csi.go
  website/content/api-docs/volumes.mdx
Labels: type/bug, theme/storage, backport/1.1.x, backport/1.2.x, backport/1.3.x

#14483 Add client scheduling eligibility to heartbeat
  .changelog/14483.txt
  client/client.go
  nomad/node_endpoint.go
  nomad/structs/structs.go
Labels: type/bug, theme/metrics, stage/accepted

#14514 remove root keyring install API
  api/keyring.go
  api/keyring_test.go
  command/agent/keyring_endpoint.go
  command/agent/keyring_endpoint_test.go
  command/commands.go
  command/operator_root_keyring.go
  command/operator_root_keyring_install.go
  website/content/docs/commands/operator/root/keyring-install.mdx
  website/data/docs-nav-data.json
Labels: theme/variables

#14528 CI: make `make check` clean on macOS
  client/fingerprint/cgroup.go
  client/fingerprint/cgroup_linux.go
  client/lib/cgutil/cpuset_manager.go
  client/lib/cgutil/cpuset_manager_v2.go
Labels: theme/testing

#14400 Vars: CLI commands for get, put, purge [wip]
  api/variables.go
  command/commands.go
  command/var.go
  command/var_get.go
  command/var_get_test.go
  command/var_init.go
  command/var_init_test.go
  command/var_list.go
  command/var_list_test.go
  command/var_purge.go
  command/var_purge_test.go
  command/var_put.go
  command/var_put_test.go
  command/var_test.go
  nomad/variables_endpoint.go
Labels: type/enhancement, theme/cli, theme/variables

#14519 job_endpoint: check spec for all regions
  .changelog/14519.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_oss.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14550 [vars] Make `var list` flags match other var commands
  command/var.go
  command/var_list.go
  command/var_list_test.go
Labels: theme/cli, theme/variables

#14527 docs: update `template` for Nomad Variables
  website/content/docs/job-specification/template.mdx
Labels: theme/docs, theme/template, theme/variables

#14547 variables: restrict allowed paths for variables
  nomad/structs/variables.go
  nomad/structs/variables_test.go
Labels: theme/variables

#14249 Variables CLI documentation
  website/content/docs/commands/var/get.mdx
  website/content/docs/commands/var/index.mdx
  website/content/docs/commands/var/init.mdx
  website/content/docs/commands/var/list.mdx
  website/content/docs/commands/var/purge.mdx
  website/content/docs/commands/var/put.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, theme/cli, theme/variables

#14513 docs: keyring HTTP API documentation
  website/content/api-docs/operator/keyring.mdx
  website/data/api-docs-nav-data.json
Labels: theme/docs, theme/variables

#14555 var: Correct 0-index CAS Deletes
  nomad/state/state_store_variables.go
  nomad/state/state_store_variables_test.go
Labels: type/bug, theme/variables

#14516 docs: variables HTTP API documentation
  website/content/api-docs/variables.mdx
  website/data/api-docs-nav-data.json
Labels: theme/docs, theme/variables

#14561 docs: include path in ACL requirements for variables
  command/var_get.go
  command/var_list.go
  command/var_purge.go
  command/var_put.go
  website/content/docs/commands/var/get.mdx
  website/content/docs/commands/var/list.mdx
  website/content/docs/commands/var/purge.mdx
  website/content/docs/commands/var/put.mdx
Labels: theme/variables

#14509 changelog entry for variables feature
  .changelog/13000.txt
Labels: theme/variables

#10446 scheduler: stopped-yet-running allocs are still running
  .changelog/10446.txt
  nomad/job_endpoint_test.go
  nomad/structs/devices.go
  nomad/structs/devices_test.go
  nomad/structs/funcs.go
  nomad/structs/funcs_test.go
  nomad/structs/network.go
  nomad/structs/network_test.go
  scheduler/context.go
  scheduler/generic_sched_test.go
  testutil/wait.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: type/bug

#14576 docs: Correct driver name for 'Nomad Task Group' autoscaler target
  website/content/tools/autoscaling/plugins/target/nomad.mdx
Labels: theme/docs, backport/website, backport/1.2.x, backport/1.3.x

#14587 E2E/UI: set `NOMAD_PROXY_ADDR` separately from `NOMAD_ADDR`
  e2e/ui/README.md
  e2e/ui/api-client.js
  e2e/ui/global-setup.js
  e2e/ui/input/tokens/operator.js
  e2e/ui/run.sh
  e2e/ui/tests/download-logs.spec.js
  e2e/ui/tests/example.spec.js
Labels: theme/ui, theme/testing

#14599 variables: fix ENT-only test failure in command tests
  command/var_get_test.go
Labels: type/bug, theme/testing, theme/variables

#14473 website: content updates for developer
  website/Makefile
  website/content/docs/commands/agent.mdx
  website/content/docs/commands/alloc/stop.mdx
  website/content/docs/commands/deployment/fail.mdx
  website/content/docs/commands/deployment/promote.mdx
  website/content/docs/commands/deployment/resume.mdx
  website/content/docs/commands/deployment/unblock.mdx
  website/content/docs/commands/job/dispatch.mdx
  website/content/docs/commands/job/eval.mdx
  website/content/docs/commands/job/periodic-force.mdx
  website/content/docs/commands/job/promote.mdx
  website/content/docs/commands/job/revert.mdx
  website/content/docs/commands/job/run.mdx
  website/content/docs/commands/job/scale.mdx
  website/content/docs/commands/job/stop.mdx
  website/content/docs/concepts/security.mdx
  website/content/docs/concepts/variables.mdx
  website/content/docs/configuration/consul.mdx
  website/content/docs/configuration/server.mdx
  website/content/docs/configuration/telemetry.mdx
  website/content/docs/enterprise/license/index.mdx
  website/content/docs/faq.mdx
  website/content/docs/index.mdx
  website/content/docs/install/index.mdx
  website/content/docs/install/production/index.mdx
  website/content/docs/install/quickstart.mdx
  website/content/docs/integrations/consul-integration.mdx
  website/content/docs/job-specification/check.mdx
  website/content/docs/job-specification/connect.mdx
  website/content/docs/job-specification/gateway.mdx
  website/content/docs/job-specification/hcl2/variables.mdx
  website/content/docs/job-specification/lifecycle.mdx
  website/content/docs/job-specification/service.mdx
  website/content/docs/job-specification/template.mdx
  website/content/docs/job-specification/upstreams.mdx
  website/content/docs/job-specification/vault.mdx
  website/content/docs/operations/index.mdx
  website/content/docs/operations/metrics-reference.mdx
  website/content/docs/operations/monitoring-nomad.mdx
  website/content/docs/operations/nomad-agent.mdx
  website/content/docs/partnerships.mdx
  website/content/intro/index.mdx
  website/content/intro/use-cases.mdx
  website/content/intro/vs/terraform.mdx
  website/content/plugins/drivers/podman.mdx
  website/content/tools/autoscaling/plugins/target/aws-asg.mdx
  website/content/tools/autoscaling/plugins/target/azure-vmss.mdx
  website/content/tools/autoscaling/plugins/target/gce-mig.mdx
  website/data/docs-nav-data.json
  website/data/intro-nav-data.json
  website/data/plugins-nav-data.json
  website/scripts/website-build.sh
  website/scripts/website-start.sh
Labels: theme/docs, theme/website, backport/website

#14619 Minor tweaks to the service views
  ui/app/components/allocation-service-sidebar.hbs
  ui/app/styles/utils/z-indices.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/components/job-service-row.hbs
  ui/app/templates/jobs/job/services/index.hbs
  ui/app/templates/jobs/job/services/service.hbs
Labels: theme/ui

#14629 api: provide more detail on ACL bootstrap request error
  .github/14629.txt
  command/agent/acl_endpoint.go
Labels: backport/1.3.x

#14643 chore: backport go.work gitignore changes
  .gitignore
Labels: backport/1.2.x

#14610 operator debug: write NDJSON for large collections
  .changelog/14610.txt
  command/operator_debug.go
Labels: type/enhancement, theme/cli

#14620 cli: print success message on var put
  command/var_put.go
Labels: type/enhancement, theme/cli, theme/variables

#14651 cli: remove deprecated `eval status -json` list behavior
  .changelog/14651.txt
  command/eval_status.go
  command/eval_status_test.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/cli, type/tech-debt

#14661 [vars:api] Return fake QueryMeta on 403s with Peek()
  api/variables.go
Labels: type/bug, theme/api, theme/consul-template, theme/variables

#14659 scheduler: Fix bug where the would treat multiregion jobs as paused for job types that don't use deployments
  .changelog/14659.txt
  nomad/structs/structs.go
  scheduler/reconcile.go
  scheduler/reconcile_test.go
Labels: theme/enterprise, backport/1.2.x, backport/1.3.x

#14667 [vars] Update Consul Template dependency
  go.mod
  go.sum
Labels: theme/consul-template, theme/dependencies, theme/variables

#14673 fingerprint: don't clear Consul/Vault attributes on failure
  .changelog/14673.txt
  client/fingerprint/consul.go
  client/fingerprint/consul_test.go
  client/fingerprint/vault.go
  client/fingerprint/vault_test.go
  testutil/vault.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/client, theme/vault, theme/consul

#14634 cli: set content length on `operator api` requests
  .changelog/14634.txt
  command/operator_api.go
  command/operator_api_test.go
Labels: backport/1.3.x

#14679 docs: write a lot of words about heartbeats
  website/content/docs/configuration/server.mdx
Labels: backport/website

#14675 CSI: ensure initial unpublish state is checkpointed
  .changelog/14675.txt
  nomad/core_sched_test.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
Labels: type/bug, theme/storage, backport/1.1.x, backport/1.2.x, backport/1.3.x

#14720 backport to 1.2.x: CSI: skip node unpublish on GC'd or down nodes
  .changelog/14720.txt
  nomad/csi_endpoint.go
Labels: type/bug, theme/storage

#14721 backport to 1.1.x: CSI: skip node unpublish on GC'd or down nodes
  .changelog/14720.txt
  nomad/csi_endpoint.go
Labels: type/bug, theme/storage

#14637 jobspec: allow artifact headers in HCLv1
  .changelog/14637.txt
  jobspec/parse_task.go
  jobspec/parse_test.go
  jobspec/test-fixtures/artifacts.hcl
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#14664 multiregion: Added a section for multiregion parameterized job dispatch
  website/content/docs/commands/job/dispatch.mdx
  website/content/docs/job-specification/multiregion.mdx
  website/content/docs/job-specification/parameterized.mdx
  website/content/docs/job-specification/periodic.mdx
Labels: backport/website, backport/1.4.x

#14740 [ui] Bugfix: Service health checks would not take into account a second task of an alloc
  ui/app/routes/allocations/allocation.js
Labels: backport/1.4.x

#14741 [ui] Bugfix: reinstate the "this variable will be accessible by $job/$group/$task" notification
  ui/app/components/variable-form.hbs
  ui/app/components/variable-form.js
  ui/tests/acceptance/variables-test.js
Labels: backport/1.4.x

#14749 template: apply splay value on change_mode script
  .changelog/14749.txt
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
Labels: backport/1.3.x, backport/1.4.x
