Repository hashicorp/nomad, pull requests merged in 2022-07, with the labels that each got.

#13539 build: update to go1.18.3
  .circleci/config.yml
  .github/workflows/test-core.yaml
  .go-version
  contributing/README.md
  scripts/release/mac-remote-build
  scripts/vagrant-linux-priv-go.sh
Labels: backport/1.2.x, backport/1.3.x

#13542 ui: compute length difference
  ui/app/abilities/variable.js
  ui/app/templates/variables/variable/index.hbs
  ui/tests/acceptance/secure-variables-test.js
  ui/tests/unit/abilities/variable-test.js
Labels: theme/ui, theme/secure-variables

#13547 docs: Add 'serial' attribute to usb driver
  website/content/plugins/devices/community/usb.mdx
Labels: backport/website

#13582 small typo on volume specification page
  website/content/docs/other-specifications/volume/index.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x

#11716 Update sys/capabilties-self to read only
  website/content/docs/integrations/vault-integration.mdx
Labels: theme/docs, stage/waiting-reply

#13589 Fix Testutil for delve debugging API tests
  api/internal/testutil/discover/discover.go
  api/internal/testutil/server.go
Labels: type/bug, theme/testing

#13447 ui: create variable permission logic
  ui/app/abilities/variable.js
  ui/app/components/secure-variable-form.hbs
  ui/app/components/secure-variable-form/input-group.hbs
  ui/app/templates/variables/index.hbs
  ui/app/templates/variables/path.hbs
  ui/app/templates/variables/variable/index.hbs
  ui/mirage/factories/token.js
  ui/tests/acceptance/secure-variables-test.js
  ui/tests/unit/abilities/variable-test.js
Labels: theme/ui, theme/secure-variables

#13472 query for leader in `operator debug` command
  .changelog/13472.txt
  command/operator_debug.go
Labels: theme/cli

#13586 build: bump circleci macos version
  .circleci/config.yml
Labels: backport/1.2.x, backport/1.3.x

#13502 WIP: Secure Variables: Go API
  api/secure_variables.go
  api/secure_variables_test.go
Labels: theme/api, theme/secure-variables

#12955 core: emit node evals only for sys jobs in dc
  .changelog/12955.txt
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
Labels: backport/1.3.x

#13265 driver/docker: Don't pull InfraImage if it exists
  .changelog/13265.txt
  drivers/docker/network.go
  website/content/docs/drivers/docker.mdx
Labels: theme/networking, theme/driver/docker, backport/1.3.x

#13581 cli: improve output of eval commands
  .changelog/13581.txt
  command/eval.go
  command/eval_delete.go
  command/eval_list.go
  command/eval_status.go
  website/content/docs/commands/eval/delete.mdx
  website/content/docs/commands/eval/list.mdx
  website/content/docs/commands/eval/status.mdx
Labels: backport/1.3.x

#13551 state: fix eval list by prefix with * namespace
  .changelog/13551.txt
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: backport/1.2.x, backport/1.3.x

#13626 client: enforce max_kill_timeout client configuration
  .changelog/13626.txt
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/taskrunner/driver_handle.go
  client/allocrunner/taskrunner/remotetask_hook.go
  client/allocrunner/taskrunner/task_runner.go
  client/config/testing.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#13644 docs: upgrade guide for client max_kill_timeout
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/1.3.x

#13656 cli: ensure node status and drain use correct cmd name.
  .changelog/13656.txt
  command/node_drain.go
  command/node_status.go
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13668 agent: test full object when performing test config parse.
  command/agent/config_parse_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
Labels: backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13658 snapshot restore-from-archive streaming and filtering
  .changelog/13658.txt
  command/operator_snapshot_state.go
  helper/raftutil/fsm.go
  helper/raftutil/snapshot.go
  helper/snapshot/snapshot.go
  nomad/fsm.go
  scheduler/benchmarks/helpers_test.go
Labels: type/enhancement, theme/cli

#13659 [bugfix, ui] Allow running jobs from a namespace-limited token
  ui/app/abilities/job.js
  ui/app/adapters/job.js
  ui/app/components/job-editor.js
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/integration/components/job-editor-test.js
  ui/tests/unit/abilities/job-test.js
  ui/tests/unit/adapters/job-test.js
Labels: backport/1.3.x

#13691 changelog: add entry for #13659
  .changelog/13659.txt
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#13649 [CI-only] Support fossa scanning
  .release/ci.hcl
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#13696 docs: rename Internals to Concepts
  website/content/api-docs/operator/raft.mdx
  website/content/api-docs/operator/snapshot.mdx
  website/content/api-docs/volumes.mdx
  website/content/docs/commands/node/drain.mdx
  website/content/docs/commands/volume/create.mdx
  website/content/docs/commands/volume/delete.mdx
  website/content/docs/commands/volume/register.mdx
  website/content/docs/commands/volume/snapshot-create.mdx
  website/content/docs/commands/volume/snapshot-delete.mdx
  website/content/docs/commands/volume/snapshot-list.mdx
  website/content/docs/concepts/architecture.mdx
  website/content/docs/concepts/consensus.mdx
  website/content/docs/concepts/filesystem.mdx
  website/content/docs/concepts/gossip.mdx
  website/content/docs/concepts/index.mdx
  website/content/docs/concepts/plugins/base.mdx
  website/content/docs/concepts/plugins/csi.mdx
  website/content/docs/concepts/plugins/devices.mdx
  website/content/docs/concepts/plugins/index.mdx
  website/content/docs/concepts/plugins/task-drivers.mdx
  website/content/docs/concepts/scheduling/index.mdx
  website/content/docs/concepts/scheduling/preemption.mdx
  website/content/docs/concepts/scheduling/scheduling.mdx
  website/content/docs/concepts/security.mdx
  website/content/docs/drivers/docker.mdx
  website/content/docs/drivers/exec.mdx
  website/content/docs/drivers/index.mdx
  website/content/docs/drivers/java.mdx
  website/content/docs/drivers/qemu.mdx
  website/content/docs/drivers/raw_exec.mdx
  website/content/docs/ecosystem.mdx
  website/content/docs/faq.mdx
  website/content/docs/internals/index.mdx
  website/content/docs/job-specification/artifact.mdx
  website/content/docs/job-specification/service.mdx
  website/content/docs/job-specification/template.mdx
  website/content/docs/operations/monitoring-nomad.mdx
  website/content/docs/operations/nomad-agent.mdx
  website/content/docs/partnerships.mdx
  website/content/docs/runtime/environment.mdx
  website/content/docs/schedulers.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
  website/content/plugins/devices/community/index.mdx
  website/content/plugins/devices/index.mdx
  website/content/plugins/drivers/community/containerd.mdx
  website/content/plugins/drivers/community/index.mdx
  website/content/plugins/drivers/index.mdx
  website/content/plugins/drivers/podman.mdx
  website/content/plugins/drivers/remote/index.mdx
  website/content/tools/autoscaling/internals/plugins/index.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13679 Remove namespace cache
  .changelog/13679.txt
  ui/app/controllers/csi/volumes/index.js
  ui/app/controllers/jobs/index.js
  ui/app/controllers/optimize.js
  ui/app/services/system.js
  ui/app/templates/csi/volumes/index.hbs
  ui/app/templates/jobs/index.hbs
  ui/app/templates/optimize.hbs
  ui/tests/acceptance/jobs-list-test.js
  ui/tests/acceptance/optimize-test.js
  ui/tests/acceptance/volumes-list-test.js
Labels: backport/1.3.x

#13706 ci: remove any other versions of Node installed
  scripts/vagrant-linux-unpriv-ui.sh
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#13705 SV: fixes for namespace handling
  nomad/secure_variables_endpoint.go
  nomad/structs/secure_variables.go
Labels: theme/secure-variables

#13719 secure vars: fix enterprise test by upserting the namespace
  nomad/secure_variables_endpoint_test.go
Labels: theme/secure-variables

#13707 SV: CLI: var list command
  command/commands.go
  command/var.go
  command/var_list.go
  command/var_list_test.go
  nomad/secure_variables_endpoint.go
Labels: theme/secure-variables

#13651 core: merge reserved_ports into host_networks
  .changelog/13651.txt
  command/agent/command.go
  nomad/structs/funcs.go
  nomad/structs/network.go
  nomad/structs/network_test.go
  nomad/structs/structs.go
  scheduler/context_test.go
  scheduler/feasible.go
  scheduler/propertyset.go
  scheduler/rank.go
  scheduler/rank_test.go
  website/content/docs/configuration/client.mdx
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#13421 Track plan rejection history and automatically mark clients as ineligible
  .changelog/13421.txt
  command/agent/agent.go
  command/agent/agent_test.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  command/agent/testdata/sample0.json
  command/agent/testdata/sample1/sample0.json
  nomad/config.go
  nomad/plan_apply.go
  nomad/plan_apply_node_tracker.go
  nomad/plan_apply_node_tracker_test.go
  nomad/server.go
  nomad/state/state_store.go
  nomad/structs/structs.go
  website/content/docs/configuration/server.mdx
  website/content/docs/operations/metrics-reference.mdx
  website/content/docs/operations/monitoring-nomad.mdx
Labels: backport/1.3.x

#13750 tests: add a space between node name and timestamp
  helper/testlog/testlog.go
Labels: theme/testing

#13733 keyring: upserting key metadata in FSM must be deterministic
  nomad/state/state_store.go
Labels: type/bug, theme/secure-variables

#13716 docs: remove consul 1.12.0 warning
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/1.3.x

#13749 keyring: fix flake in replication-after-election test
  nomad/encrypter_test.go
Labels: type/bug, theme/flaky-tests, theme/secure-variables

#13773 packaging: restart nomad service after package update
  .release/linux/postrm
Labels: backport/1.1.x, backport/1.2.x, backport/1.3.x

#13769 Improve metrics reference documentation
  website/content/docs/operations/metrics-reference.mdx
Labels: theme/docs, backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13783 docs: update Podman docs to v0.4.0
  website/content/plugins/drivers/podman.mdx
Labels: backport/website

#13772 word typo digestible
  website/content/docs/enterprise/index.mdx
Labels: backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13779 docs: update Autoscaler AWS plugin with new ws_credential_provider config
  website/content/tools/autoscaling/plugins/target/aws-asg.mdx
Labels: backport/website

#13848 secure vars: rename automatically accessible vars path for jobs
  nomad/secure_variables_endpoint.go
  nomad/secure_variables_endpoint_test.go
  nomad/structs/secure_variables.go
  nomad/structs/secure_variables_test.go
Labels: theme/secure-variables

#13859 cleanup: example refactoring out map[string]struct{} using set.Set
  go.mod
  go.sum
  nomad/service_registration_endpoint.go
Labels: theme/cleanup

#13862 Change path-linked-variables to start with nomad/jobs/, instead of jobs/
  ui/app/components/secure-variable-form.hbs
  ui/app/components/secure-variable-form.js
  ui/app/models/job.js
  ui/app/models/task-group.js
  ui/app/models/task.js
  ui/app/models/variable.js
  ui/mirage/scenarios/default.js
  ui/tests/acceptance/secure-variables-test.js
  ui/tests/unit/models/variable-test.js
Labels: theme/secure-variables

#13621 Return 429 response on HTTP max connection limit
  .changelog/13621.txt
  command/agent/http.go
  command/agent/http_test.go
  website/content/docs/operations/metrics-reference.mdx
Labels: type/enhancement, theme/api, stage/accepted

#13695 docs: document secure variables server config options
  website/content/docs/configuration/server.mdx
Labels: theme/docs, theme/secure-variables

#13690 docs: keyring commands
  command/operator_secure_variables_keyring_install.go
  website/content/docs/commands/operator/gossip/keyring-generate.mdx
  website/content/docs/commands/operator/gossip/keyring-install.mdx
  website/content/docs/commands/operator/gossip/keyring-list.mdx
  website/content/docs/commands/operator/gossip/keyring-remove.mdx
  website/content/docs/commands/operator/gossip/keyring-use.mdx
  website/content/docs/commands/operator/keygen.mdx
  website/content/docs/commands/operator/keyring.mdx
  website/content/docs/commands/operator/secure-variables/keyring-install.mdx
  website/content/docs/commands/operator/secure-variables/keyring-list.mdx
  website/content/docs/commands/operator/secure-variables/keyring-remove.mdx
  website/content/docs/commands/operator/secure-variables/keyring-rotate.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, theme/secure-variables

#13849 keyring: use nanos for `CreateTime` in key metadata
  api/keyring.go
  command/operator_secure_variables_keyring.go
  nomad/keyring_endpoint_test.go
  nomad/structs/secure_variables.go
Labels: theme/secure-variables

#13788 search: use secure vars ACL policy for secure vars context
  acl/acl.go
  acl/acl_test.go
  command/agent/search_endpoint_test.go
  nomad/search_endpoint.go
Labels: type/bug, theme/auth, theme/secure-variables

#13748 workload identity: use parent ID for dispatch/periodic jobs
  nomad/encrypter_test.go
  nomad/plan_apply.go
  nomad/secure_variables_endpoint.go
  nomad/secure_variables_endpoint_test.go
  nomad/structs/structs.go
Labels: type/bug, theme/secure-variables

#13870 client: use test timeouts for network fingerprinters in dev mode
  command/agent/config.go
Labels: backport/1.2.x, backport/1.3.x

#13871 docs: clarify submit-job allows stopping
  website/content/docs/other-specifications/acl-policy.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x

#13880 block deleting namespaces if the namespace contains a volume
  .changelog/13880.txt
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: type/bug, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13888 block deleting namespace if it contains a secure variable
  nomad/state/state_store.go
  nomad/state/state_store_secure_variables.go
  nomad/state/state_store_test.go
Labels: theme/secure-variables

#13881 [docs] Fix link on Evaluations API page
  website/content/api-docs/evaluations.mdx
Labels: theme/docs, backport/website

#13901 changelog: add entry for #13865 and #13866
  .changelog/13865.txt
  .changelog/13866.txt
Labels: backport/1.3.x

#13892 Fixing placement in docs for scaling
  website/content/docs/job-specification/csi_plugin.mdx
  website/content/docs/job-specification/scaling.mdx
Labels: theme/docs, backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13738 Update filesystem.mdx
  website/content/docs/concepts/filesystem.mdx
Labels: backport/website, backport/1.1.x, backport/1.2.x, backport/1.3.x

#13932 deps: remove deprecated net/context
  client/logmon/server.go
  drivers/docker/docklog/docker_logger.go
  drivers/docker/docklog/docker_logger_test.go
  drivers/docker/docklog/server.go
  drivers/docker/handle.go
  drivers/shared/executor/grpc_server.go
  go.mod
  plugins/base/server.go
  plugins/device/server.go
  plugins/drivers/server.go
Labels: theme/dependencies

#13928 test: disable docker OOM detection test on cgroups v2
  drivers/docker/driver_test.go
Labels: theme/driver/docker, theme/flaky-tests

#13925 fix flaky `TestAgent_ProxyRPC_Dev` test
  command/agent/agent_test.go
Labels: theme/flaky-tests
