Repository hashicorp/nomad, pull requests merged in 2023-08, with the labels that each got.

#18096 fix 'default' alias not added to interface specified by `network_interface`
  .changelog/18096.txt
  client/fingerprint/network.go
  client/fingerprint/network_test.go
Labels: type/bug, theme/fingerprint, theme/networking, stage/waiting-reply, backport/1.4.x, backport/1.5.x, backport/1.6.x

#17925 cli: search all namespaces for node volumes
  .changelog/17925.txt
  command/node_status.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18130 Update nomad-agent.mdx
  website/content/docs/operations/nomad-agent.mdx
Labels: theme/docs

#18136 test: add tests for allocNameIndex core funcs
  scheduler/reconcile_util_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18141 scheduler: filter device instance IDs by constraints
  .changelog/18141.txt
  scheduler/device.go
  scheduler/device_test.go
Labels: type/bug, theme/devices

#18142 docs: fix URL in agent pprof examples
  website/content/api-docs/agent.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x, backport/1.6.x

#17958 CLI: make snapshot name requiered in creating volume snapshots
  .changelog/17958.txt
  command/volume_snapshot_create.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18155 test: fix flaky RPC TLS enforcement test
  nomad/rpc_test.go
Labels: theme/flaky-tests

#17939 Tuning job versions retention. #17635
  .changelog/17939.txt
  command/agent/agent.go
  command/agent/config.go
  nomad/config.go
  nomad/fsm.go
  nomad/fsm_test.go
  nomad/server.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/state/testing.go
  nomad/structs/structs.go
  website/content/docs/configuration/server.mdx
Labels: type/enhancement, backport/1.6.x

#18172 docs: expand pprof documentation on goroutine profiles
  website/content/api-docs/agent.mdx
Labels: theme/docs, theme/observability

#18179 e2e: modernize vaultcompat testing
  .github/workflows/test-e2e.yml
  GNUmakefile
  e2e/vaultcompat/README.md
  e2e/vaultcompat/consts_test.go
  e2e/vaultcompat/doc.go
  e2e/vaultcompat/input/cat.hcl
  e2e/vaultcompat/input/policy.hcl
  e2e/vaultcompat/role_test.go
  e2e/vaultcompat/vault_test.go
  e2e/vaultcompat/vaultcompat_test.go
  go.mod
  go.sum
  testutil/server.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18184 update go1.21
  .go-version
  .golangci.yml
  .semgrep/imports.yml
  GNUmakefile
  client/allocrunner/taskrunner/driver_handle.go
  client/allocrunner/taskrunner/getter/params.go
  client/client.go
  command/agent/http_test.go
  command/job_restart.go
  contributing/README.md
  go.mod
  go.sum
  helper/cluster_test.go
  helper/funcs.go
  helper/funcs_test.go
  nomad/blocked_evals.go
  nomad/drainer/watch_jobs.go
  nomad/job_endpoint.go
  nomad/node_pool_endpoint.go
  nomad/scaling_endpoint.go
  nomad/server.go
  nomad/state/state_store_variables.go
  nomad/structs/structs.go
  scheduler/propertyset.go
  scheduler/reconcile.go
  scripts/linux-priv-go.sh
  scripts/release/mac-remote-build
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18175 docs: ampersand and bash backgrounding problem
  website/content/api-docs/agent.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x, backport/1.6.x

#18170 test: deflake job endpoint registration test
  nomad/job_endpoint_test.go
Labels: theme/flaky-tests

#18171 test: deflake node drain intergration test
  nomad/drainer_int_test.go
Labels: theme/drain, theme/flaky-tests

#18200 fix multiple overflow errors in exponential backoff
  .changelog/18200.txt
  client/allocrunner/taskrunner/stats_hook.go
  client/allocrunner/taskrunner/vault_hook.go
  client/devicemanager/instance.go
  client/pluginmanager/drivermanager/instance.go
  command/agent/consul/version_checker.go
  drivers/docker/driver.go
  drivers/docker/stats.go
  helper/backoff.go
  helper/backoff_test.go
  nomad/state/state_store.go
  nomad/worker.go
Labels: type/bug

#18109 docs: expand documentation on node pools
  website/content/api-docs/jobs.mdx
  website/content/docs/concepts/architecture.mdx
  website/content/docs/concepts/node-pools.mdx
  website/content/docs/concepts/scheduling/index.mdx
  website/content/docs/concepts/scheduling/placement.mdx
  website/content/docs/concepts/scheduling/scheduling.mdx
  website/content/docs/job-specification/multiregion.mdx
  website/content/docs/other-specifications/node-pool.mdx
  website/content/docs/schedulers.mdx
  website/data/docs-nav-data.json
Labels: backport/website, backport/1.6.x

#18223 docs: move glossary to a top-level menu item
  website/content/docs/concepts/architecture.mdx
  website/content/docs/glossary.mdx
  website/data/docs-nav-data.json
Labels: backport/website, backport/1.6.x

#18225 docs: fix job dispatch documentation
  website/content/api-docs/jobs.mdx
  website/content/docs/commands/job/dispatch.mdx
Labels: theme/docs, backport/website, backport/1.4.x, backport/1.5.x, backport/1.6.x

#18120 [ui] Preserve HCL2 on stop/start via the web UI
  .changelog/18120.txt
  ui/app/components/job-page/parts/title.js
  ui/mirage/config.js
  ui/tests/integration/components/job-page/helpers.js
  ui/tests/integration/components/job-page/periodic-test.js
  ui/tests/integration/components/job-page/service-test.js
Labels: backport/1.6.x

#18234 csi: prevent panic on volume delete
  .changelog/18234.txt
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18240 deps: update hashicorp/go-set to v0.1.14
  go.mod
  go.sum
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18237 nomad: remove custom max func and use Go 1.21.0 builtin
  nomad/plan_apply.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18224 config: parsing support for multiple Vault clusters in agent config
  client/config/config.go
  client/config/testing.go
  command/agent/agent.go
  command/agent/agent_endpoint.go
  command/agent/command.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/extra-vault.hcl
  command/agent/testdata/sample0.json
  nomad/config.go
  nomad/structs/config/vault.go
Labels: type/enhancement, theme/config, theme/vault

#18210 [ui] Use ]] and [[ to paginate index pages
  .changelog/18210.txt
  ui/.template-lintrc.js
  ui/app/components/list-pagination/list-pager.js
  ui/app/templates/components/list-pagination/list-pager.hbs
Labels: backport/1.6.x

#18255 config: parsing support for multiple Consul clusters in agent config
  client/config/config.go
  command/agent/agent.go
  command/agent/agent_endpoint.go
  command/agent/command.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/extra-consul.hcl
  command/agent/testdata/sample0.json
  nomad/config.go
  nomad/structs/config/consul.go
Labels: type/enhancement, theme/config, theme/consul

#18253 fingerprint: add support for fingerprinting multiple Vault clusters
  client/fingerprint/vault.go
  client/fingerprint/vault_ce.go
  client/fingerprint/vault_test.go
  testutil/vault.go
Labels: type/enhancement, theme/fingerprint, theme/vault

#17929 feat: improve policy documentation for "query_window" property
  website/content/tools/autoscaling/plugins/apm/nomad.mdx
  website/content/tools/autoscaling/policy.mdx
Labels: backport/website, backport/1.6.x

#18232 client: 404 when accessing files for GC'ed alloc
  .changelog/18232.txt
  client/fs_endpoint.go
  client/fs_endpoint_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18277 docs: clarify reference to `network.mode` in docker `network_mode` config
  website/content/docs/drivers/docker.mdx
Labels: backport/website, backport/1.6.x

#17858 Add multiple times in periodic jobs
  .changelog/17858.txt
  api/jobs.go
  api/jobs_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/parse_job.go
  jobspec/parse_test.go
  jobspec/test-fixtures/periodic-crons.hcl
  jobspec2/parse_job.go
  nomad/structs/diff.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  ui/app/templates/components/job-page/periodic.hbs
  website/content/api-docs/json-jobs.mdx
  website/content/docs/job-specification/periodic.mdx
Labels: backport/1.6.x

#18296 docs: fix a sentence in vault-integration.mdx
  website/content/docs/integrations/vault-integration.mdx
Labels: backport/website, backport/1.4.x, backport/1.5.x, backport/1.6.x

#18288 docs: expand on where node_class may be used
  website/content/docs/configuration/client.mdx
Labels: theme/docs

#18311 all: swap exp packages for maps, slices
  .semgrep/imports.yml
  api/error_unexpected_response.go
  client/allocrunner/taskrunner/getter/params.go
  client/allocrunner/taskrunner/task_runner.go
  client/config/config.go
  client/lib/idset/idset.go
  client/serviceregistration/checks/checkstore/shim.go
  client/serviceregistration/checks/checkstore/shim_test.go
  command/acl_auth_method_create.go
  command/acl_auth_method_update.go
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/consul/catalog_testing.go
  command/agent/consul/connect.go
  command/agent/consul/service_client.go
  command/agent/job_endpoint.go
  command/alloc_status.go
  command/operator_debug.go
  command/var_put.go
  drivers/docker/driver.go
  e2e/servicediscovery/service_discovery_test.go
  helper/funcs.go
  jobspec2/parse_job.go
  lib/auth/jwt/validator.go
  nomad/config.go
  nomad/consul.go
  nomad/job_endpoint_hook_connect.go
  nomad/job_endpoint_hook_vault.go
  nomad/license_config.go
  nomad/search_endpoint_test.go
  nomad/state/state_store.go
  nomad/state/state_store_acl.go
  nomad/structs/acl.go
  nomad/structs/bitmap.go
  nomad/structs/config/audit.go
  nomad/structs/config/sentinel.go
  nomad/structs/config/ui.go
  nomad/structs/csi.go
  nomad/structs/network.go
  nomad/structs/service_registration.go
  nomad/structs/services.go
  nomad/structs/structs.go
  nomad/structs/workload_id.go
  nomad/util.go
  scheduler/generic_sched_test.go
  scheduler/util.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18316 test: use must package for state store restore test file.
  nomad/state/state_store_restore_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18326 test: use correct parallel test setup func
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/taskrunner/artifact_hook_test.go
  client/client_test.go
  client/widmgr/widmgr_test.go
  command/tls_cert_create_test.go
  drivers/docker/driver_test.go
  nomad/acl_endpoint_test.go
  nomad/alloc_endpoint_test.go
  nomad/node_endpoint_test.go
  nomad/plan_apply_test.go
  nomad/plan_endpoint_test.go
  nomad/structs/workload_id_test.go
  nomad/util_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18333 nds: add validation for `tls_skip_verify`
  .changelog/18333.txt
  nomad/structs/services.go
  nomad/structs/services_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18269 Ensure that the index processed by the client is at least as new as the last one processed.
  .changelog/18269.txt
  client/client.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18332 jobspec: add diff for Task Group Scaling block
  .changelog/18332.txt
  nomad/structs/diff.go
  nomad/structs/diff_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18345 client: include response body in output for successful HTTP checks
  .changelog/18345.txt
  client/serviceregistration/checks/client.go
  client/serviceregistration/checks/client_test.go
Labels: backport/1.6.x

#18362 Revert "client: include response body in output for successful HTTP checks (#18345)"
  .changelog/18345.txt
  client/serviceregistration/checks/client.go
  client/serviceregistration/checks/client_test.go
Labels: backport/1.6.x
