Repository hashicorp/nomad, pull requests merged in 2023-12, with the labels that each got.

#19249 E2E: fix assertion in CT native service lookup test
  e2e/consultemplate/consultemplate_test.go
Labels: theme/consul-template, theme/e2e

#19216 Clarify docs around CSI volume context updates
  website/content/docs/other-specifications/volume/index.mdx
Labels: backport/website, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19270 variables: fix access to variables for poststop tasks
  .changelog/19270.txt
  nomad/acl.go
Labels: type/bug, theme/variables

#19268 vault: fix legacy token workflow for poststop tasks
  .changelog/19268.txt
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
Labels: theme/vault, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19258 docs: split `consul` config params into client vs server sections
  website/content/docs/configuration/consul.mdx
Labels: theme/docs, theme/consul, backport/1.7.x

#18932 client version constraints for implicit identities for WI
  nomad/job_endpoint_hook_implicit_identities.go
  nomad/job_endpoint_hook_implicit_identities_test.go
  scheduler/feasible_test.go
Labels: theme/vault, theme/consul, theme/workload-identity, backport/1.7.x

#19275 docs: changelog entry for bugfix introduced in #18754
  .changelog/18754.txt
Labels: theme/docs, backport/1.7.x

#19285 docs: small updates to agent `consul`
  website/content/docs/configuration/consul.mdx
Labels: backport/1.7.x

#19299 docs: fix recommended binding rules for Consul integration
  website/content/docs/integrations/consul-integration.mdx
Labels: theme/docs, theme/consul, backport/1.7.x

#19153 [ui] example job with actions
  .changelog/19153.txt
  ui/app/utils/default-job-templates.js
  ui/app/utils/default_jobs/actions.js
  ui/tests/acceptance/job-run-test.js
Labels: backport/1.7.x

#19282 docs: clarify behavior and recommendations for mTLS vs TLS for HTTP
  website/content/docs/concepts/security.mdx
  website/content/docs/configuration/tls.mdx
Labels: theme/docs, theme/auth, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19320 Update to Go 1.21.5
  .changelog/19320.txt
  .go-version
  contributing/README.md
  scripts/linux-priv-go.sh
  scripts/release/mac-remote-build
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19101 Add a new parameter to avoid starting a replacement for lost allocs
  .changelog/16867.txt
  api/jobs_test.go
  api/tasks.go
  client/client.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  nomad/core_sched_test.go
  nomad/mock/job.go
  nomad/plan_apply.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  scheduler/reconcile.go
  scheduler/reconcile_test.go
  scheduler/reconcile_util.go
  scheduler/reconcile_util_test.go
  website/content/docs/job-specification/group.mdx
Labels: type/enhancement, theme/scheduling

#19334 connect: deployments should wait for Connect sidecar checks
  .changelog/19334.txt
  client/allochealth/tracker.go
  client/allochealth/tracker_test.go
  client/serviceregistration/service_registration.go
  command/agent/consul/service_client.go
Labels: type/bug, theme/consul, theme/consul/connect

#19349 config: fix loading Vault token from env var
  .changelog/19349.txt
  command/agent/command.go
  command/agent/command_test.go
Labels: backport/1.7.x

#19333 ci: use go-modtool with config file
  GNUmakefile
  ci/modtool.toml
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19335 docs: expand on Sentinel policy reference
  website/content/docs/enterprise/index.mdx
  website/content/docs/enterprise/sentinel.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, theme/enterprise, backport/1.5.x, backport/1.6.x, backport/1.7.x

#16638 client: allow incomplete allocrunners to be removed on restore
  .changelog/16638.txt
  client/client.go
  client/client_test.go
Labels: type/enhancement, theme/client, theme/client-restart, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19370 UI: fix column header typo on job services page
  ui/app/templates/jobs/job/services/index.hbs
Labels: theme/ui, backport/1.7.x

#19377 [ui] Two small UI quality of life changes
  .changelog/19377.txt
  ui/app/templates/components/job-editor/edit.hbs
  ui/app/templates/components/job-page/parts/children.hbs
  ui/app/templates/components/job-row.hbs
  ui/app/templates/jobs/index.hbs
  ui/tests/acceptance/jobs-list-test.js
Labels: backport/1.7.x

#19394 update PKI example in template spec with the new pkiCert function
  website/content/docs/job-specification/template.mdx
Labels: theme/docs, theme/vault, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19399 docs: add warning not to use 1.7.0
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/docs

#19400 docs: add warnings about backing up keyring to snapshot commands
  website/content/docs/commands/operator/snapshot/agent.mdx
  website/content/docs/commands/operator/snapshot/save.mdx
Labels: theme/docs, theme/keyring, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19416 changelog: add entry for #19415
  .changelog/19415.txt
Labels: backport/1.7.x

#19404 docs: fix placement of Consul auth method configs
  website/content/docs/configuration/consul.mdx
Labels: backport/website, backport/1.7.x

#19332 [ui] Small-screen styles for exec window
  .changelog/19332.txt
  ui/app/styles/components/exec-window.scss
  ui/app/styles/core/variables.scss
Labels: backport/1.7.x

#18516 Fixes Consul token checking when policies exist within namespaces
  .changelog/18516.txt
  e2e/connect/acls.go
  nomad/consul_policy.go
Labels: hcc/cst, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19432 [ui] Fix a small regression where accessor is hidden by default when editing a token
  .changelog/19432.txt
  ui/app/components/token-editor.hbs
Labels: backport/1.7.x

#19425 auth: respect default `tls.verify_server_hostname=false`
  .changelog/19425.txt
  nomad/auth/auth.go
  nomad/auth/auth_test.go
  nomad/server.go
Labels: type/bug, theme/auth, backport/1.7.x

#19434 e2e: unflake testTaskImageChroot
  e2e/isolation/input/chroot_docker.nomad
Labels: theme/flaky-tests, theme/e2e

#19423 cli: Fix bug in `var put` command using mix of flags and spec.
  .changelog/19423.txt
  command/var_put.go
  command/var_put_test.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19449 consul: fix constraints for non-default clusters (ENT)
  .changelog/19449.txt
  nomad/job_endpoint_hook_connect.go
  nomad/job_endpoint_hook_connect_test.go
Labels: type/bug, theme/consul, theme/enterprise, backport/1.7.x

#19439 vault: load default config for tasks without vault
  .changelog/19439.txt
  client/allocrunner/taskrunner/template_hook.go
  client/allocrunner/taskrunner/template_hook_test.go
Labels: theme/vault, backport/1.7.x

#19304 [docs] Note reboot to update `bridge_network_hairpin_mode`
  website/content/docs/configuration/client.mdx
Labels: type/enhancement, theme/docs, theme/networking, backport/website, backport/1.7.x

#19383 numa: account for incorrect core number on topology.insert
  .changelog/19383.txt
  client/lib/numalib/detect_linux.go
  client/lib/numalib/detect_linux_test.go
  client/lib/numalib/topology.go
Labels: backport/1.7.x

#19441 [CSI] Prevent stage_publish_base_dir from being subdir of mount_dir
  .changelog/19441.txt
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  website/content/docs/job-specification/csi_plugin.mdx
Labels: type/bug, theme/storage, backport/1.7.x

#19452 [ui] When Action output is long enough, keep a user scroll-anchored to the bottom
  .changelog/19452.txt
  ui/app/components/action-card.hbs
  ui/app/components/action-card.js
  ui/app/styles/components/actions.scss
Labels: backport/1.7.x

#19470 docs: add reporting config block documentation.
  website/content/docs/configuration/reporting.mdx
  website/data/docs-nav-data.json
Labels: backport/website, backport/1.7.x

#19435 Update auth-methods docs to comply with style guide
  website/content/api-docs/acl/auth-methods.mdx
Labels: theme/docs, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19474 docs: note that 1.7.2 yanks 1.7.0-1.7.1 due to CPU fingerprint bug
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/docs, backport/1.7.x

#19336 Adds support for failures_before_warning and adds failues_before options on Nomad client service
  .changelog/19336.txt
  api/services.go
  api/services_test.go
  command/agent/agent.go
  command/agent/agent_test.go
  command/agent/command.go
  command/agent/consul/service_client.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/parse_service.go
  jobspec/parse_test.go
  jobspec/test-fixtures/service-check-pass-fail.hcl
  nomad/structs/config/consul.go
  nomad/structs/diff_test.go
  nomad/structs/services.go
  nomad/structs/services_test.go
  website/content/docs/commands/agent.mdx
  website/content/docs/configuration/consul.mdx
  website/content/docs/job-specification/check.mdx
Labels: backport/1.7.x

#19424 docs: update Consul and Vault integration
  website/content/docs/concepts/workload-identity.mdx
  website/content/docs/integrations/consul-integration.mdx
  website/content/docs/integrations/consul/acl.mdx
  website/content/docs/integrations/consul/index.mdx
  website/content/docs/integrations/consul/service-mesh.mdx
  website/content/docs/integrations/vault/acl.mdx
  website/content/docs/integrations/vault/index.mdx
  website/content/docs/job-specification/identity.mdx
  website/data/docs-nav-data.json
  website/public/img/consul-integration-auth-method.png
  website/public/img/consul-integration-wi.png
  website/public/img/consul-integration-wid-acl-token.png
  website/public/img/vault-integration-auth-method.png
  website/public/img/vault-integration-auth-overview.png
  website/public/img/vault-integration-wid-acl-token.png
  website/redirects.js
Labels: backport/website, backport/1.7.x

#19485 consul: fingerprint Consul Enterprise admin partitions
  .changelog/19485.txt
  client/fingerprint/consul.go
  client/fingerprint/consul_test.go
Labels: type/enhancement, theme/fingerprint, theme/consul, backport/1.7.x

#19490 client: consul hook not called for templates
  .changelog/19490.txt
  client/allocrunner/taskrunner/consul_hook.go
  client/allocrunner/taskrunner/task_runner_hooks.go
Labels: type/bug, theme/consul, theme/workload-identity, backport/1.7.x

#19176 Mark CGroups as off when missing essential controllers
  .changelog/19176.txt
  client/lib/cgroupslib/mount.go
Labels: type/enhancement, theme/cgroups, backport/1.7.x

#19483 Surfaces errors from namespace delete properly
  .changelog/19483.txt
  nomad/fsm.go
  nomad/fsm_test.go
Labels: type/bug, theme/namespaces, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19501 docs: note replacement of `-` characters in meta env vars
  website/content/docs/job-specification/meta.mdx
  website/content/docs/runtime/environment.mdx
  website/content/partials/envvars.mdx
Labels: theme/docs, backport/1.5.x, backport/1.6.x, backport/1.7.x

#18823 UI: Show message for when log collection is disabled
  .changelog/18823.txt
  ui/app/components/task-log.js
  ui/app/templates/components/task-log.hbs
Labels: type/enhancement, theme/ui, backport/1.7.x

#19508 docs: fix migration to workload identity links
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/website, backport/1.7.x

#19510 consul: fix parsing of `service.cluster` field
  api/services.go
Labels: backport/1.7.x

#19513 ci: run linter in `./api` package
  GNUmakefile
  api/agent.go
  api/allocations_exec.go
  api/api.go
  api/consul.go
  api/event_stream.go
  api/internal/testutil/responsewriter.go
  api/internal/testutil/server.go
  api/operator.go
  api/retry.go
  api/search.go
  api/tasks.go
  api/variables.go
  drivers/shared/executor/procstats/list_default.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#18607 [ui] node eligibilty taken into consideration when clients list filtered to "ready"
  .changelog/18607.txt
  ui/app/components/client-node-row.js
  ui/app/controllers/clients/index.js
  ui/app/styles/core/table.scss
  ui/app/templates/clients/index.hbs
  ui/app/templates/components/client-node-row.hbs
  ui/tests/acceptance/clients-list-test.js
  ui/tests/pages/clients/list.js
Labels: backport/1.7.x

#19529 [ui] Mask token secret when logged in
  .changelog/19529.txt
  ui/app/styles/components/authorization.scss
  ui/app/templates/settings/tokens.hbs
  ui/tests/pages/settings/tokens.js
Labels: backport/1.7.x

#19537 docs: correct Nomad Autoscaler example link in HA vars documentation
  website/content/docs/concepts/variables.mdx
Labels: theme/docs, backport/website, theme/variables, backport/1.7.x

#19535 Adds vault role to JWT claims if specified in jobspec
  .changelog/19535.txt
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  website/content/docs/concepts/workload-identity.mdx
Labels: type/enhancement, theme/vault, theme/workload-identity, backport/1.7.x

#19010 docs: add Nomad Autoscaler HA configuration details.
  website/content/tools/autoscaling/agent/high_availability.mdx
  website/content/tools/autoscaling/cli.mdx
  website/data/tools-nav-data.json
Labels: backport/website, backport/1.7.x
