Repository hashicorp/nomad, pull requests merged in 2023-07, with the labels that each got.

#17795 docs: fix up constraint jobspec HCL format.
  website/content/docs/job-specification/constraint.mdx
Labels: backport/website, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17280 [api] Add NetworkStatus to allocation response
  .changelog/17280.txt
  api/allocations.go
  api/allocations_test.go
Labels: stage/waiting-reply, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17579 Add "total_ticks_count" for CPU metrics
  .changelog/17579.txt
  client/allocrunner/taskrunner/task_runner.go
  client/client.go
  client/stats/cpu.go
  client/stats/cpu_test.go
  client/stats/host.go
  website/content/docs/operations/metrics-reference.mdx
Labels: type/enhancement, theme/metrics

#17812 [Docs] Update security.mdx
  website/content/docs/concepts/security.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x

#17775 CI: Dynamic runs-on values for oss/ent
  .github/actions/setup-js/action.yml
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/checks.yaml
  .github/workflows/release.yml
  .github/workflows/test-core.yaml
  .github/workflows/test-e2e.yml
  .github/workflows/test-ui.yml
  .github/workflows/test-windows.yml
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17808 ci: clean GOCACHE before build
  .github/workflows/build.yml
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17766 cni: ensure to setup CNI addresses in deterministic order
  .changelog/17766.txt
  client/allocrunner/networking_cni.go
  client/allocrunner/networking_cni_test.go
Labels: hcc/cst, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17829 ci: keep windows tests on public runners
  .github/workflows/test-windows.yml
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17835 env/aws: updates from ec2info
  client/fingerprint/env_aws_cpu.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17841 ci: pull secrets from Vault in nomad-enterprise
  .github/actions/vault-secrets/action.yml
  .github/workflows/backport.yml
  .github/workflows/build.yml
  .github/workflows/checks.yaml
  .github/workflows/release.yml
  .github/workflows/test-core.yaml
  .github/workflows/test-e2e.yml
  .github/workflows/test-ui.yml
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17847 consul: handle "not found" errors from Consul when deleting tokens
  .changelog/17847.txt
  nomad/consul.go
Labels: type/bug, theme/consul, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17852 ci: more self-hosted iops for checks workflow
  .github/workflows/checks.yaml
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17843 Include parent job ID as a Docker container label #17751
  .changelog/17843.txt
  client/allocrunner/taskrunner/task_runner.go
  drivers/docker/driver.go
  plugins/drivers/driver.go
  plugins/drivers/proto/driver.pb.go
  plugins/drivers/proto/driver.proto
Labels: type/enhancement, theme/driver/docker

#17840 CSI: persist previous mounts on client to restore during restart
  .changelog/17840.txt
  client/allocrunner/alloc_runner.go
  client/allocrunner/csi_hook.go
  client/allocrunner/csi_hook_test.go
  client/allocrunner/state/state.go
  client/pluginmanager/csimanager/instance.go
  client/pluginmanager/csimanager/interface.go
  client/pluginmanager/csimanager/volume.go
  client/pluginmanager/csimanager/volume_test.go
  client/state/db_bolt.go
  client/state/db_error.go
  client/state/db_mem.go
  client/state/db_noop.go
  client/state/interface.go
  helper/funcs.go
  nomad/csi_endpoint.go
  nomad/structs/volumes.go
Labels: type/bug, theme/storage, hcc/cst, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17881 docs: v1.6.0 requires ipc_lock cap for mlock
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/website

#17896 Clarify update stagger description and alternatives
  website/content/docs/job-specification/update.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x, backport/1.6.x

#17824 docs: update podman driver docs with v0.5.0 changes
  website/content/plugins/drivers/podman.mdx
Labels: backport/website

#17706 Smoke test binaries for EL7/glibc-2.17 compatiblity
  .github/workflows/build.yml
Labels: theme/build-infrastructure, theme/ci, backport/1.4.x, backport/1.5.x, backport/1.6.x

#17928 fix: allowed metric values documentation for the Nomad APM plugin
  website/content/tools/autoscaling/plugins/apm/nomad.mdx
Labels: backport/website, backport/1.6.x

#17930 docs: fix QEMU driver HCL plugin options example formatting.
  website/content/docs/drivers/qemu.mdx
Labels: backport/website, backport/1.4.x, backport/1.5.x, backport/1.6.x

#17950 docs: note windows requirement for workload identity
  website/content/api-docs/task-api.mdx
  website/content/docs/concepts/workload-identity.mdx
  website/content/docs/job-specification/identity.mdx
Labels: backport/website

#17962 [chore] Fix typos
  drivers/docker/config.go
  drivers/docker/utils.go
Labels: type/bug, theme/driver/docker, type/tech-debt

#17975 test: enable exec test previously disabled due to CircleCI
  plugins/drivers/testutils/exec_testing.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#17967 qemu: add test to cover task store functions.
  drivers/qemu/state_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#17963 updating to specify mTLS rpc endpoints
  website/content/docs/configuration/tls.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x, backport/1.6.x

#17994 changelog: add entry for #17731 into 1.4.11
  CHANGELOG.md
Labels: backport/1.4.x

#17911 volume-status : show namespace the volume belongs to
  .changelog/17911.txt
  command/node_status.go
  command/volume_status.go
  command/volume_status_csi.go
  website/content/docs/commands/node/status.mdx
  website/content/docs/commands/volume/status.mdx
Labels: backport/1.6.x

#17940 ui: fix Topology node state filter
  .changelog/17940.txt
  ui/app/controllers/topology.js
  ui/tests/acceptance/topology-test.js
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#17936 nsd: retain query params in HTTP health checks
  .changelog/17936.txt
  client/serviceregistration/checks/client.go
  client/serviceregistration/checks/client_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#17938 metrics: report task memory_max value
  .changelog/17938.txt
  client/allocrunner/taskrunner/task_runner.go
  website/content/docs/operations/metrics-reference.mdx
Labels: backport/1.6.x

#17915 [ui] When a purged/404-ing job is detected, boot the user out of that job and back to the index
  ui/app/controllers/jobs/job.js
  ui/app/routes/jobs/job.js
  ui/app/routes/jobs/job/index.js
  ui/app/templates/jobs/job.hbs
  ui/app/utils/properties/watch.js
  ui/tests/acceptance/job-detail-test.js
Labels: backport/1.6.x

#17932 [ui] New keyboard shortcut for Create Variable
  .changelog/17932.txt
  ui/app/controllers/variables/index.js
  ui/app/controllers/variables/path.js
  ui/app/templates/variables/index.hbs
  ui/app/templates/variables/path.hbs
Labels: backport/1.6.x

#17933 [ui] Copy change to include the nomad/jobs all-access variable prefix
  .changelog/17933.txt
  ui/app/components/variable-form.hbs
Labels: backport/1.6.x

#17935 [ui] Copy button added to variables title
  .changelog/17935.txt
  ui/app/styles/components/variables.scss
  ui/app/templates/variables/variable/index.hbs
Labels: backport/1.6.x

#17996 CSI: improve controller RPC reliability
  .changelog/17996.txt
  nomad/client_csi_endpoint.go
  nomad/csi_endpoint.go
  nomad/csi_endpoint_test.go
  nomad/server.go
Labels: type/bug, theme/storage, hcc/cst, backport/1.4.x, backport/1.5.x, backport/1.6.x

#18017 state: canonicalize namespace on restore
  .changelog/18017.txt
  nomad/state/state_store_restore.go
Labels: backport/1.6.x

#18020 ui: handle errors from unimplemented services
  .changelog/18020.txt
  ui/app/adapters/application.js
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18021 ui: handle node pool requests to older regions
  .changelog/18021.txt
  ui/app/adapters/node-pool.js
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/components/client-node-row.hbs
  ui/app/templates/components/job-page/parts/stats-box.hbs
  ui/app/templates/components/job-row.hbs
Labels: backport/1.6.x

#18026 Changelog entry for remote purge boot-out
  .changelog/17915.txt
Labels: backport/1.6.x

#18005 Retain task states for post stop tasks at the time of node GC
  .changelog/17971.txt
  client/allocrunner/alloc_runner.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#17927 node-pool: fix validate name function comment typo.
  nomad/structs/node_pool.go
Labels: backport/1.6.x

#17815 check in stderrFrame is nil before logging stderrFrame.Data
  .changelog/17815.txt
  command/alloc_logs.go
Labels: backport/1.5.x, backport/1.6.x

#18044 build: update to go 1.20.6
  .go-version
  contributing/README.md
  scripts/linux-priv-go.sh
  scripts/release/mac-remote-build
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18006 website: add Nomad Ops to Tools
  website/content/tools/index.mdx
Labels: backport/website, backport/1.6.x

#18051 [ui] Sort variables ascending by key at serialization time
  .changelog/18051.txt
  ui/app/serializers/variable.js
Labels: backport/1.6.x

#18056 changelog: add entry for #18044
  .changelog/18044.txt
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18061 chore(nodepool): Go stdlib vars for HTTP methods and status codes
  command/agent/node_pool_endpoint.go
  command/agent/node_pool_endpoint_test.go
Labels: backport/1.6.x

#18062 chore(variable): Go stdlib vars for HTTP methods and status codes
  command/agent/variable_endpoint.go
  command/agent/variable_endpoint_test.go
Labels: backport/1.5.x, backport/1.6.x

#17968 chore(lint): use Go stdlib variables for HTTP methods and status codes
  .golangci.yml
  client/allocrunner/checks_hook_test.go
  client/fingerprint/env_azure.go
  client/fingerprint/env_azure_test.go
  client/fingerprint/env_digitalocean_test.go
  client/fingerprint/env_gce.go
  client/fingerprint/env_gce_test.go
  client/serviceregistration/checks/client.go
  client/serviceregistration/checks/client_test.go
  command/agent/acl_endpoint.go
  command/agent/acl_endpoint_test.go
  command/agent/agent_endpoint.go
  command/agent/agent_endpoint_test.go
  command/agent/alloc_endpoint.go
  command/agent/alloc_endpoint_test.go
  command/agent/csi_endpoint_test.go
  command/agent/deployment_endpoint_test.go
  command/agent/eval_endpoint.go
  command/agent/eval_endpoint_test.go
  command/agent/event_endpoint_test.go
  command/agent/fs_endpoint_test.go
  command/agent/http.go
  command/agent/http_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  command/agent/metrics_endpoint.go
  command/agent/metrics_endpoint_test.go
  command/agent/namespace_endpoint.go
  command/agent/namespace_endpoint_test.go
  command/agent/node_endpoint.go
  command/agent/node_endpoint_test.go
  command/agent/operator_endpoint.go
  command/agent/operator_endpoint_oss.go
  command/agent/operator_endpoint_test.go
  command/agent/region_endpoint.go
  command/agent/region_endpoint_test.go
  command/agent/scaling_endpoint.go
  command/agent/scaling_endpoint_test.go
  command/agent/search_endpoint_test.go
  command/agent/stats_endpoint_test.go
  command/agent/status_endpoint.go
  command/agent/status_endpoint_test.go
  command/agent/system_endpoint.go
  command/agent/system_endpoint_test.go
  command/agent/testagent.go
  command/operator_debug.go
  command/operator_debug_test.go
  testutil/server.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18078 docs: add allocation checks API documentation.
  website/content/api-docs/allocations.mdx
Labels: backport/website, backport/1.4.x, backport/1.5.x, backport/1.6.x

#18081 cli: add help message for `-consul-namespace`
  .changelog/18081.txt
  command/job_run.go
  website/content/docs/commands/job/run.mdx
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18054 feature: Add new field render_templates on restart block
  .changelog/18054.txt
  api/jobs_test.go
  api/tasks.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  client/allocrunner/taskrunner/template_hook.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  command/agent/testingutils_test.go
  command/helpers_test.go
  jobspec/parse_group.go
  jobspec/parse_test.go
  jobspec/test-fixtures/basic.hcl
  jobspec2/parse_test.go
  jobspec2/test-fixtures/restart-render-templates.hcl
  nomad/mock/job.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  scheduler/util.go
  scheduler/util_test.go
  website/content/docs/job-specification/restart.mdx
Labels: theme/template, backport/1.6.x

#18100 scheduler: fix panic in `render_templates` destructive update check
  scheduler/util.go
Labels: type/bug, theme/scheduling

#18053 [ui] Search results are overloading filter with sorted results
  .changelog/18053.txt
  ui/app/controllers/jobs/index.js
  ui/tests/acceptance/jobs-list-test.js
Labels: backport/1.6.x

#18095 cli: support wildcard namespace in alloc subcommands
  .changelog/18095.txt
  command/alloc_exec.go
  command/alloc_exec_test.go
  command/alloc_fs.go
  command/alloc_logs.go
  website/content/docs/commands/alloc/exec.mdx
  website/content/docs/commands/alloc/fs.mdx
  website/content/docs/commands/alloc/logs.mdx
Labels: type/enhancement, theme/cli, theme/allocation API

#17964 [ui] Job Variables page
  .changelog/17964.txt
  ui/app/abilities/job.js
  ui/app/components/editable-variable-link.hbs
  ui/app/components/variable-form.hbs
  ui/app/components/variable-form.js
  ui/app/components/variable-paths.hbs
  ui/app/controllers/jobs/job/variables.js
  ui/app/helpers/editable-variable-link.js
  ui/app/models/job.js
  ui/app/models/task-group.js
  ui/app/models/task.js
  ui/app/router.js
  ui/app/routes/jobs/job/variables.js
  ui/app/styles/components/variables.scss
  ui/app/templates/components/job-subnav.hbs
  ui/app/templates/jobs/job/variables.hbs
  ui/app/templates/variables/variable/index.hbs
  ui/mirage/config.js
  ui/mirage/scenarios/default.js
  ui/tests/acceptance/keyboard-test.js
  ui/tests/acceptance/variables-test.js
  ui/tests/integration/components/job-status-panel-test.js
Labels: backport/1.6.x
