Repository hashicorp/nomad, pull requests merged in 2023-04, with the labels that each got.

#16767 docs: fix use of gpg to avoid teeing binary to terminal
  website/content/docs/install/index.mdx
Labels: theme/docs, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16722 CSI: set mounts in alloc hook resources atomically
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/csi_hook.go
  client/allocrunner/csi_hook_test.go
  client/allocrunner/interfaces/runner.go
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/volume_hook_test.go
  client/pluginmanager/csimanager/interface.go
  client/structs/allochook.go
Labels: type/bug, theme/storage, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16781 cli: fix up failing quota inspect enterprise test.
  command/quota_delete_test.go
  command/quota_inspect_test.go
  command/quota_status_test.go
Labels: backport/1.5.x

#16777 cleanup: use jobID name rather than jobName in job endpoints
  command/agent/job_endpoint.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16761 Prevent kill_timeout greater than progress_deadline
  .changelog/16761.txt
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16791 Do not set attributes when spawning the getter child
  .changelog/16791.txt
  client/allocrunner/taskrunner/getter/testing.go
  client/allocrunner/taskrunner/getter/util.go
  client/allocrunner/taskrunner/getter/util_default.go
  client/allocrunner/taskrunner/getter/util_linux.go
  client/allocrunner/taskrunner/getter/util_windows.go
Labels: backport/1.5.x

#16800 agent: add top-level warning if mTLS is not configured
  command/agent/command.go
Labels: theme/security, theme/config, backport/1.5.x

#16765 docs: remove reference to vSphere from CSI concepts docs
  website/content/docs/concepts/plugins/csi.mdx
Labels: theme/docs, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16796 E2E: test enforcement of ACL system
  e2e/auth/auth_test.go
  e2e/auth/doc.go
  e2e/terraform/scripts/anonymous.nomad_policy.hcl
Labels: theme/security, theme/e2e

#16813 client: ensure envoy version hook uses all pointer receiver funcs.
  client/allocrunner/taskrunner/envoy_version_hook.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16641 [testing] Set RequireRoot to be a test helper
  api/internal/testutil/slow.go
Labels: type/enhancement, theme/testing

#16811 docker: default device.container_path to host_path
  .changelog/16811.txt
  drivers/docker/config.go
  drivers/docker/config_test.go
  drivers/docker/driver.go
  drivers/docker/driver_test.go
Labels: type/enhancement, backport/1.5.x

#16823 E2E: update subset of node drain tests off the old framework
  e2e/nodedrain/doc.go
  e2e/nodedrain/input/drain_ignore_system.nomad
  e2e/nodedrain/input/drain_simple.nomad
  e2e/nodedrain/node_drain_test.go
  e2e/nodedrain/nodedrain.go
Labels: theme/drain, theme/testing, theme/e2e

#16826 ephemeral disk: `migrate` should imply `sticky`
  .changelog/16826.txt
  client/allocwatcher/alloc_watcher.go
  e2e/nodedrain/input/drain_migrate.nomad
  e2e/nodedrain/node_drain_test.go
  e2e/nodedrain/nodedrain.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  scheduler/generic_sched.go
  website/content/docs/job-specification/ephemeral_disk.mdx
Labels: type/enhancement, theme/data migration, theme/drain

#16809 gracefully recover tasks that use csi node plugins
  .changelog/16809.txt
  client/allocrunner/csi_hook.go
  client/allocrunner/csi_hook_test.go
  client/dynamicplugins/registry.go
  client/pluginmanager/csimanager/interface.go
  client/pluginmanager/csimanager/manager.go
  client/pluginmanager/csimanager/manager_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16838 acl: bump JWT auth gate to 1.5.4
  nomad/leader.go
Labels: backport/1.5.x

#16815 consul/connect: fixed a bug where restarting proxy tasks failed.
  .changelog/16815.txt
  client/allocrunner/taskrunner/envoy_version_hook.go
  client/allocrunner/taskrunner/envoy_version_hook_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16835 docs: document signal handling
  website/content/docs/operations/nomad-agent.mdx
Labels: theme/docs, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16792 Deployment Status Command Does Not Respect -namespace Wildcard
  .changelog/16792.txt
  nomad/deployment_endpoint.go
  nomad/deployment_endpoint_test.go
  nomad/state/state_store.go
  nomad/structs/structs.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16859 core: ensure all Server receiver names are consistent.
  nomad/rpc_rate_metrics.go
Labels: backport/1.5.x

#16868 E2E: clarify drain `-deadline` and `-force` flag behaviors
  e2e/e2e_test.go
  e2e/nodedrain/input/drain_deadline.nomad
  e2e/nodedrain/node_drain_test.go
  e2e/nodedrain/nodedrain.go
  website/content/docs/commands/node/drain.mdx
Labels: theme/drain, theme/e2e

#16828 docs: add node meta command docs
  command/node_meta_apply.go
  website/content/docs/commands/node/index.mdx
  website/content/docs/commands/node/meta/apply.mdx
  website/content/docs/commands/node/meta/index.mdx
  website/content/docs/commands/node/meta/read.mdx
  website/data/docs-nav-data.json
Labels: backport/website

#16827 client: allow `drain_on_shutdown` configuration
  .changelog/16827.txt
  client/client.go
  client/config/config.go
  client/config/drain.go
  client/drain.go
  client/drain_test.go
  command/agent/agent.go
  command/agent/config.go
  nomad/fsm.go
  nomad/structs/config/drain.go
  website/content/docs/configuration/client.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/operations/nomad-agent.mdx
  website/content/docs/upgrade/index.mdx
Labels: type/enhancement, theme/drain

#16889 docs: update licensing FAQ to match current documentation
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/enterprise/license/index.mdx
Labels: theme/docs, theme/enterprise

#16907 [scheduler] Honor `false` for distinct hosts constraint
  .changelog/16907.txt
  jobspec2/hcl_conversions.go
  scheduler/feasible.go
  scheduler/feasible_test.go
Labels: type/bug, theme/scheduling

#16918 ui: fix notification service in token controller
  ui/app/controllers/settings/tokens.js
Labels: backport/1.5.x

#16923 rpc: use "+" concatenations in hot path RPC rate limit metrics.
  nomad/structs/structs.go
  nomad/structs/structs_test.go
Labels: backport/1.5.x

#16921 allocrunner: prevent panic on network manager
  .changelog/16921.txt
  client/allocrunner/network_manager_linux.go
  client/allocrunner/network_manager_linux_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16328 docs: Updates to the UI block
  website/content/docs/configuration/ui.mdx
Labels: backport/website, backport/1.5.x

#16930 docs: add missing API field JobACL and fix workload identity headers
  website/content/api-docs/acl/policies.mdx
  website/content/docs/concepts/workload-identity.mdx
Labels: backport/website, backport/1.4.x, backport/1.5.x

#16071 changelog: add changelog update for vendor label for linux packaging
  .changelog/16071.txt
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16931 docs: add missing field Capabilities to Namespace API
  website/content/api-docs/namespaces.mdx
Labels: backport/website, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16900 Update util_linux.go
  .changelog/16900.txt
  client/allocrunner/taskrunner/getter/util_linux.go
Labels: backport/1.5.x

#16946 docs: fix keyring path in install docs
  website/content/docs/install/index.mdx
Labels: theme/docs, backport/website, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16944 cli: fix panic on job plan when -diff=false
  .changelog/16944.txt
  command/job_plan.go
Labels: backport/1.5.x

#16776 cni: fix plugin fingerprinting versions
  .changelog/16776.txt
  client/fingerprint/plugins_cni.go
  client/fingerprint/plugins_cni_test.go
  client/fingerprint/test_fixtures/cni/bridge
  client/fingerprint/test_fixtures/cni/vlan
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16723 fix host port handling for ipv6, fixes #16550
  .changelog/16723.txt
  client/taskenv/env.go
  client/taskenv/env_test.go
  command/agent/agent_endpoint_test.go
  nomad/job_endpoint_hook_connect.go
  nomad/structs/diff.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16905 services: un-mark group services as deregistered if restart hook runs
  .changelog/16905.txt
  client/allocrunner/group_service_hook.go
  e2e/consul/alloc_restart_test.go
  e2e/consul/consul_test.go
  e2e/consul/input/alloc_restart.hcl
  e2e/consul/service_revert_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16969 scale: do not allow scaling of jobs with type system.
  .changelog/16969.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16995 vars: ensure struct receiver names are consistent.
  nomad/structs/variables.go
Labels: backport/1.5.x

#16960 [ui] Fixed: Evaluations sidebar/response not scrollable
  .changelog/16960.txt
  ui/app/components/evaluation-sidebar/detail.hbs
  ui/app/styles/components/sidebar.scss
Labels: theme/ui, backport/1.5.x

#16990 testing: improve fidelity of mock driver task restore
  drivers/mock/driver.go
  drivers/mock/driver_test.go
Labels: theme/driver, theme/client-restart, theme/testing, backport/1.5.x

#17005 docs: add more notes about artifact breaking changes in 1.5.0
  .changelog/15514.txt
  CHANGELOG.md
  website/content/docs/job-specification/artifact.mdx
Labels: backport/website, backport/1.5.x
