Repository hashicorp/nomad, pull requests merged in 2023-03, with the labels that each got.

#16217 client: use RPC address and not serf after initial Consul discovery
  .changelog/16217.txt
  client/client.go
Labels: type/bug, theme/client, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16292 deps: update go-plugin to 1.4.9
  go.mod
  go.sum
Labels: backport/1.3.x, backport/1.4.x, dependencies, backport/1.5.x

#16287 handle `FSM.Apply` errors in `raftApply`
  .changelog/16287.txt
  api/jobs_test.go
  api/nodes_test.go
  nomad/acl_endpoint.go
  nomad/csi_endpoint.go
  nomad/drainer_shims.go
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  nomad/keyring_endpoint.go
  nomad/namespace_endpoint.go
  nomad/operator_endpoint.go
  nomad/periodic.go
  nomad/rpc.go
  nomad/service_registration_endpoint.go
Labels: type/bug, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16243 Add namespace argument to the job verification help text
  .changelog/16243.txt
  command/job_plan.go
Labels: theme/cli

#16309 docs: fix typos in task-api.mdx and workload-identity.mdx
  website/content/api-docs/task-api.mdx
  website/content/docs/concepts/workload-identity.mdx
Labels: theme/docs, backport/website, backport/1.5.x

#16316 service: fix regression in task access to list/read endpoint
  .changelog/16316.txt
  nomad/service_registration_endpoint.go
  nomad/service_registration_endpoint_test.go
Labels: type/bug, theme/auth, backport/1.5.x

#16306 cli: use shared logic for resolving job prefix
  .changelog/16306.txt
  command/job_allocs.go
  command/job_allocs_test.go
  command/job_deployments.go
  command/job_deployments_test.go
  command/job_dispatch.go
  command/job_dispatch_test.go
  command/job_eval.go
  command/job_history.go
  command/job_history_test.go
  command/job_inspect.go
  command/job_inspect_test.go
  command/job_periodic_force.go
  command/job_periodic_force_test.go
  command/job_promote.go
  command/job_promote_test.go
  command/job_revert.go
  command/job_revert_test.go
  command/job_scale.go
  command/job_scaling_events.go
  command/job_status.go
  command/job_stop.go
  command/job_stop_test.go
  command/meta.go
  command/meta_test.go
Labels: backport/1.5.x

#16282 docs: fix alloc stop `no_shutdown_delay`
  command/alloc_stop.go
  website/content/api-docs/allocations.mdx
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16305 remove backcompat support for non-atomic job registration
  .changelog/16305.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  nomad/leader.go
  nomad/periodic.go
Labels: theme/tech-debt, backport/1.5.x

#16281 client: don't emit task shutdown delay event if not waiting
  .changelog/16281.txt
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/task_runner_test.go
  nomad/structs/structs.go
Labels: backport/1.5.x

#16274 [ui] Fix: Wildcard-datacenter system/sysbatch jobs stopped showing client links/chart
  .changelog/16274.txt
  ui/app/abilities/variable.js
  ui/app/utils/match-glob.js
  ui/app/utils/properties/job-client-status.js
  ui/tests/acceptance/job-detail-test.js
  ui/tests/helpers/module-for-job.js
  ui/tests/unit/abilities/variable-test.js
  ui/tests/unit/utils/match-glob-test.js
Labels: backport/1.5.x

#16362 scheduler: correctly detect inplace update with wildcard datacenters
  .changelog/16362.txt
  nomad/node_endpoint.go
  nomad/structs/structs.go
  scheduler/util.go
  scheduler/util_test.go
Labels: type/bug, theme/scheduling, backport/1.5.x

#16363 docs: note that secrets dir is usually mounted `noexec`
  website/content/docs/concepts/filesystem.mdx
  website/content/docs/job-specification/template.mdx
  website/content/docs/runtime/environment.mdx
Labels: theme/docs, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16357 cli: support `json` and `t` on `acl binding-rule info` command.
  .changelog/16357.txt
  command/acl_binding_rule_info.go
  command/acl_binding_rule_info_test.go
Labels: backport/1.5.x

#16358 docs: add 1.5.0, 1.4.5, and 1.3.10 pause regression upgrade note.
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/website, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16332 deps: Update ioutil library references to os and io respectively for e2e helper nomad
  demo/digitalocean/app/bench.go
  e2e/clientstate/clientstate.go
  e2e/csi/csi.go
  e2e/e2eutil/job.go
  e2e/execagent/execagent.go
  e2e/metrics/prometheus.go
  e2e/vaultcompat/vault_test.go
  e2e/vaultsecrets/vaultsecrets.go
  helper/escapingfs/escapes_test.go
  helper/pluginutils/loader/loader_test.go
  helper/snapshot/archive.go
  helper/snapshot/archive_test.go
  helper/snapshot/snapshot.go
  helper/testtask/testtask.go
  jobspec2/parse.go
  jobspec2/parse_test.go
  nomad/acl_endpoint.go
  nomad/acl_endpoint_test.go
  nomad/event_endpoint.go
  nomad/operator_endpoint_test.go
  nomad/rpc_test.go
  nomad/server.go
  testutil/server.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16318 deps: Update ioutil deprecated library references to os and io respectively in the client package
  client/alloc_watcher_e2e_test.go
  client/allocdir/alloc_dir.go
  client/allocdir/alloc_dir_test.go
  client/allocdir/task_dir.go
  client/allocdir/task_dir_test.go
  client/allocdir/testing.go
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/taskrunner/artifact_hook_test.go
  client/allocrunner/taskrunner/connect_native_hook.go
  client/allocrunner/taskrunner/connect_native_hook_test.go
  client/allocrunner/taskrunner/dispatch_hook.go
  client/allocrunner/taskrunner/dispatch_hook_test.go
  client/allocrunner/taskrunner/envoy_bootstrap_hook.go
  client/allocrunner/taskrunner/envoy_bootstrap_hook_test.go
  client/allocrunner/taskrunner/sids_hook.go
  client/allocrunner/taskrunner/sids_hook_test.go
  client/allocrunner/taskrunner/task_runner_test.go
  client/allocrunner/taskrunner/vault_hook.go
  client/allocwatcher/alloc_watcher_test.go
  client/allocwatcher/alloc_watcher_unix_test.go
  client/client.go
  client/config/testing.go
  client/fingerprint/bridge_linux_test.go
  client/fingerprint/consul_test.go
  client/fingerprint/env_azure.go
  client/fingerprint/env_digitalocean.go
  client/fingerprint/env_gce.go
  client/fingerprint/network_linux.go
  client/fs_endpoint_test.go
  client/lib/cgutil/cpuset_manager_v1.go
  client/lib/cgutil/cpuset_manager_v1_test.go
  client/logmon/logging/rotator.go
  client/logmon/logging/rotator_test.go
  client/logmon/logmon_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16339 docs: Updated who-uses-nomad to add Behavox
  website/content/docs/who-uses-nomad.mdx
Labels: backport/website

#16401 scheduling: prevent self-collision in dynamic port network offerings
  .changelog/16401.txt
  nomad/structs/bitmap.go
  nomad/structs/network.go
  nomad/structs/network_test.go
  scheduler/generic_sched_test.go
  scheduler/rank.go
Labels: type/bug, theme/scheduling, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16407 cli: fix help output format on `job init` command.
  command/job_init.go
Labels: backport/1.5.x

#16412 docs: update content-conformance package
  website/package-lock.json
  website/package.json
Labels: theme/website

#16380 cli: remove hard requirement on `list-jobs`
  .changelog/16380.txt
  command/job_allocs.go
  command/job_allocs_test.go
  command/job_deployments.go
  command/job_deployments_test.go
  command/job_dispatch.go
  command/job_dispatch_test.go
  command/job_eval.go
  command/job_eval_test.go
  command/job_history.go
  command/job_history_test.go
  command/job_inspect.go
  command/job_inspect_test.go
  command/job_periodic_force.go
  command/job_periodic_force_test.go
  command/job_promote.go
  command/job_promote_test.go
  command/job_revert.go
  command/job_revert_test.go
  command/job_scale.go
  command/job_scale_test.go
  command/job_scaling_events.go
  command/job_scaling_events_test.go
  command/job_status.go
  command/job_status_test.go
  command/job_stop.go
  command/job_stop_test.go
  command/meta.go
  command/testing_test.go
  website/content/docs/commands/job/allocs.mdx
  website/content/docs/commands/job/deployments.mdx
  website/content/docs/commands/job/dispatch.mdx
  website/content/docs/commands/job/eval.mdx
  website/content/docs/commands/job/history.mdx
  website/content/docs/commands/job/inspect.mdx
  website/content/docs/commands/job/periodic-force.mdx
  website/content/docs/commands/job/promote.mdx
  website/content/docs/commands/job/revert.mdx
  website/content/docs/commands/job/scale.mdx
  website/content/docs/commands/job/scaling-events.mdx
  website/content/docs/commands/job/status.mdx
  website/content/docs/commands/job/stop.mdx
Labels: backport/1.5.x

#16405 cli: add `-json` and `-t` flag for `alloc checks` command
  .changelog/16405.txt
  command/alloc_checks.go
  command/alloc_checks_test.go
  website/content/docs/commands/alloc/checks.mdx
  website/content/docs/commands/alloc/index.mdx
  website/data/docs-nav-data.json
Labels: backport/1.5.x

#16402 allocrunner: fix health check monitoring for Consul services
  .changelog/16402.txt
  client/allochealth/tracker.go
  client/allochealth/tracker_test.go
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/health_hook.go
  client/allocrunner/health_hook_test.go
  client/taskenv/services.go
  nomad/mock/alloc.go
Labels: backport/1.4.x, backport/1.5.x

#16304 deps: remove replace statement for go-discover
  go.mod
Labels: backport/1.4.x, backport/1.5.x

#16422 scheduler: add simple benchmark for tasksUpdated
  nomad/mock/job.go
  scheduler/util_test.go
Labels: backport/1.5.x

#16416 scheduler: refactor system util tests
  nomad/structs/structs.go
  scheduler/system_util_test.go
Labels: theme/scheduling, theme/testing, backport/1.5.x

#16427 build: update from go1.20.1 to go1.20.2
  .changelog/16427.txt
  .circleci/config.yml
  .go-version
  contributing/README.md
  scripts/release/mac-remote-build
  scripts/vagrant-linux-priv-go.sh
Labels: backport/1.3.x, backport/1.4.x, dependencies, backport/1.5.x

#16435 doc: Update `nomad fmt` doc to run against non-deprecated HCL2 jobspec only
  website/content/docs/commands/fmt.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x

#16434 plugin: add missing fields to `TaskConfig`
  .changelog/16434.txt
  plugins/drivers/proto/driver.pb.go
  plugins/drivers/proto/driver.proto
  plugins/drivers/utils.go
  plugins/drivers/utils_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16467 cgv1: do not disable cpuset manager if reserved interface already exists
  .changelog/16467.txt
  client/lib/cgutil/cpuset_manager_v1.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16469 agent: trim space when parsing X-Nomad-Token header
  .changelog/16469.txt
  command/agent/http.go
  command/agent/http_test.go
Labels: type/enhancement, backport/1.5.x

#16484 Update for enterprise trial wording and link
  website/content/docs/enterprise/license/index.mdx
Labels: theme/website, backport/website, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16421 scheduler: annotate tasksUpdated with reason and purge DeepEquals
  .changelog/16421.txt
  contributing/checklist-jobspec.md
  helper/opaque.go
  helper/opaque_test.go
  nomad/structs/csi.go
  nomad/structs/csi_test.go
  nomad/structs/services.go
  nomad/structs/structs.go
  nomad/structs/structs_test.go
  nomad/structs/volume_test.go
  nomad/structs/volumes.go
  scheduler/util.go
  scheduler/util_test.go
Labels: backport/1.5.x

#16502 cli: fix login command help output formatting.
  command/login.go
Labels: backport/1.5.x

#16506 build: fix `test-nomad` make target when running locally.
  GNUmakefile
Labels: backport/1.5.x

#16514 docs: dispatch_payload and jobs api docs had some weirdness
  website/content/api-docs/jobs.mdx
  website/content/docs/job-specification/dispatch_payload.mdx
Labels: theme/website, backport/website

#16490 client: use `Status.RPCServers` RPC for Consul discovery
  .changelog/16490.txt
  client/client.go
Labels: type/bug, theme/discovery, theme/auth, backport/1.5.x

#16273 docs: add binding-rule selector escape example on Windows PS
  website/content/docs/commands/acl/binding-rule/create.mdx
Labels: backport/website

#16534 acl: fix canonicalization of OIDC auth method mock
  nomad/mock/acl.go
Labels: backport/1.5.x

#16289 nsd: always set deregister flag after deregistration of group
  .changelog/16289.txt
  client/allocrunner/group_service_hook.go
  client/allocrunner/group_service_hook_test.go
  client/serviceregistration/nsd/nsd.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16504 cli: nomad login command should not require a -type flag and should respect default auth method
  .changelog/16504.txt
  command/login.go
  command/login_test.go
  website/content/docs/commands/login.mdx
Labels: backport/1.5.x

#16543 tls enforcement flaky tests
  nomad/rpc_test.go
  nomad/testing.go
  testutil/wait.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16553 Spelling update
  website/content/docs/concepts/plugins/task-drivers.mdx
Labels: backport/website

#16444 cli: Add `json` and `-t` flags to `server members` command
  .changelog/16444.txt
  command/server_members.go
  command/server_members_test.go
  website/content/docs/commands/server/members.mdx
Labels: backport/1.5.x

#16485 cli: add `-json` and `-t` flags to `quota status` command
  .changelog/16485.txt
  command/quota_status.go
  command/quota_status_test.go
  website/content/docs/commands/quota/status.mdx
Labels: backport/1.5.x

#16478 Add `-json` flag to `quota inspect` command
  .changelog/16478.txt
  api/util_test.go
  command/quota_inspect.go
  command/quota_inspect_test.go
  website/content/docs/commands/quota/inspect.mdx
Labels: backport/1.5.x

#16378 [ui] Perform common job tasks with keyboard shortcuts
  .changelog/16378.txt
  ui/app/components/job-page/parts/title.js
  ui/app/controllers/jobs/index.js
  ui/app/services/keyboard.js
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/components/exec/open-button.hbs
  ui/app/templates/components/job-page/parts/title.hbs
  ui/app/templates/jobs/index.hbs
Labels: backport/1.5.x

#16555 docs: remove Java and Scala SDKs from supported list.
  website/content/api-docs/libraries-and-sdks.mdx
Labels: backport/website, backport/1.5.x

#16573 contrib: developer docs for `mock_driver`
  contributing/mock-driver.md
Labels: theme/docs

#16549 client/metadata: fix crasher caused by AllowStale = false
  .changelog/16549.txt
  api/allocations.go
  api/api.go
  api/node_meta.go
  command/agent/meta_endpoint.go
  contributing/checklist-rpc-endpoint.md
  go.mod
  go.sum
  nomad/client_meta_endpoint.go
  nomad/client_meta_endpoint_test.go
  nomad/structs/node.go
  nomad/testing.go
  testutil/wait.go
Labels: theme/crash, backport/1.5.x

#16565 changelog: update #16427 to improvement
  .changelog/16427.txt
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16569 contrib: architecture guide to the drainer
  contributing/architecture-drainer.md
Labels: theme/docs, theme/drain

#16584 Update csi_plugin.mdx
  website/content/docs/job-specification/csi_plugin.mdx
Labels: backport/website, backport/1.5.x

#16595 E2E: fix events tests
  e2e/events/events.go
  e2e/events/input/deploy.nomad
  e2e/events/input/initial.nomad
Labels: theme/testing

#16594 taskapi: use HasSuffix to detect errors from rpcs
  command/agent/http.go
Labels: backport/1.5.x

#16598 docs: detail support for Nomad checks in service block.
  website/content/docs/job-specification/service.mdx
Labels: backport/website, backport/1.4.x, backport/1.5.x

#16610 Fix broken test for quotas CLI
  command/quota_inspect_test.go
  command/quota_status_test.go
Labels: backport/1.5.x

#16548 [ui] Copyable server and client attribute values
  .changelog/16548.txt
  ui/app/components/copy-button.js
  ui/app/components/metadata-kv.hbs
  ui/app/styles/components/copy-button.scss
  ui/app/styles/core/buttons.scss
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/components/attributes-section.hbs
  ui/app/templates/components/attributes-table.hbs
  ui/app/templates/components/copy-button.hbs
  ui/app/templates/servers/server/index.hbs
Labels: backport/1.5.x

#16278 cli: job restart command
  .changelog/16278.txt
  api/tasks.go
  command/commands.go
  command/helpers.go
  command/job_restart.go
  command/job_restart_test.go
  command/meta.go
  command/testing_test.go
  website/content/docs/commands/job/restart.mdx
  website/data/docs-nav-data.json
Labels: theme/cli, backport/1.5.x

#16494 Added section of needed rules for Nomad UI
  website/content/docs/other-specifications/acl-policy.mdx
Labels: theme/docs, theme/ui, theme/auth, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16609 scheduler: fix reconciliation of reconnecting allocs
  .changelog/16609.txt
  scheduler/reconcile.go
  scheduler/reconcile_test.go
  scheduler/reconcile_util.go
Labels: hcc/cst, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16617 style: rename ForceRun to ForceEval, for clarity
  nomad/leader.go
  nomad/periodic.go
  nomad/periodic_endpoint.go
  nomad/periodic_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16583 Multiple instances of a periodic job are run simultaneously, when prohibit_overlap is true
  .changelog/16583.txt
  nomad/leader.go
  nomad/leader_test.go
Labels: hcc/cst, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16673 docs: fix link of Read Stats API
  website/content/docs/configuration/client.mdx
Labels: backport/website, backport/1.5.x

#16678 docs: fix-up legacy link in client config page.
  website/content/docs/configuration/client.mdx
Labels: backport/website, backport/1.5.x

#16667 docs: fix template retry attempts default documentation
  website/content/docs/configuration/client.mdx
Labels: theme/docs, theme/config, theme/template, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16672 client/fingerprint: correctly fingerprint E/P cores of Apple Silicon chips
  .changelog/16672.txt
  api/go.mod
  api/go.sum
  client/fingerprint/cpu.go
  client/fingerprint/cpu_darwin_test.go
  client/fingerprint/cpu_default.go
  client/fingerprint/cpu_default_test.go
  client/fingerprint/cpu_linux.go
  client/stats/cpu.go
  drivers/docker/util/stats_posix.go
  drivers/docker/util/stats_windows.go
  go.mod
  go.sum
  helper/stats/cpu.go
  helper/stats/cpu_darwin_test.go
Labels: backport/1.5.x

#16693 docs: clarify capabilities options for `docker` driver
  website/content/docs/drivers/docker.mdx
Labels: theme/docs, theme/driver/docker, backport/1.3.x, backport/1.4.x, backport/1.5.x

#16702 docs: mention Nomad Admission Control Proxy
  website/content/tools/index.mdx
Labels: backport/website, backport/1.5.x

#16619 Clean the output writter to avoid duplicates when testing for json output
  command/quota_inspect_test.go
Labels: backport/1.5.x

#15897 acl: JWT as SSO auth method
  .changelog/15897.txt
  .semgrep/rpc_endpoint.yml
  api/acl.go
  command/acl_auth_method.go
  command/acl_auth_method_create.go
  command/acl_auth_method_create_test.go
  command/acl_auth_method_update.go
  command/agent/acl_endpoint.go
  command/agent/acl_endpoint_test.go
  command/agent/http.go
  command/login.go
  command/login_test.go
  internal/testing/apitests/acl_test.go
  lib/auth/binder.go
  lib/auth/binder_test.go
  lib/auth/claims.go
  lib/auth/claims_test.go
  lib/auth/identity.go
  lib/auth/identity_test.go
  lib/auth/jwt/validator.go
  lib/auth/jwt/validator_test.go
  nomad/acl_endpoint.go
  nomad/acl_endpoint_test.go
  nomad/fsm_test.go
  nomad/leader.go
  nomad/leader_test.go
  nomad/mock/acl.go
  nomad/state/events_test.go
  nomad/state/state_store_acl_binding_rule_test.go
  nomad/state/state_store_acl_sso_test.go
  nomad/state/state_store_restore_test.go
  nomad/structs/acl.go
  ui/app/adapters/token.js
  ui/app/controllers/settings/tokens.js
  ui/app/models/auth-method.js
  ui/app/styles/components/authorization.scss
  ui/app/templates/settings/tokens.hbs
  ui/jsconfig.json
  ui/mirage/config.js
  ui/mirage/scenarios/default.js
  ui/tests/acceptance/token-test.js
  website/content/api-docs/acl/auth-methods.mdx
  website/content/docs/commands/acl/auth-method/create.mdx
  website/content/docs/commands/acl/auth-method/update.mdx
Labels: theme/auth, backport/1.5.x

#16740 take maximum processor Mhz
  .changelog/16740.txt
  helper/stats/cpu.go
Labels: backport/1.5.x
