Repository hashicorp/nomad, pull requests merged in 2023-01, with the labels that each got.

#15643 docs: fix service name interpolation key details.
  website/content/docs/job-specification/service.mdx
Labels: backport/website, backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15650 docs: fix system sample request
  website/content/api-docs/system.mdx
Labels: theme/docs, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15667 [doc] nomad `eval delete` example typo fix
  website/content/docs/commands/eval/delete.mdx
Labels: theme/docs, backport/1.3.x, backport/1.4.x

#15670 csi: Fix parsing of '=' in secrets at command line and HTTP
  .changelog/15670.txt
  command/agent/csi_endpoint.go
  command/agent/csi_endpoint_test.go
  command/volume_delete.go
  command/volume_snapshot_create.go
  command/volume_snapshot_delete.go
  command/volume_snapshot_list.go
Labels: type/bug, theme/cli, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15672 tests: fix assertion for slice length
  api/jobs_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15677 test: wait for node in api tests that register job
  api/allocations_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15625 fix: Make agent syslog log level inherit from Nomad agent log
  .changelog/15625.txt
  command/agent/command.go
  website/content/docs/configuration/index.mdx
Labels: type/bug, theme/config, theme/logging, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15690 CI: run tests on pull_request and push to main/release
  .github/workflows/test-core.yaml
Labels: theme/testing, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15695 docs: clarify shutdown_delay jobspec param and service behaviour.
  website/content/docs/job-specification/group.mdx
  website/content/docs/job-specification/task.mdx
Labels: backport/website, backport/1.3.x, backport/1.4.x

#15358 docs: networking
  website/content/docs/concepts/plugins/cni.mdx
  website/content/docs/configuration/client.mdx
  website/content/docs/job-specification/network.mdx
  website/content/docs/networking/cni.mdx
  website/content/docs/networking/index.mdx
  website/content/docs/networking/service-discovery.mdx
  website/content/docs/networking/service-mesh.mdx
  website/content/docs/runtime/environment.mdx
  website/content/partials/envvars.mdx
  website/data/docs-nav-data.json
  website/public/img/networking/bridge.png
  website/public/img/networking/docker_bridge.png
  website/public/img/networking/port_mapping.png
  website/public/img/nomad-bridge-network.png
Labels: backport/website, backport/1.4.x

#15737 Update template.mdx
  website/content/docs/job-specification/template.mdx
Labels: backport/website, backport/1.4.x

#15732 docker: configure restart policy for networking pause container
  .changelog/15732.txt
  drivers/docker/network.go
  drivers/docker/network_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15734 Authenticate method improvements
  .semgrep/rpc_endpoint.yml
  nomad/acl.go
  nomad/acl_endpoint.go
  nomad/acl_test.go
  nomad/namespace_endpoint.go
  nomad/structs/structs.go
Labels: theme/auth

#15455 scheduler: allow using device ID as attribute
  .changelog/15455.txt
  scheduler/feasible.go
  scheduler/feasible_test.go
  website/content/docs/job-specification/device.mdx
Labels: backport/1.4.x

#15735 [ui] Task Logs sidebar expansion button
  .changelog/15735.txt
  ui/app/components/task-context-sidebar.hbs
  ui/app/components/task-context-sidebar.js
  ui/app/styles/components/sidebar.scss
Labels: backport/1.4.x

#15733 [ui] Show task events in the sidebar
  .changelog/15733.txt
  ui/app/components/task-context-sidebar.hbs
  ui/app/styles/components/sidebar.scss
Labels: backport/1.4.x

#15552 Fix rejoin_after_leave behavior
  .changelog/15552.txt
  command/agent/agent.go
  command/agent/config.go
  nomad/server.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: type/bug

#15769 build: update to go 1.19.5
  .changelog/15769.txt
  .circleci/config.yml
  .go-version
  contributing/README.md
  scripts/release/mac-remote-build
  scripts/vagrant-linux-priv-go.sh
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15770 env/aws: update ec2 cpu info data
  .changelog/15770.txt
  client/fingerprint/env_aws_cpu.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15558 Return buffered text from log endpoint if decoding fails
  .changelog/15558.txt
  api/fs.go
  api/go.mod
  api/go.sum
Labels: backport/1.4.x

#15785 docs: add missing parameter `propagation_mode` to `volume_mount`
  website/content/docs/job-specification/volume_mount.mdx
Labels: backport/website, backport/1.0.x, backport/1.1.x, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15810 [docs] Adjusting links for rewrite project
  website/content/docs/faq.mdx
  website/content/docs/install/index.mdx
  website/content/docs/job-specification/upstreams.mdx
  website/content/docs/partnerships.mdx
  website/content/plugins/drivers/remote/index.mdx
Labels: theme/docs

#15784 [website] chore: updates generated docs
  website/README.md
  website/package-lock.json
  website/package.json
Labels: theme/website, backport/website

#15822 consul: correctly interpret missing consul checks as unhealthy
  .changelog/15822.txt
  client/allochealth/tracker.go
  client/allochealth/tracker_test.go
  client/serviceregistration/service_registration.go
  nomad/structs/structs.go
Labels: backport/1.4.x

#15833 docs: clarify installing from source requirement on PATH.
  website/content/docs/install/index.mdx
Labels: backport/website

#15805 Clarify conflicting metric documentation, fix typo
  website/content/docs/operations/metrics-reference.mdx
Labels: theme/docs, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15522 Add raft snapshot configuration options
  .changelog/15522.txt
  command/agent/agent.go
  command/agent/agent_test.go
  command/agent/config.go
  nomad/server.go
  nomad/server_test.go
  website/content/docs/configuration/server.mdx
Labels: type/enhancement, theme/raft, hcc/cst

#15835 Rename `nomad.broker.total_blocked` metric
  .changelog/15835.txt
  nomad/eval_broker.go
  nomad/eval_broker_test.go
  website/content/docs/operations/metrics-reference.mdx
  website/content/docs/operations/monitoring-nomad.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: type/enhancement, theme/scheduling, theme/metrics

#15841 docs: backport fix for metrics on blocked_evals vs broker
  website/content/docs/operations/monitoring-nomad.mdx
Labels: theme/docs, backport/1.2.x, backport/1.3.x

#15842 Add INFO task even log line and make logmon less noisy
  .changelog/15842.txt
  client/allocrunner/taskrunner/task_runner.go
  client/logmon/logmon.go
Labels: type/enhancement, theme/client, theme/logging

#15513 implement pre-forwarding auth on select RPCs
  client/client_test.go
  client/rpc.go
  command/agent/agent_test.go
  nomad/deployment_endpoint.go
  nomad/eval_endpoint.go
  nomad/namespace_endpoint.go
  nomad/node_endpoint.go
  nomad/rpc_test.go
  nomad/server_test.go
  nomad/status_endpoint.go
  nomad/status_endpoint_test.go
  nomad/variables_endpoint.go
  nomad/variables_endpoint_test.go
Labels: type/enhancement, theme/auth

#15819 Adds docker isolation option
  .changelog/15819.txt
  drivers/docker/config.go
  drivers/docker/driver.go
  website/content/docs/drivers/docker.mdx
Labels: type/enhancement, theme/driver/docker

#15863 acl: Fix panic when bogus token is passed
  nomad/acl.go
  nomad/acl_test.go
  nomad/namespace_endpoint_test.go
Labels: type/bug, theme/auth

#15870 WI: allow workloads to use RPCs associated with HTTP API
  .changelog/15870.txt
  .semgrep/rpc_endpoint.yml
  nomad/acl.go
  nomad/acl_endpoint.go
  nomad/acl_endpoint_test.go
  nomad/alloc_endpoint.go
  nomad/alloc_endpoint_test.go
  nomad/client_agent_endpoint.go
  nomad/client_alloc_endpoint.go
  nomad/client_fs_endpoint.go
  nomad/client_stats_endpoint.go
  nomad/csi_endpoint.go
  nomad/deployment_endpoint.go
  nomad/eval_endpoint.go
  nomad/event_endpoint.go
  nomad/job_endpoint.go
  nomad/keyring_endpoint.go
  nomad/namespace_endpoint.go
  nomad/node_endpoint.go
  nomad/operator_endpoint.go
  nomad/operator_endpoint_test.go
  nomad/periodic_endpoint.go
  nomad/scaling_endpoint.go
  nomad/search_endpoint.go
  nomad/service_registration_endpoint.go
  nomad/status_endpoint.go
  nomad/system_endpoint.go
  nomad/variables_endpoint.go
Labels: type/enhancement, theme/auth

#15808 core: enforce strict steps for clients reconnect
  .changelog/15808.txt
  nomad/fsm_test.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/structs.go
  testutil/wait.go
Labels: backport/1.3.x, backport/1.4.x

#15857 docs: add caveat on dynamic blocks
  website/content/docs/job-specification/hcl2/expressions.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15876 metrics: measure rate of RPC requests that serve API
  .changelog/15876.txt
  nomad/acl_endpoint.go
  nomad/alloc_endpoint.go
  nomad/client_agent_endpoint.go
  nomad/client_alloc_endpoint.go
  nomad/client_fs_endpoint.go
  nomad/client_stats_endpoint.go
  nomad/csi_endpoint.go
  nomad/deployment_endpoint.go
  nomad/eval_endpoint.go
  nomad/event_endpoint.go
  nomad/job_endpoint.go
  nomad/keyring_endpoint.go
  nomad/namespace_endpoint.go
  nomad/node_endpoint.go
  nomad/operator_endpoint.go
  nomad/periodic_endpoint.go
  nomad/scaling_endpoint.go
  nomad/search_endpoint.go
  nomad/service_registration_endpoint.go
  nomad/status_endpoint.go
  nomad/system_endpoint.go
  nomad/variables_endpoint.go
Labels: type/enhancement, theme/metrics

#15421 docs: correct "User" attribute in Podman Task Driver Docs
  website/content/plugins/drivers/podman.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15780 Allow per_alloc to be used with host volumes
  .changelog/15780.txt
  client/allocrunner/interfaces/task_lifecycle.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  client/allocrunner/taskrunner/volume_hook.go
  nomad/structs/volume_test.go
  nomad/structs/volumes.go
  scheduler/feasible.go
  scheduler/feasible_test.go
  scheduler/stack.go
  website/content/docs/job-specification/update.mdx
  website/content/docs/job-specification/volume.mdx
Labels: type/enhancement, stage/waiting-reply, theme/storage

#15900 metrics: Add RPC rate metrics to endpoints that validate TLS names
  .semgrep/rpc_metrics.yml
  nomad/alloc_endpoint.go
  nomad/deployment_endpoint.go
  nomad/eval_endpoint.go
  nomad/keyring_endpoint.go
  nomad/node_endpoint.go
  nomad/plan_endpoint.go
  nomad/service_registration_endpoint.go
Labels: type/enhancement, theme/metrics

#15899 metrics: Add metrics to unauthenticated endpoints
  nomad/regions_endpoint.go
  nomad/stats_fetcher.go
  nomad/status_endpoint.go
Labels: type/enhancement, theme/metrics

#15906 ui: fix navigation for namespaced jobs in search and job version
  .changelog/15906.txt
  ui/app/components/global-search/control.js
  ui/app/components/gutter-menu.js
  ui/app/components/job-version.js
  ui/tests/acceptance/job-versions-test.js
  ui/tests/acceptance/search-test.js
Labels: backport/1.3.x, backport/1.4.x

#15905 metrics: Add rate metrics to Client CSI endpoints
  nomad/client_csi_endpoint.go
  nomad/client_csi_endpoint_test.go
  nomad/server.go
Labels: type/enhancement, theme/metrics, theme/auth

#15909 ui: fix alloc memory stats to match CLI output
  .changelog/15909.txt
  ui/app/utils/classes/allocation-stats-tracker.js
  ui/tests/unit/utils/allocation-stats-tracker-test.js
Labels: backport/1.3.x, backport/1.4.x

#15901 metrics: Add remaining server RPC rate metrics
  .semgrep/rpc_endpoint.yml
  client/alloc_endpoint_test.go
  command/agent/agent_endpoint_test.go
  command/agent/alloc_endpoint_test.go
  command/agent/stats_endpoint_test.go
  nomad/acl_endpoint.go
Labels: type/enhancement, theme/metrics, theme/auth

#15915 template: restore driver handle on update
  .changelog/15915.txt
  client/allocrunner/taskrunner/template_hook.go
Labels: backport/1.3.x, backport/1.4.x

#15926 docs: add more warnings about running agent as root on Linux
  website/content/docs/commands/agent.mdx
  website/content/docs/install/index.mdx
  website/content/docs/install/quickstart.mdx
  website/content/docs/operations/nomad-agent.mdx
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15928 consul: check for acceptable service identity on consul tokens
  .changelog/15928.txt
  command/agent/consul/acl_testing.go
  nomad/consul_policy.go
  nomad/consul_policy_oss_test.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15940 Fix documentation for `meta` block: string replacement in key from `-` to `_`
  website/content/docs/job-specification/meta.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15541 Rename fields on proxyConfig
  .changelog/15541.txt
  api/consul.go
  api/consul_test.go
  command/agent/job_endpoint.go
  command/agent/job_endpoint_test.go
  jobspec/parse_service.go
  jobspec/parse_test.go
  nomad/structs/services.go
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15898 Ensure infra_image gets proper label used for reconciliation
  .changelog/15898.txt
  drivers/docker/network.go
  drivers/docker/network_test.go
Labels: type/bug, theme/driver/docker, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15966 docs: Add info about variable item key name restrictions
  website/content/docs/commands/var/put.mdx
Labels: type/enhancement, theme/docs, theme/variables

#15968 docs: Fix broken link on job-specification/checks page
  website/content/docs/job-specification/check.mdx
Labels: theme/docs

#15970 Fix typo in documentation
  website/content/tools/index.mdx
Labels: backport/website, backport/1.2.x, backport/1.3.x, backport/1.4.x

#15962 docker: set force=true on remove image to handle images referenced by multiple tags
  .changelog/15962.txt
  drivers/docker/coordinator.go
  drivers/docker/coordinator_test.go
  website/content/docs/drivers/docker.mdx
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x

#15097 [15090] Ensure no leakage of evaluations for batch jobs.
  .changelog/15097.txt
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_test.go
  nomad/config.go
  nomad/core_sched.go
  nomad/core_sched_test.go
  website/content/docs/configuration/server.mdx
Labels: backport/1.2.x, backport/1.3.x, backport/1.4.x
