Repository hashicorp/nomad, pull requests merged in 2023-10, with the labels that each got.

#18604 cli: use same offset when following single or multiple alloc logs.
  .changelog/18604.txt
  command/alloc_logs.go
Labels: backport/1.6.x

#18594 sids_hook: read tokens from consul_hook when available
  client/allocrunner/taskrunner/sids_hook.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  client/allocrunner/taskrunner/task_runner_test.go
Labels: type/enhancement, theme/consul

#18637 scaling: set Index on nil-job scale status reply
  .changelog/18637.txt
  nomad/job_endpoint.go
Labels: theme/autoscaling, backport/1.4.x, backport/1.5.x, backport/1.6.x

#18584 fix: use interpolated address when performing health checks
  .changelog/18584.txt
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/checks_hook.go
  client/allocrunner/checks_hook_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#17383 [server] Directed leadership transfer CLI and API
  .changelog/17383.txt
  api/operator.go
  command/agent/operator_endpoint.go
  command/agent/operator_endpoint_test.go
  command/commands.go
  command/operator_raft_leadership_transfer.go
  nomad/leader.go
  nomad/operator_endpoint.go
  nomad/operator_endpoint_test.go
  nomad/structs/operator.go
  website/content/api-docs/operator/raft.mdx
  website/content/docs/commands/operator/raft/transfer-leadership.mdx
  website/data/docs-nav-data.json
Labels: type/enhancement, theme/cli, theme/api, theme/raft

#18662 client: ensure task only runs with prestart hooks
  .changelog/18662.txt
  client/allocrunner/taskrunner/task_runner.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18664 client: remove null dynamic metadata keys
  .changelog/18664.txt
  client/meta_endpoint.go
  client/meta_endpoint_test.go
Labels: backport/1.5.x, backport/1.6.x

#18598 [ui] Bugfix: Wrap the passed path prop as a handlebars tag
  .changelog/18598.txt
  ui/app/components/editable-variable-link.hbs
Labels: backport/1.6.x

#18679 scheduler: fix host volume feasibility check
  scheduler/feasible.go
  scheduler/stack.go
  scheduler/stack_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18676 build: load time/tzdata on Windows
  .changelog/18676.txt
  GNUmakefile
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18661 WID manager: save and restore signed WIs from client state DB
  client/allocrunner/alloc_runner.go
  client/allocrunner/identity_hook_test.go
  client/allocrunner/taskrunner/identity_hook_test.go
  client/allocrunner/taskrunner/task_runner_test.go
  client/state/db_bolt.go
  client/state/db_error.go
  client/state/db_mem.go
  client/state/db_noop.go
  client/state/interface.go
  client/widmgr/mock.go
  client/widmgr/widmgr.go
  client/widmgr/widmgr_int_test.go
  client/widmgr/widmgr_test.go
Labels: type/enhancement, theme/workload-identity

#18702 core: add preempt to desired updates stringer function return.
  nomad/structs/structs.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18703 auth: refactor `Authenticate` into its own package
  ci/test-core.json
  nomad/acl.go
  nomad/acl_endpoint.go
  nomad/acl_test.go
  nomad/auth/auth.go
  nomad/auth/auth_test.go
  nomad/csi_endpoint_test.go
  nomad/rpc.go
  nomad/server.go
Labels: theme/auth, theme/tech-debt

#18689 cli: remove default for ACL token type on update
  .changelog/18689.txt
  command/acl_token_update.go
  website/content/docs/commands/acl/token/update.mdx
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18717 build: bump to go 1.21.3
  .changelog/18717.txt
  .go-version
  contributing/README.md
  scripts/linux-priv-go.sh
  scripts/release/mac-remote-build
Labels: theme/dependencies, theme/build-infrastructure

#18650 WID manager: request signed identities for services
  client/allocrunner/consul_hook.go
  client/allocrunner/taskrunner/identity_hook_test.go
  client/widmgr/widmgr.go
  client/widmgr/widmgr_test.go
  go.mod
  nomad/acl_test.go
  nomad/alloc_endpoint.go
  nomad/auth/auth_test.go
  nomad/encrypter_test.go
  nomad/plan_apply.go
  nomad/structs/services.go
  nomad/structs/structs.go
  nomad/structs/workload_id.go
  nomad/variables_endpoint_test.go
Labels: theme/workload-identity

#18725 deps: remove Vault SDK
  client/vaultclient_test.go
  go.mod
  go.sum
  nomad/vault_test.go
Labels: theme/vault, theme/dependencies

#18715 auth: add server-only ACL
  .semgrep/rpc_endpoint.yml
  acl/acl.go
  acl/acl_test.go
  acl/virtual.go
  nomad/acl.go
  nomad/auth/auth.go
  nomad/auth/auth_test.go
  nomad/client_csi_endpoint.go
  nomad/deployment_endpoint.go
  nomad/encrypter_test.go
  nomad/eval_endpoint.go
  nomad/keyring_endpoint.go
  nomad/keyring_endpoint_test.go
  nomad/plan_endpoint.go
  nomad/rpc_test.go
Labels: theme/auth, theme/tech-debt

#18731 testing: fix configuration for retry tests
  api/retry_test.go
Labels: theme/api, theme/testing

#18730 auth: add client-only ACL
  .semgrep/rpc_endpoint.yml
  acl/acl.go
  acl/acl_test.go
  acl/virtual.go
  client/widmgr/widmgr_int_test.go
  command/agent/event_endpoint_test.go
  command/agent/plugins_test.go
  command/agent/testagent.go
  command/operator_debug_test.go
  command/operator_scheduler_set_config_test.go
  command/testing_test.go
  command/var_lock_test.go
  nomad/acl.go
  nomad/alloc_endpoint.go
  nomad/alloc_endpoint_test.go
  nomad/auth/auth.go
  nomad/auth/auth_test.go
  nomad/csi_endpoint.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
  nomad/operator_endpoint_test.go
  nomad/rpc_test.go
  nomad/service_registration_endpoint.go
  nomad/service_registration_endpoint_test.go
  nomad/util.go
Labels: theme/auth, theme/tech-debt

#18742 WI: set the right identity name for Consul tasks
  client/allocrunner/consul_hook.go
  nomad/job_endpoint_hook_implicit_identities.go
  nomad/job_endpoint_hook_implicit_identities_test.go
  nomad/job_endpoint_hooks_test.go
  nomad/structs/consul.go
  nomad/structs/structs.go
Labels: theme/consul, theme/workload-identity

#18744 auth: remove "mixed auth" special casing for Variables endpoint
  acl/acl.go
  nomad/acl.go
  nomad/acl_test.go
  nomad/auth/auth.go
  nomad/auth/auth_test.go
  nomad/variables_endpoint.go
  nomad/variables_endpoint_test.go
Labels: theme/auth, theme/tech-debt, theme/variables

#18753 csi: add test for that plugin allocs are filtered by namespace
  nomad/csi_endpoint_test.go
Labels: theme/testing

#18768 agent: add config option to enable file and line log detail.
  .changelog/18768.txt
  command/agent/command.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  website/content/docs/commands/agent.mdx
  website/content/docs/configuration/index.mdx
Labels: backport/1.6.x

#18624 consul: add multi-cluster support to client constructors
  client/allocrunner/alloc_runner.go
  client/allocrunner/taskrunner/envoy_version_hook.go
  client/allocrunner/taskrunner/envoy_version_hook_test.go
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  client/client.go
  client/client_test.go
  client/config/arconfig.go
  client/consul/consul.go
  client/serviceregistration/service_registration.go
  client/serviceregistration/wrapper/wrapper.go
  command/agent/agent.go
  command/agent/consul/catalog_testing.go
  command/agent/consul/connect_proxies.go
  command/agent/consul/service_client.go
  command/agent/consul/service_client_test.go
  nomad/consul.go
  nomad/consul_test.go
  nomad/job_endpoint.go
  nomad/server.go
  nomad/structs/connect.go
  nomad/testing.go
Labels: type/enhancement, theme/consul

#18774 Consul: agent config updates for WI
  client/allocrunner/consul_hook.go
  command/agent/config_parse_test.go
  command/agent/job_endpoint_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/job_endpoint_hook_consul_ce.go
  nomad/job_endpoint_hook_implicit_identities.go
  nomad/job_endpoint_hook_implicit_identities_test.go
  nomad/job_endpoint_hooks.go
  nomad/job_endpoint_hooks_test.go
  nomad/structs/config/consul.go
  nomad/structs/config/consul_test.go
  nomad/structs/consul.go
  nomad/structs/consul_ce.go
  nomad/structs/services.go
Labels: type/enhancement, theme/consul, theme/workload-identity

#18786 Do not embed *Server
  nomad/heartbeat.go
  nomad/plan_apply.go
  nomad/rpc.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18811 testutil: add ACL bootstrapping to test server configuration
  testutil/server.go
Labels: theme/testing

#18795 monitor: add log include location option on monitor CLI and API
  .changelog/18795.txt
  client/agent_endpoint.go
  client/structs/structs.go
  command/agent/agent_endpoint.go
  command/agent/agent_endpoint_test.go
  command/agent_monitor.go
  command/agent_monitor_test.go
  command/operator_debug.go
  nomad/client_agent_endpoint.go
  website/content/api-docs/agent.mdx
  website/content/docs/commands/monitor.mdx
  website/content/docs/commands/operator/debug.mdx
Labels: backport/1.6.x

#18808 cli: use single dep func for opening URLs.
  command/ui.go
  go.mod
  go.sum
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18836 cli: add prefix ID and wildcard namespace support for `service info`
  .changelog/18836.txt
  command/service_info.go
  command/service_list.go
Labels: type/enhancement, theme/cli, theme/service-discovery/nomad

#18834 test: use must lib for bitmap tests.
  nomad/structs/bitmap_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18835 metrics: prevent negative counter from iowait decrease
  .changelog/18835.txt
  client/hoststats/host.go
  client/hoststats/host_test.go
Labels: type/bug, theme/metrics

#18849 metrics: prevent negative counter from iowait decrease (backport 1.6.x)
  .changelog/18835.txt
  client/stats/host.go
  client/stats/host_test.go
Labels: type/bug, theme/client, theme/metrics

#18832 cli: ensure HCL env vars are added to the job submission object.
  .changelog/18832.txt
  command/helpers.go
  command/helpers_test.go
Labels: backport/1.6.x

#18838 scheduler: appropriately unblock evals with quotas
  .changelog/18838.txt
  nomad/blocked_evals.go
  nomad/blocked_evals_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18799 E2E: Consul compatibility matrix tests
  .github/workflows/test-e2e.yml
  GNUmakefile
  e2e/consulcompat/consulcompat_test.go
  e2e/consulcompat/doc.go
  e2e/consulcompat/input/connect.nomad.hcl
  e2e/consulcompat/input/consul-policy-for-nomad-legacy.hcl
  e2e/consulcompat/input/consul-policy-for-nomad.hcl
  e2e/consulcompat/input/consul-policy-for-tasks.hcl
  e2e/consulcompat/run_ce_test.go
  e2e/consulcompat/shared_download_test.go
  e2e/consulcompat/shared_run_test.go
  e2e/consulcompat/shared_setup_test.go
  testutil/server.go
Labels: theme/consul, theme/e2e, theme/workload-identity

#18856 docs: deprecate rsadecrypt
  website/content/docs/job-specification/hcl2/functions/crypto/rsadecrypt.mdx
  website/data/docs-nav-data.json
Labels: backport/website, backport/1.6.x

#18846 scheduler: remove unused alloc index functions.
  scheduler/reconcile_util.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18704 docs: Vault Workload Identity integration
  website/content/docs/integrations/consul-integration.mdx
  website/content/docs/integrations/vault-integration.mdx
  website/content/docs/job-specification/vault.mdx
Labels: theme/docs, theme/vault, theme/workload-identity

#18863 add deprecation warning for Vault/Consul token usage
  command/agent/command.go
  command/job_revert.go
  command/job_run.go
Labels: theme/vault, theme/consul, theme/workload-identity

#18873 scheduler: ensure dup alloc names are fixed before plan submit.
  .changelog/18873.txt
  nomad/structs/structs.go
  scheduler/generic_sched.go
  scheduler/generic_sched_test.go
  scheduler/reconcile.go
  scheduler/reconcile_util.go
  scheduler/reconcile_util_test.go
Labels: backport/1.4.x, backport/1.5.x, backport/1.6.x

#18878 e2e: fix bind name to allow Connect reachability
  e2e/consulcompat/input/connect.nomad.hcl
  e2e/consulcompat/run_ce_test.go
  e2e/consulcompat/shared_run_test.go
  e2e/consulcompat/shared_setup_test.go
  testutil/server.go
Labels: theme/consul, theme/testing, theme/e2e

#18562 Add support for NetBSD
  .changelog/18562.txt
  client/allocdir/fs_netbsd.go
  command/agent/host/darwin.go
  command/agent/host/linux.go
  command/agent/host/unix.go
  go.mod
  go.sum
Labels: type/enhancement, theme/fingerprint, stage/waiting-reply

#18895 docs: remove stale note about `generate_lease` from template docs
  website/content/docs/job-specification/template.mdx
Labels: theme/docs, theme/consul-template

#18913 `identity_hook`: implement PreKill hook, not TaskStop hook
  client/allocrunner/identity_hook.go
  client/allocrunner/identity_hook_test.go
  client/widmgr/widmgr.go
Labels: type/bug, theme/workload-identity

#18914 services: fix lookup for Consul tokens
  client/allocrunner/taskrunner/sids_hook.go
  nomad/job_endpoint_hook_implicit_identities.go
  nomad/structs/services.go
Labels: type/bug, theme/consul, theme/workload-identity

#18916 docs: name, audience, and TTL fields for `identity` blocks
  website/content/docs/job-specification/identity.mdx
Labels: theme/docs, theme/workload-identity

#18928 docs: upgrade guide for integrations deprecation warnings
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/docs, theme/vault, theme/consul, theme/workload-identity

#18926 identity: version check multiple and implicit identities
  nomad/job_endpoint_hooks.go
  nomad/leader.go
  version/version.go
Labels: theme/vault, theme/consul, theme/workload-identity

#18939 docs: fix `token_period` in example Vault role for WI
  website/content/docs/integrations/vault-integration.mdx
Labels: theme/docs, theme/vault

#18940 vault: fix lookups of default cluster across upgrades
  client/allocrunner/taskrunner/template_hook.go
  client/allocrunner/taskrunner/vault_hook.go
Labels: type/bug, theme/vault
