Repository hashicorp/nomad, pull requests merged in 2023-05, with the labels that each got.

#17056 build: upgrade from go 1.20.3 to 1.20.4
  .changelog/17056.txt
  .circleci/config.yml
  .go-version
  contributing/README.md
  scripts/linux-priv-go.sh
  scripts/release/mac-remote-build
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#16908 [deps] Update consul-template to v0.31.0
  .changelog/16908.txt
  go.mod
  go.sum
Labels: theme/consul-template, theme/dependencies, dependencies

#17077 docs: update artifact jobspec sshkey example path.
  website/content/docs/job-specification/artifact.mdx
Labels: backport/website, backport/1.5.x

#17092 scale: fixed a bug where evals could be created with wrong type.
  .changelog/17092.txt
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17071 [17070] Correct the status description and modify time of canceled evals.
  .changelog/17071.txt
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17115 docs: add note to upgrade guide about yanked version
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/docs

#17104 Fix task leak during client restore when allocrunner prerun hook fails
  .changelog/17104.txt
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_hooks.go
  client/allocrunner/fail_hook.go
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/task_runner_test.go
  client/client_test.go
  client/config/config.go
  nomad/mock/alloc.go
  testutil/wait.go
Labels: type/bug, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17137 api: update Go mod go version to 1.20 to match main mod.
  api/go.mod
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17133 deps: update go-metrics to prevent panic
  go.mod
  go.sum
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17169 [ui] Keyboard shortcuts to switch regions
  .changelog/17169.txt
  ui/app/components/region-switcher.js
  ui/app/templates/components/region-switcher.hbs
  ui/tests/acceptance/keyboard-test.js
Labels: backport/1.5.x

#17161 allocrunner: provide factory function so we can build mock ARs
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/alloc_runner_unix_test.go
  client/allocrunner/config.go
  client/allocrunner/csi_hook.go
  client/allocrunner/interfaces/runner.go
  client/allocrunner/migrate_hook.go
  client/allocrunner/testing.go
  client/allocrunner/upstream_allocs_hook.go
  client/allocwatcher/alloc_watcher.go
  client/allocwatcher/group_alloc_watcher.go
  client/allocwatcher/group_alloc_watcher_test.go
  client/client.go
  client/client_interface_test.go
  client/client_test.go
  client/config/arconfig.go
  client/config/config.go
  client/gc.go
  client/gc_test.go
  client/heartbeatstop.go
  client/state/upgrade_int_test.go
  drivers/mock/driver_test.go
  plugins/drivers/testutils/testing.go
Labels: theme/testing, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17184 Update delete.mdx
  website/content/docs/commands/service/delete.mdx
Labels: backport/website, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17194 acl: refactor acl.UpsertTokens to avoid unnecessary RPC calls
  nomad/acl_endpoint.go
Labels: backport/1.5.x

#17196 drivers: make internal `DisableLogCollection` capability public
  .changelog/17196.txt
  client/allocrunner/taskrunner/logmon_hook.go
  drivers/docker/config.go
  drivers/docker/config_test.go
  plugins/drivers/client.go
  plugins/drivers/driver.go
  plugins/drivers/proto/driver.pb.go
  plugins/drivers/proto/driver.proto
  website/content/docs/concepts/plugins/task-drivers.mdx
Labels: type/enhancement, theme/driver/docker, theme/logging, theme/driver

#17175 client: ignore restart issued to terminal allocations
  .changelog/17175.txt
  client/allocrunner/alloc_runner.go
  e2e/clientstate/allocs_test.go
  e2e/clientstate/input/alloc_zombie.nomad
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17198 scheduler: prevent -Inf in spread scoring
  .changelog/17198.txt
  scheduler/spread.go
  scheduler/spread_test.go
Labels: type/bug, theme/scheduling, hcc/cst

#17195 scheduler: count implicit spread targets as a single target
  .changelog/17195.txt
  scheduler/propertyset.go
  scheduler/spread.go
  scheduler/spread_test.go
Labels: type/bug, theme/scheduling, hcc/cst

#17222 build: upgrade deprecated actions syntax
  .github/workflows/release.yml
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17219 docs: remove unneeded brackets from job specification template docs
  website/content/docs/job-specification/template.mdx
Labels: theme/docs, backport/1.4.x, backport/1.5.x

#15829 Adds documentation on ephemeral disk and logs
  website/content/docs/job-specification/ephemeral_disk.mdx
  website/content/docs/job-specification/logs.mdx
Labels: theme/docs, backport/1.3.x, backport/1.4.x, backport/1.5.x

#17234 variable: fix-up metadata copy comment and remove unrequired type.
  nomad/structs/variables.go
Labels: backport/1.4.x, backport/1.5.x

#17199 logs: fix `logs.disabled` on Windows
  .changelog/17199.txt
  drivers/shared/executor/executor.go
Labels: theme/platform-windows, theme/logging, backport/1.5.x

#17138 cli: Show leader status in json output of server members
  .changelog/17138.txt
  command/server_members.go
Labels: theme/cli

#17238 build: move GitHub actions to versions allowed by prodsec
  .github/workflows/ember-assets.yml
  .github/workflows/ember-test-audit.yml
  .github/workflows/semgrep.yml
Labels: theme/ui, theme/build-infrastructure

#17245 docs: describe the default Workload Identity ACL policy
  website/content/docs/concepts/workload-identity.mdx
Labels: theme/docs, theme/auth, theme/service-discovery/nomad, theme/variables, theme/workload-identity

#17018 allow periodic jobs to use workload identity ACL policies
  .changelog/17018.txt
  nomad/acl.go
  nomad/variables_endpoint_test.go
Labels: type/bug, theme/auth, theme/batch, backport/1.4.x, backport/1.5.x

#16743 [api] Return a shapely error for unexpected response
  .changelog/16743.txt
  api/api.go
  api/error_unexpected_response.go
  api/error_unexpected_response_test.go
  api/go.mod
  api/go.sum
  api/internal/testutil/ports.go
  api/internal/testutil/server.go
  api/namespace_test.go
  api/operator.go
  api/variables.go
  go.mod
  go.sum
Labels: type/enhancement, theme/api

#17239 build: remove 386 builds for Nomad 1.6.0
  .github/workflows/build.yml
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/build-infrastructure

#17282 dependencies backport to 1.5.x
  .changelog/16862.txt
  .changelog/17281.txt
  drivers/docker/driver_test.go
  drivers/shared/resolvconf/mount.go
  drivers/shared/resolvconf/mount_unix_test.go
  go.mod
  go.sum
  plugins/drivers/testutils/dns_testing.go
Labels: theme/dependencies

#17284 dependencies backport to 1.4.x
  .changelog/16862.txt
  .changelog/17281.txt
  drivers/docker/driver_test.go
  drivers/shared/resolvconf/mount.go
  drivers/shared/resolvconf/mount_unix_test.go
  go.mod
  go.sum
  plugins/drivers/testutils/dns_testing.go
Labels: theme/dependencies

#17285 Backport 1.3.x dependabot
  .changelog/16862.txt
  .changelog/17281.txt
  client/lib/cgutil/cgutil_linux.go
  client/lib/cgutil/cgutil_linux_test.go
  client/lib/cgutil/cpuset_manager_v1.go
  client/lib/cgutil/cpuset_manager_v2.go
  client/lib/cgutil/group_killer.go
  client/lib/resources/containment_linux.go
  drivers/docker/driver_test.go
  drivers/shared/executor/executor_linux.go
  drivers/shared/executor/executor_linux_test.go
  drivers/shared/executor/executor_universal_linux.go
  drivers/shared/resolvconf/mount.go
  drivers/shared/resolvconf/mount_unix_test.go
  go.mod
  go.sum
  plugins/drivers/testutils/dns_testing.go
Labels: theme/dependencies

#17296 docs: fixup example of readiness check
  website/content/docs/job-specification/check.mdx
Labels: backport/website

#17316 [core] nil check and error handling for client status in heartbeat responses
  .changelog/17316.txt
  client/client.go
  nomad/node_endpoint.go
  nomad/node_endpoint_test.go
Labels: type/bug, theme/core, stage/accepted

#17319 [ui] A few variables-ui-related bugfixes
  .changelog/17319.txt
  ui/app/components/variable-form.hbs
  ui/app/components/variable-form.js
  ui/app/components/variable-form/related-entities.hbs
  ui/app/controllers/variables/variable/index.js
Labels: backport/1.5.x

#17314 fix: job canonicalization should set job priority to 50, not 0.
  api/jobs.go
  api/jobs_test.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17349 client: fix Consul version finterprint
  .changelog/17349.txt
  client/fingerprint/consul.go
  client/fingerprint/consul_test.go
  command/agent/consul/self.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17346 cli: fix panic on job restart
  .changelog/17346.txt
  command/job_restart.go
Labels: backport/1.5.x

#17348 cli: output errors when monitoring deployment
  .changelog/17348.txt
  command/deployment_status.go
Labels: backport/1.3.x, backport/1.4.x, backport/1.5.x

#17315 refact: update models for relationship
  ui/app/models/job.js
  ui/app/models/node-pool.js
  ui/app/models/node.js
  ui/mirage/factories/job.js
  ui/mirage/factories/node-pool.js
  ui/mirage/factories/node.js
  ui/mirage/models/node-pool.js
  ui/mirage/models/node.js
  ui/tests/acceptance/job-detail-test.js
  ui/tests/acceptance/job-status-panel-test.js
  ui/tests/acceptance/token-test.js
  ui/tests/unit/models/node-test.js
Labels: theme/node-pools

#17354 prioritized client updates
  .changelog/17354.txt
  client/allocrunner/alloc_runner.go
  client/allocrunner/alloc_runner_test.go
  client/allocrunner/interfaces/runner.go
  client/client.go
  client/client_interface_test.go
  client/client_test.go
  client/structs/enum.go
Labels: type/enhancement, theme/client
