Repository hashicorp/nomad, pull requests merged in 2024-02, with the labels that each got.

#19863 deps: update dependencies indirectly bringing in older runc
  go.mod
  go.sum
Labels: theme/dependencies, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19876 cli: fix return code when job deployment succeeds
  .changelog/19876.txt
  command/monitor.go
  command/monitor_test.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19878 [ui] Random exec assignment chooses from only those with a matching taskGroup, if provided
  .changelog/19878.txt
  ui/app/controllers/exec.js
Labels: theme/ui, backport/1.4.x, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19882 docs: remove Docker `cpuset_cpus` config
  website/content/docs/drivers/docker.mdx
Labels: backport/website, backport/1.7.x

#19877 docs: remove duplicate entry for `upstreams.config`
  website/content/docs/job-specification/upstreams.mdx
Labels: backport/website, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19808 Libraries & SDKs: add nix-nomad
  website/content/api-docs/libraries-and-sdks.mdx
Labels: backport/website, backport/1.7.x

#19872 [ui] HashiCorp Design System upgraded to 3.6.0
  ui/app/components/conditional-link-to.hbs
  ui/app/components/das/recommendation-card.hbs
  ui/app/components/das/task-row.hbs
  ui/app/components/job-status/individual-allocation.hbs
  ui/app/components/keyboard-shortcuts-modal.hbs
  ui/app/styles/core/table.scss
  ui/app/templates/allocations/allocation/index.hbs
  ui/app/templates/clients/client/index.hbs
  ui/app/templates/clients/index.hbs
  ui/app/templates/components/job-deployment/deployment-allocations.hbs
  ui/app/templates/components/job-editor/review.hbs
  ui/app/templates/components/job-page/parts/recent-allocations.hbs
  ui/app/templates/components/multi-select-dropdown.hbs
  ui/app/templates/components/scale-events-accordion.hbs
  ui/app/templates/components/task-row.hbs
  ui/app/templates/components/topo-viz/node.hbs
  ui/app/templates/csi/plugins/plugin/allocations.hbs
  ui/app/templates/csi/plugins/plugin/index.hbs
  ui/app/templates/csi/volumes/volume.hbs
  ui/app/templates/jobs/job/allocations.hbs
  ui/app/templates/jobs/job/task-group.hbs
  ui/package.json
  ui/tests/acceptance/behaviors/fs.js
  ui/tests/integration/components/scale-events-accordion-test.js
  ui/tests/integration/components/service-status-bar-test.js
  ui/tests/integration/components/topo-viz/node-test.js
  ui/tests/pages/components/topo-viz/node.js
  ui/yarn.lock
Labels: backport/1.7.x

#19892 cli: fix `tls ca create` command with `-domain`
  .changelog/19892.txt
  command/tls_ca_create.go
  command/tls_ca_create_test.go
  helper/tlsutil/generate.go
Labels: backport/1.6.x, backport/1.7.x

#19902 docs: add note about stub list filtering
  website/content/api-docs/index.mdx
Labels: backport/website, backport/1.7.x

#19916 docs: expand impact of `verify_https_client=false`
  website/content/docs/concepts/security.mdx
Labels: backport/website, backport/1.7.x

#19905 [docs] Add action name restrictions and correct auth method and role name restrictions
  website/content/api-docs/acl/auth-methods.mdx
  website/content/api-docs/acl/roles.mdx
  website/content/docs/commands/acl/auth-method/update.mdx
  website/content/docs/commands/acl/role/create.mdx
  website/content/docs/commands/acl/role/update.mdx
  website/content/docs/job-specification/action.mdx
Labels: theme/docs, backport/website, backport/1.7.x

#19923 fingerprint: eliminate spurious warning logs with Consul CE
  client/fingerprint/consul.go
  client/fingerprint/consul_test.go
Labels: type/bug, theme/fingerprint, backport/1.7.x

#19925 windows: remove LazyDLL calls for system modules
  .changelog/19925.txt
  command/agent/host/windows.go
  drivers/shared/executor/executor_windows.go
Labels: type/enhancement, theme/security, theme/platform-windows, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19915 client: prevent start on cgroups init error
  .changelog/19915.txt
  client/client.go
  client/lib/cgroupslib/init.go
  client/lib/proclib/wrangler_cg1_linux.go
  client/lib/proclib/wrangler_cg2_linux.go
  client/lib/proclib/wrangler_default.go
  client/lib/proclib/wrangler_linux.go
Labels: backport/1.7.x

#19935 executor: limit the value of CPU shares
  .changelog/19935.txt
  drivers/shared/executor/executor_linux.go
Labels: backport/1.7.x

#19933 scheduler: retain eval metrics on port collision
  .changelog/19933.txt
  nomad/job_endpoint_test.go
  scheduler/rank.go
  testutil/wait.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19903 events: emit event when job is deleted
  .changelog/19903.txt
  nomad/state/events.go
  nomad/state/events_test.go
Labels: backport/1.7.x

#19937 state: fix state store corruption in plan apply
  nomad/state/state_store.go
Labels: type/bug, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19932 alloc exec: fix panics after stream close
  .changelog/19932.txt
  command/agent/alloc_endpoint.go
  command/agent/alloc_endpoint_test.go
  command/agent/job_endpoint.go
Labels: type/bug, theme/crash, theme/allocation API, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19954 CNI: fix deprecation warnings
  client/allocrunner/networking_cni.go
  client/allocrunner/networking_cni_test.go
Labels: theme/cni, theme/tech-debt, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19953 [ui] Upgrades to build storybook on node v20
  ui/package.json
  ui/yarn.lock
Labels: backport/1.7.x

#19945 docs: autoscaler doc for max_scale_up and max_scale_down of target-value strategy
  website/content/tools/autoscaling/plugins/strategy/target-value.mdx
Labels: backport/website, backport/1.7.x

#19969 fingerprint: add DNS address and port to Consul fingerprint
  .changelog/19969.txt
  client/fingerprint/consul.go
  client/fingerprint/consul_test.go
  client/fingerprint/test_fixtures/consul/agent_self_ent.json
Labels: type/enhancement, theme/consul, theme/consul/connect, backport/1.7.x

#19975 test: fix test datarace within driver shared eventer.
  drivers/shared/eventer/eventer_test.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19974 test: fix test datarace within helper broker.
  helper/broker/notify_test.go
Labels: backport/1.5.x, backport/1.6.x, backport/1.7.x

#19990 connect: fix missing diff of expose block
  .changelog/19990.txt
  nomad/structs/diff.go
  nomad/structs/diff_test.go
  nomad/structs/services.go
Labels: type/bug, theme/consul/connect, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19985 ui: Confirmation on exit from exec as long as socket has been opened
  .changelog/19985.txt
  ui/app/components/exec-terminal.js
  ui/app/templates/exec.hbs
  ui/package.json
  ui/yarn.lock
Labels: backport/1.7.x

#19989 ui: Warning and better error handling for invalid-named variables and job templates
  .changelog/19989.txt
  ui/app/adapters/variable.js
  ui/app/components/variable-form.hbs
  ui/app/components/variable-form.js
  ui/app/controllers/jobs/run/templates/new.js
  ui/app/templates/jobs/run/templates/new.hbs
  ui/tests/integration/components/variable-form-test.js
Labels: backport/1.7.x

#20007 cni: add DNS set by CNI plugins to task configuration
  .changelog/20007.txt
  client/allocrunner/alloc_runner.go
  client/allocrunner/taskrunner/task_runner.go
  client/allocrunner/taskrunner/task_runner_test.go
  client/structs/allochook.go
  website/content/docs/job-specification/network.mdx
Labels: type/bug, theme/cni, backport/1.5.x, backport/1.6.x, backport/1.7.x

#19874 Remove accidental console log in namespace test setup
  ui/mirage/factories/job.js
Labels: theme/ui, theme/testing

#19942 docs: add Autoscaler `query_window_offset` config
  website/content/tools/autoscaling/policy.mdx
Labels: backport/website, backport/1.7.x

#19987 Prevent NPE when service lacks identity
  .changelog/19986.txt
  nomad/structs/workload_id.go
Labels: type/bug, theme/crash, backport/1.7.x

#20031 Backport Docs: Alternative IIS Task Driver (#19411)
  website/content/plugins/drivers/community/index.mdx
  website/content/plugins/drivers/community/nomad-iis.mdx
  website/data/docs-nav-data.json
  website/data/plugins-nav-data.json
Labels: backport/1.7.x

#20022 docs: Consul Admin partition example and updates
  website/content/docs/job-specification/consul.mdx
Labels: theme/docs, theme/consul, backport/1.7.x

#20050 docs: fix autoscaler variable ACL policy example.
  website/content/tools/autoscaling/agent.mdx
Labels: backport/website, backport/1.7.x

#20047 [ui] Fixes an issue where shift+num would not open an eval on the evaluations index table
  .changelog/20047.txt
  ui/app/controllers/evaluations/index.js
  ui/app/templates/evaluations/index.hbs
Labels: backport/1.7.x
