Repository hashicorp/nomad, pull requests merged in 2024-12, with the labels that each got.

#24538 executor: fail early on reattach if listener is not executor
  .changelog/24538.txt
  drivers/shared/executor/utils.go
Labels: backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24580 Backport of chore(deps): bump github.com/hashicorp/go-sockaddr from 1.0.6 to 1.0.7 into release/1.9.x
  go.mod
  go.sum
Labels: backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.9.x

#24546 release: always use service user for git ops
  .github/workflows/release.yml
Labels: theme/ci, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24495 drivers: update ordering of events in StartTask to fix executor leak
  .changelog/24495.txt
  drivers/exec/driver.go
  drivers/exec/driver_test.go
  drivers/java/driver.go
Labels: backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24588 Fix doc title in security.mdx
  website/content/docs/concepts/security.mdx
Labels: backport/website

#24586 dynamic host volumes: set namespace from volume spec when monitoring
  command/volume_create_host.go
Labels: type/bug, theme/storage

#24598 Fix title in sentinel page
  website/content/docs/enterprise/sentinel.mdx
Labels: backport/website

#24600 helper: sanitize method on ACL token object
  nomad/structs/acl.go
  nomad/structs/event.go
Labels: type/enhancement, theme/tech-debt

#24601 sentinel: remove default scope for Sentinel apply command
  .changelog/24601.txt
  api/sentinel.go
  command/sentinel_apply.go
Labels: type/enhancement, theme/cli, theme/storage, theme/enterprise

#24595 dynamic host volumes: client state
  client/client.go
  client/host_volume_endpoint_test.go
  client/hostvolumemanager/host_volume_plugin.go
  client/hostvolumemanager/host_volume_plugin_test.go
  client/hostvolumemanager/host_volumes.go
  client/hostvolumemanager/host_volumes_test.go
  client/state/db_bolt.go
  client/state/db_error.go
  client/state/db_mem.go
  client/state/db_noop.go
  client/state/db_test.go
  client/state/interface.go
  client/structs/host_volumes.go
Labels: type/enhancement, theme/storage

#24602 test: fix panic from concurrent writes in periodic dispatch test
  nomad/periodic_test.go
Labels: theme/testing, theme/flaky-tests, theme/periodic

#24605 dynamic host volumes: add implicit constraints on plugin fingerprint
  nomad/host_volume_endpoint.go
  nomad/host_volume_endpoint_test.go
Labels: type/enhancement, theme/storage

#24607 ci: only cache from github hosted runners to avoid file perm issues
  .github/workflows/checks.yaml
Labels: backport/ent/1.7.x+ent, backport/ent/1.8.x+ent

#24606 dynamic host volumes: delete by single volume ID
  api/host_volumes.go
  command/agent/host_volume_endpoint.go
  command/volume_delete.go
  nomad/fsm.go
  nomad/host_volume_endpoint.go
  nomad/host_volume_endpoint_test.go
  nomad/state/state_store_host_volumes.go
  nomad/state/state_store_host_volumes_test.go
  nomad/structs/host_volumes.go
Labels: type/enhancement, theme/storage

#24593 Docs Feature: Add clone and edit feature
  website/content/docs/concepts/job.mdx
Labels: theme/docs

#24612 dynamic host volumes: refactor HTTP routes for volumes list dispatch
  command/agent/csi_endpoint.go
  command/agent/http.go
  command/agent/volumes_endpoint.go
Labels: type/enhancement, theme/storage

#24617 dynamic host volumes: capabilities check during scheduling
  nomad/state/state_store_host_volumes.go
  scheduler/feasible.go
  scheduler/feasible_test.go
  scheduler/scheduler.go
  scheduler/stack.go
Labels: type/enhancement, theme/storage

#24642 Character restrictions in action names were unduly oppressive
  .changelog/24642.txt
  nomad/structs/actions.go
  nomad/structs/actions_test.go
Labels: backport/1.9.x

#24667 dynamic host volumes: add -type flag to volume init
  command/asset/asset.go
  command/asset/volume.csi.hcl
  command/asset/volume.csi.json
  command/asset/volume.host.hcl
  command/asset/volume.host.json
  command/volume_init.go
Labels: type/enhancement, theme/cli, theme/storage

#24650 CNI: use tmpfs location for ipam plugin
  .changelog/24650.txt
  client/allocrunner/cni/bridge.go
  client/allocrunner/cni/plugins.go
  client/allocrunner/test_fixtures/bad_input.conflist.json
  client/allocrunner/test_fixtures/consul-cni.conflist.json
  client/allocrunner/test_fixtures/empty.conflist.json
  client/allocrunner/test_fixtures/hairpin.conflist.json
  client/allocrunner/test_fixtures/ipv6.conflist.json
Labels: type/bug, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24644 Allocation API: fix "no path to region" errors for non-global regions
  .changelog/24644.txt
  api/api.go
  e2e/terraform/provision-nomad/etc/nomad.d/base.hcl
Labels: type/bug, theme/allocation API, backport/ent/1.8.x+ent, backport/1.9.x

#24683 sec: fix alloc workload identity namespace permission
  .changelog/24683.txt
  command/agent/node_endpoint.go
  nomad/alloc_endpoint.go
  nomad/structs/structs.go
Labels: theme/api, theme/security, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24620 [ui] Fixes an issue where system jobs' status were set to Scaled Down when their allocs get garbage collected
  .changelog/24620.txt
  ui/app/components/job-status/panel/steady.js
  ui/app/models/job.js
  ui/tests/acceptance/jobs-list-test.js
Labels: backport/1.9.x

#24616 [ui] Resolutions for code-scanner/dependabot alerts in UI
  ui/package.json
  ui/yarn.lock
Labels: backport/1.8.x, backport/1.9.x

#24693 E2E: use a variable for region
  e2e/terraform/nomad.tf
  e2e/terraform/provision-nomad/etc/nomad.d/base.hcl
  e2e/terraform/provision-nomad/main.tf
  e2e/terraform/provision-nomad/tls.tf
  e2e/terraform/provision-nomad/variables.tf
  e2e/terraform/terraform.tfvars
  e2e/terraform/variables.tf
Labels: theme/e2e, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24668 [ui] Bugfix: prevent parent job from showing another job's dispatches when it has none
  .changelog/24668.txt
  ui/app/controllers/jobs/job/index.js
Labels: backport/1.9.x

#24701 sec: suppress osv alert in CRT
  .release/security-scan.hcl
Labels: theme/security, theme/ci, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24649 discovery: correctly handle IPv6 addresses from go-discover
  .changelog/24649.txt
  client/rpc.go
  client/rpc_test.go
Labels: type/bug, theme/discovery, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24705 dynamic host volumes: remove multi-node access modes
  nomad/structs/host_volumes.go
  nomad/structs/host_volumes_test.go
  nomad/structs/volumes.go
  nomad/structs/volumes_test.go
Labels: type/enhancement, theme/storage

#24708 github: Fix lock threads syntax and permissions.
  .github/workflows/lock.yml
Labels: backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x

#24622 Show HCL variable input on job submission.
  .changelog/24622.txt
  ui/app/templates/components/job-editor/edit.hbs
Labels: backport/1.9.x

#24711 dynamic host volumes: tweak plugin fingerprint
  client/fingerprint/dynamic_host_volumes.go
  client/fingerprint/dynamic_host_volumes_test.go
  client/hostvolumemanager/host_volume_plugin.go
  client/hostvolumemanager/host_volume_plugin_test.go
  client/hostvolumemanager/test_fixtures/test_plugin.sh
  demo/hostvolume/_test-plugin.sh
  demo/hostvolume/example-plugin-mkfs
  nomad/host_volume_endpoint.go
  nomad/host_volume_endpoint_test.go
Labels: type/enhancement, theme/storage

#24712 Docs: Add link to published clone and edit tutorial
  website/content/docs/concepts/job.mdx
Labels: backport/website, backport/1.9.x

#24727 Docs: change stop_after to stop_on_client_after
  website/content/docs/job-specification/disconnect.mdx
  website/data/docs-nav-data.json
Labels: backport/website, backport/ent/1.8.x+ent, backport/1.8.x, backport/1.9.x

#24731 Docs: fix typo in lower_bound
  website/content/tools/autoscaling/plugins/strategy/threshold.mdx
Labels: backport/website, backport/1.7.x, backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.8.x, backport/1.9.x

#24721 event stream: add events for dynamic host volumes
  nomad/state/deployment_events_test.go
  nomad/state/events.go
  nomad/state/events_test.go
  nomad/state/state_store_host_volumes.go
  nomad/stream/event_broker.go
  nomad/structs/event.go
  website/content/api-docs/events.mdx
Labels: type/enhancement, theme/storage, theme/events

#24724 event stream: add events for CSI volumes and plugins
  .changelog/24724.txt
  nomad/state/events.go
  nomad/state/events_test.go
  nomad/state/schema.go
  nomad/state/state_store.go
  nomad/state/state_store_restore.go
  nomad/stream/event_broker.go
  nomad/structs/event.go
  nomad/volumewatcher/volumes_watcher.go
  website/content/api-docs/events.mdx
Labels: type/enhancement, theme/storage, theme/events

#24716 deps: Update golang.org/x packages.
  go.mod
  go.sum
Labels: backport/ent/1.7.x+ent, backport/ent/1.8.x+ent, backport/1.9.x
