Repository hashicorp/nomad, pull requests merged in 2025-05, with the labels that each got.

#25721 Force an agent return if there is an error on reload
  .changelog/25721.txt
  command/agent/command.go
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: theme/docs, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25791 encrypter: Ignore wrapped key additions with zero wrapped keys.
  nomad/encrypter.go
  nomad/encrypter_test.go
Labels: backport/ent/1.9.x+ent, backport/1.10.x

#25801 deps: Update mitchellh/colorstring to d06e56a500db
  go.mod
  go.sum
Labels: backport/1.10.x

#25804 ci: Regenerate TLS certificates used for testing.
  helper/tlsutil/testdata/README.md
  helper/tlsutil/testdata/badRegion-client-bad-key.pem
  helper/tlsutil/testdata/badRegion-client-bad.pem
  helper/tlsutil/testdata/badRegion-server-bad-key.pem
  helper/tlsutil/testdata/badRegion-server-bad.pem
  helper/tlsutil/testdata/global-client-nomad-key.pem
  helper/tlsutil/testdata/global-client-nomad.pem
  helper/tlsutil/testdata/global-server-nomad-key.pem
  helper/tlsutil/testdata/global-server-nomad.pem
  helper/tlsutil/testdata/regionFoo-client-nomad-key.pem
  helper/tlsutil/testdata/regionFoo-client-nomad.pem
  helper/tlsutil/testdata/regionFoo-server-nomad-key.pem
  helper/tlsutil/testdata/regionFoo-server-nomad.pem
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25806 testing: fix vault setup test's reliance on specific Raft index
  command/setup_vault_test.go
Labels: theme/testing, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25795 encrypter: Remove tracking of cancelation for decrypt tasks.
  .changelog/25795.txt
  nomad/encrypter.go
  nomad/encrypter_test.go
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25818 build: update go toolchain to 1.24.3
  .changelog/25818.txt
  .go-version
  contributing/README.md
  scripts/linux-priv-go.sh
  scripts/release/mac-remote-build
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25803 encrypter: Track initial tasks for is ready calculation.
  .changelog/25803.txt
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/encrypter.go
  nomad/encrypter_test.go
  nomad/server.go
  website/content/docs/configuration/server.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: backport/ent/1.9.x+ent, backport/1.10.x

#25839 reduce upgrade testing flakes
  enos/README.md
  enos/modules/drain_nodes/scripts/drain.sh
  enos/modules/run_workloads/outputs.tf
  enos/modules/test_cluster_health/scripts/allocs.sh
  enos/modules/test_cluster_health/scripts/clients.sh
  enos/modules/test_cluster_health/scripts/jobs.sh
  enos/modules/test_cluster_health/scripts/servers.sh
  enos/modules/upgrade_client/scripts/get_expected_allocs.sh
  enos/modules/upgrade_client/scripts/verify_allocs.sh
  enos/modules/upgrade_servers/scripts/wait_for_stable_cluster.sh
Labels: theme/testing

#25845 Docs: Job spec artifact - move environment section
  website/content/docs/job-specification/artifact.mdx
Labels: theme/docs, backport/website, backport/ent/1.8.x+ent, backport/1.8.x, backport/ent/1.9.x+ent, backport/1.9.x, backport/1.10.x

#25844 offline license utilization reporting
  .changelog/25844.txt
  api/operator.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/http.go
  command/agent/operator_endpoint_ce.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  command/commands.go
  command/operator_utilization.go
  nomad/event_endpoint.go
  nomad/state/events.go
  nomad/state/events_ce.go
  nomad/structs/config/reporting.go
  nomad/structs/event.go
  website/content/api-docs/events.mdx
  website/content/api-docs/operator/utilization.mdx
  website/content/docs/commands/operator/utilization.mdx
  website/content/docs/configuration/reporting.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: type/enhancement, theme/docs, theme/enterprise, backport/1.10.x

#25855 build: pin actionlint workflow
  .github/workflows/actionlint.yml
Labels: theme/security, theme/dependencies, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#24150 start: allow users to call job start command to start stopped jobs
  .changelog/24150.txt
  command/commands.go
  command/job_start.go
  command/job_start_test.go
  command/testing_test.go
  website/content/docs/commands/job/restart.mdx
  website/content/docs/commands/job/start.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, backport/1.10.x

#25850 Only error on constraints if no allocs are running
  .changelog/25850.txt
  scheduler/scheduler_sysbatch_test.go
  scheduler/scheduler_system.go
  scheduler/scheduler_system_test.go
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25870 telemetry: fix excessive CPU consumption in executor
  .changelog/25870.txt
  client/allocrunner/taskrunner/stats_hook.go
  client/allocrunner/taskrunner/stats_hook_test.go
  client/allocrunner/taskrunner/task_runner_hooks.go
  drivers/shared/executor/executor.go
  drivers/shared/executor/executor_linux.go
  drivers/shared/executor/procstats/getstats.go
  drivers/shared/executor/procstats/getstats_test.go
  drivers/shared/executor/procstats/list_test.go
  drivers/shared/executor/procstats/list_windows.go
  drivers/shared/executor/procstats/procstats.go
Labels: theme/metrics, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25612 Docs: SEO job spec section
  website/content/docs/job-specification/action.mdx
  website/content/docs/job-specification/affinity.mdx
  website/content/docs/job-specification/artifact.mdx
  website/content/docs/job-specification/change_script.mdx
  website/content/docs/job-specification/check.mdx
  website/content/docs/job-specification/check_restart.mdx
  website/content/docs/job-specification/connect.mdx
  website/content/docs/job-specification/constraint.mdx
  website/content/docs/job-specification/consul.mdx
  website/content/docs/job-specification/csi_plugin.mdx
  website/content/docs/job-specification/device.mdx
  website/content/docs/job-specification/disconnect.mdx
  website/content/docs/job-specification/dispatch_payload.mdx
  website/content/docs/job-specification/env.mdx
  website/content/docs/job-specification/ephemeral_disk.mdx
  website/content/docs/job-specification/expose.mdx
  website/content/docs/job-specification/gateway.mdx
  website/content/docs/job-specification/group.mdx
  website/content/docs/job-specification/hcl2/expressions.mdx
  website/content/docs/job-specification/hcl2/index.mdx
  website/content/docs/job-specification/hcl2/locals.mdx
  website/content/docs/job-specification/hcl2/syntax.mdx
  website/content/docs/job-specification/hcl2/variables.mdx
  website/content/docs/job-specification/identity.mdx
  website/content/docs/job-specification/index.mdx
  website/content/docs/job-specification/job.mdx
  website/content/docs/job-specification/lifecycle.mdx
  website/content/docs/job-specification/logs.mdx
  website/content/docs/job-specification/meta.mdx
  website/content/docs/job-specification/migrate.mdx
  website/content/docs/job-specification/multiregion.mdx
  website/content/docs/job-specification/network.mdx
  website/content/docs/job-specification/numa.mdx
  website/content/docs/job-specification/parameterized.mdx
  website/content/docs/job-specification/periodic.mdx
  website/content/docs/job-specification/proxy.mdx
  website/content/docs/job-specification/reschedule.mdx
  website/content/docs/job-specification/resources.mdx
  website/content/docs/job-specification/restart.mdx
  website/content/docs/job-specification/scaling.mdx
  website/content/docs/job-specification/schedule.mdx
  website/content/docs/job-specification/service.mdx
  website/content/docs/job-specification/sidecar_service.mdx
  website/content/docs/job-specification/sidecar_task.mdx
  website/content/docs/job-specification/spread.mdx
  website/content/docs/job-specification/task.mdx
  website/content/docs/job-specification/template.mdx
  website/content/docs/job-specification/transparent_proxy.mdx
  website/content/docs/job-specification/ui.mdx
  website/content/docs/job-specification/update.mdx
  website/content/docs/job-specification/upstreams.mdx
  website/content/docs/job-specification/vault.mdx
  website/content/docs/job-specification/volume.mdx
  website/content/docs/job-specification/volume_mount.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, backport/website, backport/1.10.x

#25879 docs: emphasize HOME and USER env vars for tasks that use custom `user` setting
  website/content/docs/job-specification/task.mdx
  website/content/docs/runtime/environment.mdx
Labels: theme/docs, backport/website, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25800 scheduler: account for affinity value of zero in score normalization
  .changelog/25800.txt
  scheduler/rank.go
  scheduler/rank_test.go
Labels: type/bug, theme/scheduling, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25799 state store: persist NextAllocation correctly when upserting allocations
  .changelog/25799.txt
  nomad/state/state_store.go
  nomad/state/state_store_test.go
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25891 Docs: Community plugins section refactor
  website/content/plugins/drivers/community/containerd.mdx
  website/content/plugins/drivers/community/firecracker-task-driver.mdx
  website/content/plugins/drivers/community/iis.mdx
  website/content/plugins/drivers/community/index.mdx
  website/content/plugins/drivers/community/jail-task-driver.mdx
  website/content/plugins/drivers/community/lightrun.mdx
  website/content/plugins/drivers/community/nomad-iis.mdx
  website/content/plugins/drivers/community/nspawn.mdx
  website/content/plugins/drivers/community/pledge.mdx
  website/content/plugins/drivers/community/pot.mdx
  website/content/plugins/drivers/community/rookout.mdx
  website/content/plugins/drivers/community/singularity.mdx
  website/data/plugins-nav-data.json
  website/redirects.js
Labels: theme/docs, backport/website, backport/1.10.x

#25904 semgrep: adjust forbidden package rule for regex matches
  .semgrep/imports.yml
Labels: theme/testing

#25902 host volumes: -force flag for delete
  .changelog/25902.txt
  api/host_volumes.go
  command/volume_delete.go
  nomad/host_volume_endpoint.go
  nomad/host_volume_endpoint_test.go
  nomad/structs/host_volumes.go
  website/content/docs/commands/volume/delete.mdx
Labels: type/enhancement, theme/storage, backport/1.10.x

#25518 Docs: SEO updates to operations, other specs sections
  website/content/docs/operations/aws-oidc-provider.mdx
  website/content/docs/operations/benchmarking.mdx
  website/content/docs/operations/federation/failure.mdx
  website/content/docs/operations/federation/index.mdx
  website/content/docs/operations/index.mdx
  website/content/docs/operations/ipv6-support.mdx
  website/content/docs/operations/key-management.mdx
  website/content/docs/operations/metrics-reference.mdx
  website/content/docs/operations/monitoring-nomad.mdx
  website/content/docs/operations/nomad-agent.mdx
  website/content/docs/other-specifications/acl-policy.mdx
  website/content/docs/other-specifications/index.mdx
  website/content/docs/other-specifications/namespace.mdx
  website/content/docs/other-specifications/node-pool.mdx
  website/content/docs/other-specifications/quota.mdx
  website/content/docs/other-specifications/variables.mdx
  website/content/docs/other-specifications/volume/capability.mdx
  website/content/docs/other-specifications/volume/csi.mdx
  website/content/docs/other-specifications/volume/host.mdx
  website/content/docs/other-specifications/volume/index.mdx
  website/content/docs/other-specifications/volume/mount_options.mdx
  website/content/docs/other-specifications/volume/topology_request.mdx
  website/data/docs-nav-data.json
Labels: theme/docs, backport/website, backport/1.10.x

#25798 Docs: Add "/v1" where missing so endpoint docs are consistent
  website/content/api-docs/acl/roles.mdx
  website/content/api-docs/allocations.mdx
  website/content/api-docs/jobs.mdx
  website/content/api-docs/quotas.mdx
  website/content/api-docs/recommendations.mdx
  website/content/api-docs/scaling-policies.mdx
  website/content/api-docs/sentinel-policies.mdx
  website/content/api-docs/services.mdx
  website/content/api-docs/status.mdx
  website/content/api-docs/ui.mdx
Labels: theme/docs, backport/website, backport/ent/1.8.x+ent, backport/1.8.x, backport/ent/1.9.x+ent, backport/1.9.x, backport/1.10.x

#25909 testing: migrate nomad/state off testify
  .semgrep/imports.yml
  nomad/state/deployment_events_test.go
  nomad/state/events_test.go
  nomad/state/indexer/indexer_test.go
  nomad/state/indexer/time_test.go
  nomad/state/schema_test.go
  nomad/state/state_store_acl_test.go
  nomad/state/state_store_service_registration_test.go
  nomad/state/state_store_test.go
Labels: theme/testing, backport/1.10.x, backport/ent/1.10.x+ent

#25921 ipv6: normalize addrs per RFC-5942 §4
  command/agent/config.go
  command/agent/config_parse.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/extra-consul.hcl
  command/agent/testdata/extra-consul.json
  command/agent/testdata/extra-vault.hcl
  command/agent/testdata/extra-vault.json
  helper/ipaddr/ipaddr.go
  helper/ipaddr/ipaddr_test.go
Labels: theme/ipv6

#25785 Add NodeMaxAllocations to client configuration
  .changelog/25785.txt
  api/nodes.go
  client/client.go
  client/config/config.go
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/test-resources/client_with_maxallocs.hcl
  command/agent/test-resources/client_with_maxallocs.json
  command/agent/testdata/sample0.json
  command/node_status.go
  nomad/structs/funcs.go
  nomad/structs/funcs_test.go
  nomad/structs/structs.go
  scheduler/rank_test.go
  website/content/docs/commands/node/status.mdx
  website/content/docs/configuration/client.mdx
Labels: type/enhancement, theme/scheduling, backport/1.10.x

#25881 ui: Handle new token self response object when ACLs are disabled.
  .changelog/25881.txt
  ui/app/services/token.js
Labels: backport/1.10.x

#25905 [UI] Update selector of test in job actions
  ui/tests/pages/jobs/job/actions.js
Labels: theme/ui, backport/1.10.x

#25903 host volumes: add configuration to GC on node GC
  .changelog/25903.txt
  api/nodes.go
  client/client.go
  client/config/config.go
  command/agent/agent.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/host_volume_endpoint.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/host_volume_endpoint.go
  nomad/state/events_test.go
  nomad/state/state_store.go
  nomad/state/state_store_host_volumes.go
  nomad/state/state_store_host_volumes_test.go
  nomad/structs/structs.go
  website/content/docs/configuration/client.mdx
Labels: type/enhancement, theme/storage, backport/1.10.x

#25944 e2e: mention in the terraform readme that we require a local Consul binary
  e2e/terraform/README.md
Labels: theme/e2e

#25922 client: add once mode to template block
  .changelog/25922.txt
  api/jobs_test.go
  api/tasks.go
  client/allocrunner/taskrunner/template/template.go
  client/allocrunner/taskrunner/template/template_test.go
  client/allocrunner/taskrunner/template_hook.go
  client/allocrunner/taskrunner/template_hook_test.go
  command/agent/job_endpoint.go
  e2e/vaultcompat/input/cat_jwt.hcl
  e2e/vaultcompat/input/restricted_jwt.hcl
  e2e/vaultcompat/vaultcompat_test.go
  nomad/structs/diff_test.go
  nomad/structs/structs.go
  website/content/docs/job-specification/template.mdx
Labels: backport/1.10.x

#25923 cancel waiting evals when allocs reconnect
  .changelog/25923.txt
  nomad/eval_broker.go
  nomad/eval_broker_test.go
  nomad/fsm.go
  nomad/node_endpoint.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/structs.go
Labels: type/bug, theme/scheduling, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#25943 e2e: correct `TestSingleAffinities` behavior
  e2e/affinities/affinities.go
Labels: theme/e2e
