Repository hashicorp/nomad, pull requests merged in 2025-10, with the labels that each got.

#26867 e2e: Add ability to skip known bad Consul versions in compat test.
  e2e/consulcompat/shared_download_test.go
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#26872 state: nil-check waiting evals before attempting to cancel them
  .changelog/26872.txt
  nomad/fsm.go
Labels: type/bug, backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#26664 vault: default tlsSkipVerify to false
  .changelog/26664.txt
  nomad/encrypter.go
  nomad/encrypter_test.go
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#26875 e2e: correction to assertions in system scheduler tests
  e2e/scheduler_system/input/system_canary_v1_100.nomad.hcl
  e2e/scheduler_system/systemsched_test.go
Labels: theme/e2e

#26841 Add preserve-resources flag
  .changelog/26841.txt
  api/jobs.go
  api/jobs_test.go
  command/agent/job_endpoint.go
  command/job_run.go
  nomad/fsm.go
  nomad/job_endpoint.go
  nomad/job_endpoint_test.go
  nomad/state/deployment_events_test.go
  nomad/state/events_test.go
  nomad/state/state_store.go
  nomad/state/state_store_test.go
  nomad/structs/structs.go
  website/content/api-docs/jobs.mdx
  website/content/commands/job/run.mdx
Labels: backport/1.10.x

#26877 build: add architecture detection to CNI makefile target
  GNUmakefile
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x

#26880 client: upgrade consul-template to include template hashing bugfix
  .changelog/26880.txt
  go.mod
  go.sum
Labels: theme/consul-template, backport/ent/1.8.x+ent, dependencies, backport/ent/1.9.x+ent, backport/1.10.x

#26858 Add job_max_count option to keep Nomad server from running out of memory
  .changelog/26858.txt
  command/agent/agent.go
  command/agent/agent_test.go
  command/agent/config.go
  command/agent/config_parse_test.go
  command/agent/config_test.go
  command/agent/testdata/basic.hcl
  command/agent/testdata/basic.json
  nomad/config.go
  nomad/job_endpoint.go
  nomad/job_endpoint_hooks.go
  nomad/job_endpoint_hooks_test.go
  nomad/job_endpoint_test.go
  nomad/structs/structs.go
  website/content/docs/configuration/server.mdx
  website/content/docs/upgrade/upgrade-specific.mdx
Labels: type/enhancement, theme/scheduling

#26662 scheduler: skip setting preferred node when nodepool changes
  .changelog/26662.txt
  scheduler/generic_sched.go
  scheduler/generic_sched_test.go
Labels: backport/ent/1.8.x+ent, backport/ent/1.9.x+ent, backport/1.10.x
